#!/usr/bin/env bash
# install-opencode.sh — deploy the Kaola-Workflow opencode edition into a project.
#
# Additive standalone installer (does NOT modify install.sh or the
# claude/codex/gitlab/gitea editions). opencode is a runtime (like Codex), not a
# git forge, so it is delivered the opencode-native way: opencode.json + .opencode/.
#
# FORGE: --forge=github|gitlab|gitea selects which forge's workflow prose and support
# scripts to deploy (default github). The runtime is still not a forge — this installer
# remains standalone and additive — but the workflow PROSE is forge-shaped (gh vs glab
# vs tea, PR vs MR, per-forge script basenames), so a GitLab/Gitea project must not be
# handed GitHub-shaped commands. The forge variants are GENERATED by
# sync-opencode-edition.js from the same routing surfaces the other editions ship;
# github renders .opencode/, a forge renders .opencode-<forge>/.
#
# Usage:
#   ./install-opencode.sh                         # deploy into the current directory
#   ./install-opencode.sh --target /path/to/repo  # deploy into a specific project
#   ./install-opencode.sh --forge=gitlab          # deploy the GitLab-shaped edition
#   ./install-opencode.sh --global                # deploy agents+commands to ~/.config/opencode
#   ./install-opencode.sh --regenerate            # refresh the generated tree from canonical here
#
# Models: the default install seeds opencode.json with the two Kaola tiers as
# reasoning-EFFORT VARIANTS of your inherited model (no model is pinned — both tiers
# inherit the model you are already using in opencode): the reasoning tier gets the
# model's TOP effort variant, the standard tier its SECOND (e.g. max/high on GLM-5.2).
# This installer seeds it only if absent, so re-running never clobbers your choices.
# Override the inherited model via KAOLA_OPENCODE_INHERIT_MODEL, or pin a tier to a
# different model via KAOLA_OPENCODE_STANDARD_MODEL / _REASONING_MODEL.
#
# COMMAND SET: the install deploys the workflow command set (finalize, workflow-init,
# workflow-next) into .opencode/command/. The generated .opencode/command/*
# are produced by sync-opencode-edition.js from the canonical sources.
#
# The generated commands + agents resolve support scripts via an
# OPENCODE-NATIVE path (${OPENCODE_CONFIG_DIR:-$HOME/.config/opencode}/kaola-workflow/scripts)
# — there is NO $CLAUDE_PLUGIN_ROOT and NO ~/.claude/kaola-workflow in the deployed tree.
# install_support_scripts deploys to that opencode-native dir (not ~/.claude/).
#
# DEPLOY LAYOUT (scope-dependent — opencode resolves agents/commands/plugins differently by scope):
#   - PROJECT (--target/$PWD): agents/commands/plugins/hooks live under <project>/.opencode/{...}
#     (the project-local .opencode dir opencode scans).
#   - GLOBAL (--global): they live DIRECTLY under the config root ${OPENCODE_CONFIG_DIR:-$HOME/.config/opencode}/{...}
#     (NOT a nested .opencode/ — the config dir IS opencode's global ".opencode equivalent"; a nested
#     ~/.config/opencode/.opencode/ is never scanned). copy_tree takes a `layout_root` arg for exactly this.
#   - opencode.json always lands at the config/project root (dest_root), never under the layout subtree.
#
# REINSTALL IS SELF-HEALING: copy_tree PRUNES kaola-owned command files before re-copying, so a
# reinstall converges to exactly the workflow command set on disk. --uninstall removes the full
# deployed surface; see uninstall_edition.
#
# AGENTS ARE MANIFEST-DRIVEN (they cannot be blind-pruned). Commands live in a reserved
# `kaola-workflow-*` / `workflow-*` namespace, so the prune above is namespace-complete and a
# retired command self-heals. Agent files are NOT namespaced (bare `code-explorer.md`) and share
# the deployed agent dir with user-authored agents, so there is no pattern that means "ours".
# Instead copy_tree records `<filename>\t<sha256>` for every agent it deploys, and the NEXT
# install removes exactly the previously-recorded files the tree no longer ships that are still
# byte-identical to what we wrote. A file absent from the manifest is user-authored and is never
# touched; a recorded file the user then edited is their work and is never touched either.

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
TARGET=""
GLOBAL=0
REGENERATE=0
UNINSTALL=0
YES=0
NO_SCRIPTS=0
FORGE="github"

usage() {
  cat <<'EOF'
Usage: ./install-opencode.sh [--target DIR] [--forge=github|gitlab|gitea] [--global]
                            [--regenerate] [--uninstall] [--no-scripts] [--yes]
  --target DIR     deploy into DIR (default: current directory)
  --forge F        github (default), gitlab, or gitea — which forge's workflow prose
                   and support scripts to deploy
  --global         deploy agents+commands+plugin+hooks into ~/.config/opencode (all projects)
  --regenerate     refresh the in-repo .opencode/ tree from canonical, then exit
  --uninstall      remove the kaola-deployed opencode edition from the resolved scope
                   (honors --target/--global), then exit (see UNINSTALL below)
  --no-scripts     skip installing support scripts (see SUPPORT SCRIPTS below)
  --yes            non-interactive (accept the default deploy path)

SUPPORT SCRIPTS: workflow commands locate scripts via kaola_script(), which searches
./scripts/ and ${OPENCODE_CONFIG_DIR:-$HOME/.config/opencode}/kaola-workflow/scripts/
(opencode-native, honoring $OPENCODE_CONFIG_DIR). For a CONSUMER project (not this repo)
the installer copies the support scripts there so the commands resolve. Self-dev in this
repo needs none of that (./scripts/ is used directly).

UNINSTALL: --uninstall removes ONLY kaola-deployed artifacts from the resolved scope
(project DEST_ROOT via --target/$PWD, or --global ${OPENCODE_CONFIG_DIR:-$HOME/.config/opencode}):
the deployed agents/commands/plugin/hooks (agents by deploy manifest + source-tree filename,
the rest by source-tree filename — never a blind rm of a dir; the manifest is what lets an
agent RETIRED since the last install still be removed) and the opencode-native support scripts.
The SHARED ~/.config/kaola-workflow/config.json is kept for any co-installed Claude/Codex edition.
Your own opencode.json (model/permission config) is PRESERVED. A subsequent bare install
then deploys the workflow edition.
EOF
}

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    --target) TARGET="${2:?--target requires a directory}"; shift 2 ;;
    --forge=*) FORGE="${1#--forge=}"; shift ;;
    --forge) FORGE="${2:?--forge requires github, gitlab, or gitea}"; shift 2 ;;
    --global) GLOBAL=1; shift ;;
    --regenerate) REGENERATE=1; shift ;;
    --uninstall) UNINSTALL=1; shift ;;
    --no-scripts) NO_SCRIPTS=1; shift ;;
    -y|--yes) YES=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

# Resolve the forge layout from the ONE source the generators use (scripts/runtime-edition-forge.js),
# so this installer never restates a forge dir or a per-forge script name. An unknown forge fails
# here, loudly, before anything is written.
FORGE_HELPER="$SCRIPT_DIR/scripts/runtime-edition-forge.js"
if [[ ! -f "$FORGE_HELPER" ]]; then
  echo "Install error: forge layout helper missing: $FORGE_HELPER" >&2
  exit 1
fi
if ! FORGE_SUFFIX="$(node "$FORGE_HELPER" --forge="$FORGE" --out-suffix)"; then
  echo "Install error: unknown forge \"$FORGE\" (expected github, gitlab, or gitea)" >&2
  exit 2
fi
if ! FORGE_SCRIPTS_DIR="$(node "$FORGE_HELPER" --forge="$FORGE" --scripts-dir)"; then
  echo "Install error: cannot resolve the support-script dir for forge $FORGE" >&2
  exit 1
fi
# The generated tree this forge deploys FROM: .opencode for github, .opencode-<forge> otherwise.
SOURCE_TREE="$SCRIPT_DIR/.opencode$FORGE_SUFFIX"

# Always ensure the in-repo generated tree is fresh before copying from it (install only — an
# uninstall removes by source filename and must not regenerate the repo tree).
if [[ "$UNINSTALL" -ne 1 ]]; then
  echo "Kaola-Workflow · opencode edition ($FORGE) — refreshing generated tree..."
  node "$SCRIPT_DIR/scripts/sync-opencode-edition.js" --forge="$FORGE" --check >/dev/null 2>&1 \
    || node "$SCRIPT_DIR/scripts/sync-opencode-edition.js" --forge="$FORGE" --write >/dev/null
fi

if [[ "$REGENERATE" -eq 1 ]]; then
  echo "Regenerated $SOURCE_TREE from canonical. Done."
  exit 0
fi

# Workflow command set: the commands deployed into .opencode/command/. Any OTHER command fails
# CLOSED (skipped + warned) so a future canonical command cannot silently widen the install.
# Single source of truth for the deploy set (used by copy_tree).
WORKFLOW_COMMANDS=(
  kaola-workflow-finalize.md workflow-init.md workflow-next.md
)
in_array() { local needle="$1"; shift; local x; for x in "$@"; do [[ "$x" == "$needle" ]] && return 0; done; return 1; }

# Name of the deploy manifest recorded inside the deployed agent dir (a dotfile, so it never
# shadows an agent). Same tab-separated `<filename>\t<sha256>` shape install.sh uses.
AGENT_MANIFEST_NAME=".kaola-workflow-agent-manifest"
SOURCE_AGENT_DIR="$SOURCE_TREE/agent"

sha256_file() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  else
    shasum -a 256 "$1" | awk '{print $1}'
  fi
}

# True when `$1` is a plain file name: non-empty, no path separator, not `.`/`..`,
# not absolute. A deploy manifest records BASENAMES only, so anything else is corruption or
# tampering and must never be turned into a filesystem path.
is_plain_basename() {
  local n="${1-}"
  [[ -n "$n" ]] || return 1
  case "$n" in
    */*|*\\*|.|..) return 1 ;;
  esac
  return 0
}

# Print the hash the given manifest records for `$1` and return 0 when the manifest lists that
# exact name; return 1 (printing nothing) otherwise. Literal string compare — the name is never
# interpolated into a path or a pattern.
manifest_row_hash() {
  local want="$1" file="$2" row_name row_hash row_rest
  [[ -f "$file" ]] || return 1
  while IFS=$'\t' read -r row_name row_hash row_rest || [[ -n "${row_name:-}" ]]; do
    [[ -n "${row_name:-}" ]] || continue
    [[ "$row_name" == "$want" ]] || continue
    printf '%s\n' "${row_hash:-}"
    return 0
  done < "$file"
  return 1
}

# Report every manifest row that is not a plain file name. Such a row cannot describe a file this
# installer deployed into the agent dir, so it is named on stderr and then ignored.
warn_unsafe_manifest_names() {
  local file="$1" row_name row_rest
  [[ -f "$file" ]] || return 0
  while IFS=$'\t' read -r row_name row_rest || [[ -n "${row_name:-}" ]]; do
    [[ -n "${row_name:-}" ]] || continue
    if ! is_plain_basename "$row_name"; then
      echo "warning: ignoring agent manifest entry that is not a plain file name: $row_name" >&2
    fi
  done < "$file"
  return 0
}

# Remove agents a PREVIOUS install deployed that the current tree no longer ships. Fail-closed:
# a candidate must be recorded in the previous manifest, absent from the canonical source tree,
# present on disk, and still byte-identical to the hash we recorded. Anything else is left alone.
# An absent/empty previous manifest sweeps NOTHING.
#
# The sweep ENUMERATES THE AGENT DIRECTORY and intersects it against the previous manifest, so a
# delete path is never CONSTRUCTED from a manifest-supplied name: a row holding `../…`, an
# absolute path, or a separator simply matches no directory entry and is reported + skipped.
sweep_retired_agents() {
  local prev_manifest="$1"
  local agent_dir="$2"
  local dest base prev_hash current_hash
  [[ -f "$prev_manifest" ]] || return 0
  warn_unsafe_manifest_names "$prev_manifest"
  for dest in "$agent_dir"/*.md; do
    [[ -f "$dest" ]] || continue
    base="$(basename "$dest")"
    # Still shipped by the tree → it was just re-copied; never a sweep candidate.
    if [[ -f "$SOURCE_AGENT_DIR/$base" ]]; then continue; fi
    prev_hash=""
    if ! prev_hash="$(manifest_row_hash "$base" "$prev_manifest")"; then continue; fi
    [[ -n "$prev_hash" ]] || continue
    current_hash="$(sha256_file "$dest")"
    [[ "$current_hash" == "$prev_hash" ]] || continue
    rm -f "$dest"
    echo "Removed retired agent: $dest"
  done
  return 0
}

copy_tree() {
  local dest_root="$1"    # holds opencode.json (config/project root)
  # layout_root: the dir that DIRECTLY holds agent/command/plugins/hooks. Project → $dest_root/.opencode;
  # Global → $dest_root (the config root itself; opencode never scans a nested .opencode/ there).
  local layout_root="${2:-$dest_root/.opencode}"
  mkdir -p "$layout_root/agent" "$layout_root/command" \
           "$layout_root/plugins" "$layout_root/hooks"
  # Deploy the hooks adapter plugin from the TRACKED template source (templates/opencode/plugins/).
  # This is NOT the self-referential .opencode/plugins/ copy — the tracked template is the canonical
  # source and is always present. A missing plugin is a LOUD install error (no 2>/dev/null || true).
  # Run BEFORE the self-dev guard because even in self-dev mode the destination
  # ($layout_root/plugins/) is distinct from the source (templates/opencode/plugins/).
  cp "$SCRIPT_DIR/templates/opencode/plugins/"*.js "$layout_root/plugins/"
  # Self-dev guard: deploying the edition into its OWN source repo means the canonical .opencode and
  # the destination layout are the same directory, so `cp` would refuse ("X and X are identical") and
  # trip `set -e`. In that case the generated tree already IS the live one — skip the (no-op) copy.
  if [[ "$SOURCE_TREE" -ef "$layout_root" ]]; then
    echo "Self-dev deploy (source .opencode is already the live tree) → copy skipped."
    return
  fi
  # Agents: snapshot the previous deploy manifest, re-copy the current source set, record the new
  # manifest, then sweep whatever the previous manifest owned that the tree has since retired.
  local agent_manifest prev_manifest manifest_tmp agent_file agent_base agent_count
  agent_manifest="$layout_root/agent/$AGENT_MANIFEST_NAME"
  prev_manifest="$(mktemp)"
  if [[ -f "$agent_manifest" ]]; then
    cp "$agent_manifest" "$prev_manifest"
  fi
  manifest_tmp="$(mktemp)"
  agent_count=0
  for agent_file in "$SOURCE_AGENT_DIR/"*.md; do
    [[ -f "$agent_file" ]] || continue
    agent_base="$(basename "$agent_file")"
    cp "$agent_file" "$layout_root/agent/$agent_base"
    printf '%s\t%s\n' "$agent_base" "$(sha256_file "$layout_root/agent/$agent_base")" >> "$manifest_tmp"
    agent_count=$((agent_count + 1))
  done
  # Fail CLOSED on an empty agent source (the previous bare `cp <dir>/*.md` errored out here; a
  # silent zero-agent deploy would be the 5.4.0 silent-empty regression class).
  if [[ "$agent_count" -eq 0 ]]; then
    rm -f "$manifest_tmp" "$prev_manifest"
    echo "Install error: no agent sources found in $SOURCE_AGENT_DIR" >&2
    exit 1
  fi
  mv "$manifest_tmp" "$agent_manifest"
  sweep_retired_agents "$prev_manifest" "$layout_root/agent"
  rm -f "$prev_manifest"
  # The COMMAND deploy is SELF-HEALING. First PRUNE every kaola-owned command file from the dest,
  # then re-copy the workflow command set via a fail-CLOSED ALLOWLIST: a command not in
  # WORKFLOW_COMMANDS is skipped + warned, so a future canonical command cannot silently widen the
  # install. Agents/plugins/hooks are always fully deployed.
  local stale_pattern stale_file
  for stale_pattern in "kaola-workflow-*.md" "workflow-init.md" "workflow-next.md"; do
    for stale_file in "$layout_root/command/"$stale_pattern; do
      [[ -f "$stale_file" ]] || continue
      rm -f "$stale_file"
    done
  done
  local command_file base
  for command_file in "$SOURCE_TREE/command/"*.md; do
    [[ -f "$command_file" ]] || continue
    base="$(basename "$command_file")"
    if ! in_array "$base" "${WORKFLOW_COMMANDS[@]}"; then
      echo "warning: skipping unrecognized command not in the workflow command set: $base" >&2
      continue
    fi
    cp "$command_file" "$layout_root/command/$base"
  done
  cp "$SOURCE_TREE/hooks/"*.sh "$layout_root/hooks/" 2>/dev/null || true
  chmod +x "$layout_root/hooks/"*.sh 2>/dev/null || true
  echo "Installed workflow agents+commands+plugin+hooks → $layout_root/"
}

# Remove ONLY kaola-deployed artifacts from the resolved scope, by source-tree filename (never a blind
# rm of a dir the user may share). Preserves the user-owned opencode.json and the SHARED
# ~/.config/kaola-workflow/config.json (kept for any co-installed Claude/Codex edition).
uninstall_edition() {
  local dest_root layout_root
  if [[ "$GLOBAL" -eq 1 ]]; then
    dest_root="${OPENCODE_CONFIG_DIR:-$HOME/.config/opencode}"
    layout_root="$dest_root"
  else
    dest_root="${TARGET:-$PWD}"
    layout_root="$dest_root/.opencode"
  fi
  echo "Uninstalling Kaola-Workflow · opencode edition ($FORGE) from → $layout_root"
  if [[ "$SOURCE_TREE" -ef "$layout_root" ]]; then
    echo "Refusing to uninstall the edition's OWN source tree ($layout_root). No-op." >&2
    return
  fi
  local f base sub
  # Agents: remove the UNION of what the deploy manifest records this installer wrote — which
  # includes agents RETIRED since that install and therefore absent from the current source tree —
  # and the current source-tree filenames, so an install predating the manifest still uninstalls
  # cleanly. Manifest-listed names only; an unlisted file is user-authored and is left alone.
  #
  # Like the sweep, this ENUMERATES the agent dir and intersects it against the manifest rather
  # than building `$layout_root/agent/<manifest name>` — a manifest row is never treated as a
  # path, so a row holding `../…` or an absolute path cannot delete anything outside the dir.
  local agent_manifest dest
  agent_manifest="$layout_root/agent/$AGENT_MANIFEST_NAME"
  if [[ -f "$agent_manifest" ]]; then
    warn_unsafe_manifest_names "$agent_manifest"
    for dest in "$layout_root/agent/"*.md; do
      [[ -f "$dest" ]] || continue
      base="$(basename "$dest")"
      if manifest_row_hash "$base" "$agent_manifest" >/dev/null; then rm -f "$dest"; fi
    done
    rm -f "$agent_manifest"
  fi
  for f in "$SOURCE_AGENT_DIR/"*.md;                         do [[ -f "$f" ]] || continue; rm -f "$layout_root/agent/$(basename "$f")"; done
  for f in "$SOURCE_TREE/command/"*.md;                      do [[ -f "$f" ]] || continue; rm -f "$layout_root/command/$(basename "$f")"; done
  for f in "$SCRIPT_DIR/templates/opencode/plugins/"*.js;    do [[ -f "$f" ]] || continue; rm -f "$layout_root/plugins/$(basename "$f")"; done
  for f in "$SOURCE_TREE/hooks/"*.sh;                        do [[ -f "$f" ]] || continue; rm -f "$layout_root/hooks/$(basename "$f")"; done
  for sub in command agent plugins hooks; do rmdir "$layout_root/$sub" 2>/dev/null || true; done
  [[ "$GLOBAL" -eq 1 ]] || rmdir "$layout_root" 2>/dev/null || true
  echo "Removed deployed agents/commands/plugin/hooks."
  # Support scripts (opencode-native dir; honors $OPENCODE_CONFIG_DIR).
  local scripts_dir="${OPENCODE_CONFIG_DIR:-$HOME/.config/opencode}/kaola-workflow/scripts"
  local manifest="$SCRIPT_DIR/scripts/kaola-workflow-install-manifest.js"
  if [[ -f "$manifest" && -d "$scripts_dir" ]]; then
    local name
    while IFS= read -r name || [[ -n "$name" ]]; do
      [[ -n "$name" ]] || continue
      # Defense in depth: the manifest emits plain script basenames. Anything else never
      # becomes a delete path.
      if ! is_plain_basename "$name"; then
        echo "warning: ignoring support-script manifest entry that is not a plain file name: $name" >&2
        continue
      fi
      rm -f "$scripts_dir/$name"
    done < <(node "$manifest" --forge="$FORGE" --scripts 2>/dev/null)
    rmdir "$scripts_dir" 2>/dev/null || true
    rmdir "${OPENCODE_CONFIG_DIR:-$HOME/.config/opencode}/kaola-workflow" 2>/dev/null || true
    echo "Removed deployed support scripts."
  fi
  if [[ -f "$dest_root/opencode.json" ]]; then
    echo "Preserved $dest_root/opencode.json (user-owned model/permission config)."
  fi
  echo "Uninstall complete. A fresh ./install-opencode.sh now deploys the workflow edition."
}

# Install the support scripts the workflow commands invoke (kaola_script() search path includes
# ${OPENCODE_CONFIG_DIR:-$HOME/.config/opencode}/kaola-workflow/scripts/ — opencode-native, #544).
# Reuses the single-source install manifest; only meaningful for consumer projects.
install_support_scripts() {
  if [[ "$NO_SCRIPTS" -eq 1 ]]; then
    echo "Support scripts skipped (--no-scripts)."
    return
  fi
  local manifest="$SCRIPT_DIR/scripts/kaola-workflow-install-manifest.js"
  [[ -f "$manifest" ]] || { echo "warning: install manifest not found; skipping support scripts." >&2; return; }
  local dest="${OPENCODE_CONFIG_DIR:-$HOME/.config/opencode}/kaola-workflow/scripts"
  mkdir -p "$dest"
  local name src
  while IFS= read -r name || [[ -n "$name" ]]; do
    [[ -n "$name" ]] || continue
    src="$FORGE_SCRIPTS_DIR/$name"
    # The Oracle Kernel is de-duplicated to a single canonical source; a forge tree that
    # does not carry its own copy resolves it from scripts/ (mirrors install.sh).
    [[ -f "$src" ]] || src="$SCRIPT_DIR/scripts/$name"
    if [[ ! -f "$src" ]]; then
      echo "Install error: allowlisted support script missing from source for forge $FORGE: $name" >&2
      exit 1
    fi
    cp "$src" "$dest/$name"
    chmod +x "$dest/$name"
  done < <(node "$manifest" --forge="$FORGE" --scripts 2>/dev/null)
  echo "Installed support scripts → $dest (kaola_script() search path; forge $FORGE)"
}

seed_config() {
  local dest_root="$1"
  local cfg="$dest_root/opencode.json"
  if [[ -f "$cfg" ]]; then
    echo "Preserved existing $cfg (your model choices are kept)."
    return
  fi
  # Generate via the sync renderer. With --adapt it emits the two-tier EFFORT-VARIANT
  # config for your inherited model (KAOLA_OPENCODE_INHERIT_MODEL env, else the global
  # opencode.json "model"): reasoning tier → the contract's TOP variant, standard tier
  # → its SECOND variant. The effort KNOB is CONTRACT-KEYED (mapTier + CONTRACT_EFFORT_TABLE
  # + contractForProvider in kaola-workflow-adaptive-schema.js): GLM-5.2/z.ai → Anthropic
  # contract (thinking budget), OpenAI → reasoningEffort, Google → reasoningEffort. An
  # UNRECOGNIZED provider gets the safe default contract (reasoningEffort high/medium — a
  # real top/second split, no de-tier). A falsy/absent model still renders the neutral
  # template (both tiers inherit your opencode default).
  node "$SCRIPT_DIR/scripts/sync-opencode-edition.js" --write-config-to "$cfg" --adapt
  echo "Seeded $cfg — effort tiers adapted to your inherited model (contract-keyed)."
  echo "  GLM-5.2/z.ai → Anthropic contract (thinking budget); OpenAI → reasoningEffort;"
  echo "  Google → reasoningEffort; unknown → safe default (no de-tier)."
  echo "  ⚠ Switched your opencode model? Re-run with KAOLA_OPENCODE_INHERIT_MODEL=<provider>/<model>"
  echo "  to regenerate the variant definitions (the dispatch path re-resolves regardless)."
  echo "  Override the inherited model via KAOLA_OPENCODE_INHERIT_MODEL, or pin a tier via"
  echo "  KAOLA_OPENCODE_STANDARD_MODEL / _REASONING_MODEL env."
}

# --uninstall short-circuits the install entirely (functions are defined above).
if [[ "$UNINSTALL" -eq 1 ]]; then
  uninstall_edition
  exit 0
fi

if [[ "$GLOBAL" -eq 1 ]]; then
  DEST_ROOT="${OPENCODE_CONFIG_DIR:-$HOME/.config/opencode}"
  echo "Deploying globally ($FORGE) → $DEST_ROOT"
  # GLOBAL: opencode scans the config root DIRECTLY (agents/commands/plugins under ~/.config/opencode/,
  # NOT a nested .opencode/). layout_root = the config root itself.
  copy_tree "$DEST_ROOT" "$DEST_ROOT"
  seed_config "$DEST_ROOT"
  install_support_scripts
else
  DEST_ROOT="${TARGET:-$PWD}"
  echo "Deploying into project ($FORGE) → $DEST_ROOT"
  # PROJECT: opencode scans <project>/.opencode/. layout_root = $DEST_ROOT/.opencode (copy_tree default).
  copy_tree "$DEST_ROOT" "$DEST_ROOT/.opencode"
  seed_config "$DEST_ROOT"
  install_support_scripts
fi

echo ""
echo "Next: open the project in opencode and run a workflow command, e.g.:"
echo "  /workflow-init"
echo "Models resolve from opencode.json; both tiers inherit your opencode default unless you pin them."
