#!/usr/bin/env bash
# install-droid.sh — deploy the Kaola-Workflow Droid CLI edition.
#
# Droid is a coding-agent RUNTIME, not a git forge. It is delivered the Droid-native
# way: skills under ~/.factory/skills/ plus a managed machine-global AGENTS.md carrier
# at ~/.factory/AGENTS.md. This runtime installs no Kaola role profiles and NO hooks by
# design (the adapter records a measured capability; Droid's hook surface exists but this
# edition deliberately writes no hooks.json, no settings.json, no custom droids, and no
# MCP servers). The always-loaded carrier is the compact recovery path, exactly like the
# other native_only managed_region runtimes.
#
# FORGE: --forge=github|gitlab|gitea selects which forge's workflow prose and
# support scripts to deploy (default github). The forge variants are GENERATED by
# sync-droid-edition.js from the same routing surfaces the other editions ship.
#
# Usage:
#   ./install-droid.sh                         # global install into ~/.factory
#   ./install-droid.sh --global                # same as above
#   ./install-droid.sh --project[=DIR]         # project skills under DIR/.factory
#   ./install-droid.sh --check                 # verify installed artifacts
#   ./install-droid.sh --uninstall             # remove only Kaola-deployed artifacts
#   ./install-droid.sh --forge=gitlab          # deploy GitLab-shaped workflow prose
#
# Global layout:
#   ~/.factory/skills/<name>/SKILL.md
#   ~/.factory/AGENTS.md   (managed global contract, via kaola-workflow-global-contract.js —
#                           per-target: --runtime droid installs/checks ONLY this runtime's own carrier,
#                           as the LAST install step; no other runtime's home is written)
#   ~/.factory/kaola-workflow/scripts  (support scripts)
#
# DROID_HOME relocates this install for hermetic tests only; Droid discovers skills and
# the personal AGENTS.md carrier from the Droid config home (~/.factory by default).
#
# Project layout:
#   <DIR>/.factory/skills/<name>/SKILL.md
#   plus the global recovery carrier above in ~/.factory.
#
# Uninstall: --uninstall removes ONLY Kaola-deployed artifacts — the skills by rendered
# directory name (never a blind rm of the skills dir) and the support scripts by manifest
# name. The machine-global ~/.factory/AGENTS.md carrier is shared transaction state owned
# by kaola-workflow-global-contract.js, not this edition, and is never removed here.

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
FORGE="github"
GLOBAL=1
TARGET=""
CHECK=0
UNINSTALL=0
YES=0

usage() {
  cat <<'EOF'
Usage: ./install-droid.sh [--global] [--project[=DIR]] [--forge=github|gitlab|gitea] [--check] [--uninstall] [-y|--yes]
  --global          install global skills into ~/.factory (default)
  --project[=DIR]   install project skills into DIR/.factory (default: CWD)
  --forge F         github (default), gitlab, or gitea
  --check           verify installed artifacts without mutating
  --uninstall       remove only Kaola-deployed skills and support scripts, then exit
  -y, --yes         non-interactive (ignored; accepted for install-all compatibility)
  -h, --help        show this help

Uninstall removes ONLY Kaola-deployed artifacts from the resolved scope: the deployed
skills (by source-tree directory name — never a blind rm of a dir), and the support
scripts (by manifest name). The machine-global ~/.factory/AGENTS.md carrier is owned by
the shared global-contract transaction and is NOT removed by this edition uninstall.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --forge=*) FORGE="${1#*=}"; shift ;;
    --forge) FORGE="${2:?--forge requires github, gitlab, or gitea}"; shift 2 ;;
    --global) GLOBAL=1; shift ;;
    --project) GLOBAL=0; TARGET="$PWD"; shift ;;
    --project=*) GLOBAL=0; TARGET="${1#*=}"; shift ;;
    --target) GLOBAL=0; TARGET="${2:?--target requires a directory}"; shift 2 ;;
    --check) CHECK=1; shift ;;
    --uninstall) UNINSTALL=1; shift ;;
    -y|--yes) YES=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

HOME_ROOT="${DROID_HOME:-${HOME:?}/.factory}"

STAGE="$(mktemp -d "${TMPDIR:-/tmp}/kw-droid-install.XXXXXX")"
cleanup() { rm -rf "$STAGE"; }
trap cleanup EXIT

echo "Kaola-Workflow · droid edition ($FORGE) — staging generated artifacts..."
node "$SCRIPT_DIR/scripts/sync-droid-edition.js" --forge="$FORGE" --tree-root="$STAGE" --write

FORGE_HELPER="$SCRIPT_DIR/scripts/runtime-edition-forge.js"
if [[ ! -f "$FORGE_HELPER" ]]; then
  echo "Install error: forge layout helper missing: $FORGE_HELPER" >&2
  exit 1
fi
if ! FORGE_SUFFIX="$(node "$FORGE_HELPER" --forge="$FORGE" --out-suffix)"; then
  echo "Install error: unknown forge \"$FORGE\" (expected github, gitlab, or gitea)" >&2
  exit 2
fi
if ! FORGE_SCRIPTS_DIR="$(node "$FORGE_HELPER" --forge="$FORGE" --scripts-dir)"; then
  echo "Install error: cannot resolve the support-script dir for forge $FORGE" >&2
  exit 1
fi

SOURCE_TREE="$STAGE/.factory$FORGE_SUFFIX"
SUPPORT_DEST="$HOME_ROOT/kaola-workflow/scripts"
SUPPORT_MANIFEST=()
while IFS= read -r line; do [[ -n "$line" ]] && SUPPORT_MANIFEST+=("$line"); done \
  < <(node "$SCRIPT_DIR/scripts/kaola-workflow-install-manifest.js" --forge="$FORGE" --scripts)

if [[ "$GLOBAL" == 1 ]]; then
  SKILLS_DEST="$HOME_ROOT/skills"
else
  PROJECT_DIR="${TARGET:-$PWD}"
  SKILLS_DEST="$PROJECT_DIR/.factory/skills"
fi

# Install or check the managed global AGENTS.md carrier through the per-target
# global-contract CLI (#1087): --runtime droid selects ONLY the droid-local target, so
# another runtime's carrier conflict or drift can never fail this installer.
# Both modes report the droid-local target instead of discarding the CLI exit code.
global_contract() {
  local mode="$1" output rc=0
  output="$(node "$SCRIPT_DIR/scripts/kaola-workflow-global-contract.js" "$mode" --runtime droid --json 2>&1)" || rc=$?
  node - "$mode" "$rc" "$HOME_ROOT/AGENTS.md" "$output" <<'NODE'
const [mode, rcText, carrierPath, output] = process.argv.slice(2);
const rc = Number(rcText);
let doc = null;
try { doc = JSON.parse(output); } catch (_) { /* non-JSON output is reported verbatim below */ }
const target = doc && Array.isArray(doc.targets) ? doc.targets.find(t => t.id === 'droid-local') : null;
const overall = doc && doc.status ? doc.status : 'UNKNOWN';
const droid = target ? target.status : 'ABSENT';
if (rc === 0) process.exit(0);
console.error(`${mode}: droid global contract ${overall} (exit ${rc}); droid-local carrier ${droid} at ${carrierPath}`);
if (!doc) console.error(output);
else if (doc.error) console.error(`${mode}: ${doc.error}`);
if (mode === 'check') console.error('check: run ./install-droid.sh to refresh the droid global contract carrier');
process.exit(1);
NODE
}

install_global_carrier() { global_contract install; }
check_global_carrier() { global_contract check; }

# Install the forge-selected support scripts into the Droid-native helper root.
install_support_scripts() {
  mkdir -p "$SUPPORT_DEST"
  local src name
  for name in "${SUPPORT_MANIFEST[@]}"; do
    src="$FORGE_SCRIPTS_DIR/$name"
    [[ -f "$src" ]] || { echo "Install error: support script missing: $src" >&2; exit 1; }
    cp "$src" "$SUPPORT_DEST/$name"
  done
}

# Verify installed support scripts match the canonical source.
check_support_scripts() {
  local bad=0 src name
  if [[ ! -d "$SUPPORT_DEST" ]]; then
    echo "check: missing $SUPPORT_DEST" >&2; return 1
  fi
  for name in "${SUPPORT_MANIFEST[@]}"; do
    src="$FORGE_SCRIPTS_DIR/$name"
    if [[ ! -f "$SUPPORT_DEST/$name" ]]; then
      echo "check: missing support script $name" >&2; bad=1
    elif ! diff -q "$src" "$SUPPORT_DEST/$name" >/dev/null 2>&1; then
      echo "check: support script $name drifted from canonical" >&2; bad=1
    fi
  done
  return "$bad"
}

# Verify that the staged .factory/skills tree matches the destination.
check_artifacts() {
  local src_skills="$SOURCE_TREE/skills"
  local bad=0
  if [[ ! -d "$SKILLS_DEST" || ! -d "$src_skills" ]]; then
    echo "check: missing $SKILLS_DEST" >&2; bad=1
  elif ! diff -qr "$src_skills" "$SKILLS_DEST" >/dev/null 2>&1; then
    echo "check: skills do not match rendered source" >&2; bad=1
  fi
  return "$bad"
}

# #1087 (#1086 F2): release this runtime's reference on the shared ~/.config/kaola-workflow block.
# The registry keeps the block while any other runtime (or another scope of this one) holds a
# reference and removes it only when this was the last one.
release_shared_config_ref() {
  local scope_args=(--scope global) out
  if [[ "$GLOBAL" -ne 1 ]]; then scope_args=(--scope project --target "${TARGET:-$PWD}"); fi
  if out="$(node "$SCRIPT_DIR/scripts/kaola-workflow-shared-refs.js" deregister \
      --block kaola-config --runtime droid "${scope_args[@]}")"; then
    echo "Released shared config reference (droid): $out"
  else
    echo "warning: shared config reference not released ($out); ~/.config/kaola-workflow left in place." >&2
  fi
}

# Remove only Kaola-deployed artifacts: rendered skill dirs by source-tree directory
# name (never a blind rm of the skills dir) and support scripts by manifest name.
uninstall_edition() {
  local bad=0 name
  if [[ -d "$SKILLS_DEST" ]]; then
    # Remove rendered skill dirs by source-tree directory name — never a blind rm of a dir.
    for name in $(cd "$SOURCE_TREE/skills" 2>/dev/null && printf '%s\n' */ 2>/dev/null | sed 's#/##' || true); do
      [[ -n "$name" ]] || continue
      if [[ -d "$SKILLS_DEST/$name" ]]; then
        rm -rf "$SKILLS_DEST/$name"
        echo "Removed skill: $SKILLS_DEST/$name"
      fi
    done
    # Remove the skills dir itself only if Kaola artifacts left nothing else behind.
    rmdir "$SKILLS_DEST" 2>/dev/null || true
  fi
  if [[ -d "$SUPPORT_DEST" ]]; then
    for name in "${SUPPORT_MANIFEST[@]}"; do
      if [[ -f "$SUPPORT_DEST/$name" ]]; then
        rm -f "$SUPPORT_DEST/$name"
        echo "Removed support script: $SUPPORT_DEST/$name"
      fi
    done
    rmdir "$SUPPORT_DEST/scripts" 2>/dev/null || true
    rmdir "$SUPPORT_DEST/kaola-workflow" 2>/dev/null || true
    rmdir "$SUPPORT_DEST" 2>/dev/null || true
    # Zero-residue: drop the emptied kaola-workflow parent dir too.
    rmdir "$(dirname "$SUPPORT_DEST")" 2>/dev/null || true
  fi
  release_shared_config_ref
  echo "Droid edition uninstalled (machine-global ~/.factory/AGENTS.md carrier untouched — shared transaction state)."
  return "$bad"
}

if [[ "$CHECK" == 1 ]]; then
  check_global_carrier
  check_support_scripts || exit 1
  check_artifacts || exit 1
  echo "Droid edition check passed."
  exit 0
fi

if [[ "$UNINSTALL" == 1 ]]; then
  uninstall_edition
  exit 0
fi

install_support_scripts

mkdir -p "$SKILLS_DEST"
if [[ -d "$SOURCE_TREE/skills" ]]; then
  for src in "$SOURCE_TREE/skills/"*; do
    [[ -d "$src" ]] || continue
    name="$(basename "$src")"
    mkdir -p "$SKILLS_DEST/$name"
    cp "$src/SKILL.md" "$SKILLS_DEST/$name/SKILL.md"
  done
fi

# Last step (#1087): this runtime's own global-contract carrier.
install_global_carrier

echo "Installed Droid edition ($FORGE) — skills: $SKILLS_DEST, support scripts: $SUPPORT_DEST, global carrier: $HOME_ROOT/AGENTS.md"
