#!/usr/bin/env bash
# install-dsh.sh — deploy the Kaola-Workflow DSH (DeepSeek Harness) edition.
#
# DSH is a coding-agent RUNTIME, not a git forge. It is delivered the DSH-native
# way: skills under ~/.dsh/skills/ plus a managed machine-global AGENTS.md carrier
# at ~/.dsh/AGENTS.md. This runtime installs no Kaola role profiles and NO hooks by
# design. It never writes ~/.dsh/.env, ~/.dsh/settings.yaml, credentials, or
# model/provider config — those are user-owned DSH surfaces.
#
# FORGE: --forge=github|gitlab|gitea selects which forge's workflow prose and
# support scripts to deploy (default github). The forge variants are GENERATED by
# sync-dsh-edition.js from the same routing surfaces the other editions ship.
#
# Usage:
#   ./install-dsh.sh                         # global install into ~/.dsh
#   ./install-dsh.sh --global                # same as above
#   ./install-dsh.sh --project[=DIR]         # project skills under DIR/.dsh
#   ./install-dsh.sh --check                 # verify installed artifacts
#   ./install-dsh.sh --uninstall             # remove only Kaola-deployed artifacts
#   ./install-dsh.sh --forge=gitlab          # deploy GitLab-shaped workflow prose
#
# Global layout:
#   ~/.dsh/skills/<name>/SKILL.md
#   ~/.dsh/AGENTS.md   (managed global contract, via kaola-workflow-global-contract.js —
#                       per-target: --runtime dsh installs/checks ONLY this runtime's own carrier,
#                       as the LAST install step; no other runtime's home is written)
#   ~/.dsh/kaola-workflow/scripts  (support scripts)
#
# DSH_HOME relocates this install for hermetic tests only; DSH discovers skills and
# the user-global AGENTS.md carrier from the DSH home (~/.dsh by default).
#
# Project layout:
#   <DIR>/.dsh/skills/<name>/SKILL.md
#   plus the global recovery carrier above in ~/.dsh.
#
# Uninstall: --uninstall removes ONLY Kaola-deployed artifacts — the skills by rendered
# directory name (never a blind rm of the skills dir) and the support scripts by manifest
# name. A global-scope uninstall (the default) also strips this runtime's OWN managed region
# in ~/.dsh/AGENTS.md through its own per-target record (kaola-workflow-global-contract.js
# uninstall --runtime dsh); an owner-edited carrier is refused and left in place. A --project
# uninstall leaves the machine-global carrier alone.

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
FORGE="github"
GLOBAL=1
TARGET=""
CHECK=0
UNINSTALL=0
YES=0

usage() {
  cat <<'EOF'
Usage: ./install-dsh.sh [--global] [--project[=DIR]] [--forge=github|gitlab|gitea] [--check] [--uninstall] [-y|--yes]
  --global          install global skills into ~/.dsh (default)
  --project[=DIR]   install project skills into DIR/.dsh (default: CWD)
  --forge F         github (default), gitlab, or gitea
  --check           verify installed artifacts without mutating
  --uninstall       remove only Kaola-deployed skills, support scripts, and (global scope)
                    this runtime's own global-contract carrier, then exit
  -y, --yes         non-interactive (ignored; accepted for install-all compatibility)
  -h, --help        show this help

Uninstall removes ONLY Kaola-deployed artifacts from the resolved scope: the deployed
skills (by source-tree directory name — never a blind rm of a dir), and the support
scripts (by manifest name). A global-scope uninstall also strips this runtime's own
managed region in ~/.dsh/AGENTS.md through its own per-target global-contract record
(an owner-edited carrier is refused and left in place); --project leaves that carrier.
This installer never writes settings.yaml, .env, credentials, or model/provider config.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --forge=*) FORGE="${1#*=}"; shift ;;
    --forge) FORGE="${2:?--forge requires github, gitlab, or gitea}"; shift 2 ;;
    --global) GLOBAL=1; shift ;;
    --project) GLOBAL=0; TARGET="$PWD"; shift ;;
    --project=*) GLOBAL=0; TARGET="${1#*=}"; shift ;;
    --target) GLOBAL=0; TARGET="${2:?--target requires a directory}"; shift 2 ;;
    --check) CHECK=1; shift ;;
    --uninstall) UNINSTALL=1; shift ;;
    -y|--yes) YES=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

HOME_ROOT="${DSH_HOME:-${HOME:?}/.dsh}"

STAGE="$(mktemp -d "${TMPDIR:-/tmp}/kw-dsh-install.XXXXXX")"
cleanup() { rm -rf "$STAGE"; }
trap cleanup EXIT

echo "Kaola-Workflow · dsh edition ($FORGE) — staging generated artifacts..."
node "$SCRIPT_DIR/scripts/sync-dsh-edition.js" --forge="$FORGE" --tree-root="$STAGE" --write

FORGE_HELPER="$SCRIPT_DIR/scripts/runtime-edition-forge.js"
if [[ ! -f "$FORGE_HELPER" ]]; then
  echo "Install error: forge layout helper missing: $FORGE_HELPER" >&2
  exit 1
fi
if ! FORGE_SUFFIX="$(node "$FORGE_HELPER" --forge="$FORGE" --out-suffix)"; then
  echo "Install error: unknown forge \"$FORGE\" (expected github, gitlab, or gitea)" >&2
  exit 2
fi
if ! FORGE_SCRIPTS_DIR="$(node "$FORGE_HELPER" --forge="$FORGE" --scripts-dir)"; then
  echo "Install error: cannot resolve the support-script dir for forge $FORGE" >&2
  exit 1
fi

SOURCE_TREE="$STAGE/.dsh$FORGE_SUFFIX"
SUPPORT_DEST="$HOME_ROOT/kaola-workflow/scripts"
SUPPORT_MANIFEST=()
while IFS= read -r line; do [[ -n "$line" ]] && SUPPORT_MANIFEST+=("$line"); done \
  < <(node "$SCRIPT_DIR/scripts/kaola-workflow-install-manifest.js" --forge="$FORGE" --scripts)

if [[ "$GLOBAL" == 1 ]]; then
  SKILLS_DEST="$HOME_ROOT/skills"
else
  PROJECT_DIR="${TARGET:-$PWD}"
  SKILLS_DEST="$PROJECT_DIR/.dsh/skills"
fi

# Install or check the managed global AGENTS.md carrier through the per-target
# global-contract CLI (#1087): --runtime dsh selects ONLY the dsh-local target, so
# another runtime's carrier conflict or drift can never fail this installer.
# Both modes report the dsh-local target instead of discarding the CLI exit code.
global_contract() {
  local mode="$1" output rc=0
  output="$(node "$SCRIPT_DIR/scripts/kaola-workflow-global-contract.js" "$mode" --runtime dsh --json 2>&1)" || rc=$?
  node - "$mode" "$rc" "$HOME_ROOT/AGENTS.md" "$output" <<'NODE'
const [mode, rcText, carrierPath, output] = process.argv.slice(2);
const rc = Number(rcText);
let doc = null;
try { doc = JSON.parse(output); } catch (_) { /* non-JSON output is reported verbatim below */ }
const target = doc && Array.isArray(doc.targets) ? doc.targets.find(t => t.id === 'dsh-local') : null;
const overall = doc && doc.status ? doc.status : 'UNKNOWN';
const dsh = target ? target.status : 'ABSENT';
if (rc === 0) process.exit(0);
console.error(`${mode}: dsh global contract ${overall} (exit ${rc}); dsh-local carrier ${dsh} at ${carrierPath}`);
if (!doc) console.error(output);
else if (doc.error) console.error(`${mode}: ${doc.error}`);
if (mode === 'check') console.error('check: run ./install-dsh.sh to refresh the dsh global contract carrier');
process.exit(1);
NODE
}

install_global_carrier() { global_contract install; }
check_global_carrier() { global_contract check; }

# Install the forge-selected support scripts into the DSH-native helper root.
install_support_scripts() {
  mkdir -p "$SUPPORT_DEST"
  local src name
  for name in "${SUPPORT_MANIFEST[@]}"; do
    src="$FORGE_SCRIPTS_DIR/$name"
    [[ -f "$src" ]] || { echo "Install error: support script missing: $src" >&2; exit 1; }
    cp "$src" "$SUPPORT_DEST/$name"
  done
}

# Verify installed support scripts match the canonical source.
check_support_scripts() {
  local bad=0 src name
  if [[ ! -d "$SUPPORT_DEST" ]]; then
    echo "check: missing $SUPPORT_DEST" >&2; return 1
  fi
  for name in "${SUPPORT_MANIFEST[@]}"; do
    src="$FORGE_SCRIPTS_DIR/$name"
    if [[ ! -f "$SUPPORT_DEST/$name" ]]; then
      echo "check: missing support script $name" >&2; bad=1
    elif ! diff -q "$src" "$SUPPORT_DEST/$name" >/dev/null 2>&1; then
      echo "check: support script $name drifted from canonical" >&2; bad=1
    fi
  done
  return "$bad"
}

# Verify that the staged .dsh/skills tree matches the destination.
check_artifacts() {
  local src_skills="$SOURCE_TREE/skills"
  local bad=0
  if [[ ! -d "$SKILLS_DEST" || ! -d "$src_skills" ]]; then
    echo "check: missing $SKILLS_DEST" >&2; bad=1
  elif ! diff -qr "$src_skills" "$SKILLS_DEST" >/dev/null 2>&1; then
    echo "check: skills do not match rendered source" >&2; bad=1
  fi
  return "$bad"
}

# #1087 (#1086 F3): a global-scope uninstall strips this runtime's OWN global-contract carrier
# through its own per-target record and releases that record's shared-block reference. A carrier
# the owner edited since install is refused (OWNER_CONFLICT) and left in place; no other runtime's
# carrier or record is read for removal. A project-scope uninstall leaves the machine-global carrier.
uninstall_global_carrier() {
  [[ "$GLOBAL" -eq 1 ]] || return 0
  local output rc=0 status
  output="$(node "$SCRIPT_DIR/scripts/kaola-workflow-global-contract.js" uninstall --runtime dsh --json 2>&1)" || rc=$?
  status="$(node -e 'try { console.log(JSON.parse(process.argv[1]).status || "UNKNOWN"); } catch (_) { console.log("UNKNOWN"); }' "$output")"
  if [[ "$rc" -eq 0 ]]; then
    echo "dsh global contract carrier: $status"
  else
    echo "warning: dsh global contract carrier left in place ($status, exit $rc)" >&2
    printf '%s\n' "$output" >&2
  fi
}

# #1087 (#1086 F2): release this runtime's reference on the shared ~/.config/kaola-workflow block.
# The registry keeps the block while any other runtime (or another scope of this one) holds a
# reference and removes it only when this was the last one.
release_shared_config_ref() {
  local scope_args=(--scope global) out
  if [[ "$GLOBAL" -ne 1 ]]; then scope_args=(--scope project --target "${TARGET:-$PWD}"); fi
  if out="$(node "$SCRIPT_DIR/scripts/kaola-workflow-shared-refs.js" deregister \
      --runtime dsh "${scope_args[@]}")"; then
    echo "Released shared config reference (dsh): $out"
  else
    echo "warning: shared config reference not released ($out); ~/.config/kaola-workflow left in place." >&2
  fi
}

# Remove only Kaola-deployed artifacts: rendered skill dirs by source-tree directory
# name (never a blind rm of the skills dir) and support scripts by manifest name.
uninstall_edition() {
  local bad=0 name
  if [[ -d "$SKILLS_DEST" ]]; then
    for name in $(cd "$SOURCE_TREE/skills" 2>/dev/null && printf '%s\n' */ 2>/dev/null | sed 's#/##' || true); do
      [[ -n "$name" ]] || continue
      if [[ -d "$SKILLS_DEST/$name" ]]; then
        rm -rf "$SKILLS_DEST/$name"
        echo "Removed skill: $SKILLS_DEST/$name"
      fi
    done
    rmdir "$SKILLS_DEST" 2>/dev/null || true
  fi
  if [[ -d "$SUPPORT_DEST" ]]; then
    for name in "${SUPPORT_MANIFEST[@]}"; do
      if [[ -f "$SUPPORT_DEST/$name" ]]; then
        rm -f "$SUPPORT_DEST/$name"
        echo "Removed support script: $SUPPORT_DEST/$name"
      fi
    done
    rmdir "$SUPPORT_DEST" 2>/dev/null || true
    rmdir "$(dirname "$SUPPORT_DEST")" 2>/dev/null || true
  fi
  uninstall_global_carrier
  release_shared_config_ref
  echo "DSH edition uninstalled."
  return "$bad"
}

if [[ "$CHECK" == 1 ]]; then
  check_global_carrier
  check_support_scripts || exit 1
  check_artifacts || exit 1
  echo "DSH edition check passed."
  exit 0
fi

if [[ "$UNINSTALL" == 1 ]]; then
  uninstall_edition
  exit 0
fi

install_support_scripts

mkdir -p "$SKILLS_DEST"
if [[ -d "$SOURCE_TREE/skills" ]]; then
  for src in "$SOURCE_TREE/skills/"*; do
    [[ -d "$src" ]] || continue
    name="$(basename "$src")"
    mkdir -p "$SKILLS_DEST/$name"
    cp "$src/SKILL.md" "$SKILLS_DEST/$name/SKILL.md"
  done
fi

# Last step (#1087): this runtime's own global-contract carrier.
install_global_carrier

echo "Installed DSH edition ($FORGE) — skills: $SKILLS_DEST, support scripts: $SUPPORT_DEST, global carrier: $HOME_ROOT/AGENTS.md"
