#!/usr/bin/env bash
# install-grok.sh — deploy the Kaola-Workflow grok edition into a project (or globally).
#
# Additive standalone installer (does NOT modify install.sh, install-opencode.sh,
# install-kimi.sh, or the claude/codex/gitlab/gitea editions). Grok CLI is a runtime
# (like opencode and Kimi), not a git forge, so it is delivered the grok-native way:
# named agents under agents/, flat slash commands under commands/, and a generated
# Grok Rule that stays in model context across compaction.
#
# FORGE: --forge=github|gitlab|gitea selects which forge's workflow prose and support
# scripts to deploy (default github). The forge variants are GENERATED by
# sync-grok-edition.js from the same routing surfaces the other editions ship;
# github renders .grok/, a forge renders .grok-<forge>/.
#
# Usage:
#   ./install-grok.sh                         # deploy into the current directory
#   ./install-grok.sh --target /path/to/repo  # deploy into a specific project
#   ./install-grok.sh --forge=gitlab          # deploy the GitLab-shaped edition
#   ./install-grok.sh --global                # deploy agents+commands to ${GROK_HOME:-~/.grok}
#   ./install-grok.sh --regenerate            # refresh the generated tree from canonical here
#
# DEPLOY LAYOUT (scope-dependent):
#   - PROJECT (--target/$PWD): agents and commands land under <project>/.grok/{agents,commands}.
#   - GLOBAL (--global): they land DIRECTLY under ${GROK_HOME:-$HOME/.grok}/{agents,commands}.
#   - Support scripts + hook scripts land under the grok home (user-level):
#     ${GROK_HOME:-$HOME/.grok}/kaola-workflow/{scripts,hooks}.
#   - GLOBAL installs one complete Rule under ${GROK_HOME:-$HOME/.grok}/rules/.
#   - PROJECT installs the same generated Rule under <project>/.grok/rules/.
#   - No Grok compact hook is installed: passive hook stdout is not model context.
#
# Models: every subagent inherits the session model and effort. This installer seeds no
# per-role model or effort config.

set -euo pipefail

KW_TMPDIR="${TMPDIR:-/tmp}"
case "$KW_TMPDIR" in
  /*) ;;
  *) KW_TMPDIR="/tmp" ;;
esac

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
TARGET=""
GLOBAL=0
REGENERATE=0
UNINSTALL=0
YES=0
NO_SCRIPTS=0
FORGE="github"

usage() {
  cat <<'EOF'
Usage: ./install-grok.sh [--target DIR] [--forge=github|gitlab|gitea] [--global]
                         [--regenerate] [--uninstall] [--no-scripts] [--yes]
  --target DIR     deploy agents+commands into DIR/.grok (default: current directory)
  --forge F        github (default), gitlab, or gitea — which forge's workflow prose
                   and support scripts to deploy
  --global         deploy agents+commands into ${GROK_HOME:-~/.grok} (all projects)
  --regenerate     refresh the in-repo .grok/ tree from canonical, then exit
  --uninstall      remove the kaola-deployed grok edition from the resolved scope
                   (honors --target/--global), then exit
  --no-scripts     skip support scripts and historical hook-script cleanup
  --yes            non-interactive (skip the confirmation prompt)

SUPPORT SCRIPTS + RULES: workflow commands resolve support scripts via
${GROK_HOME:-$HOME/.grok}/kaola-workflow/scripts (the list comes from
scripts/kaola-workflow-install-manifest.js). A global install puts the recovery
Rule under GROK_HOME; a project install puts it under <project>/.grok/rules.

UNINSTALL: --uninstall removes ONLY kaola-deployed artifacts from the resolved
scope: the deployed agents, commands, and recovery Rule (by source-tree filename),
plus shared support scripts + hook scripts under the grok home.
The SHARED ~/.config/kaola-workflow/config.json is kept for any co-installed
Claude/Codex/opencode/kimi edition.
EOF
}

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    --target) TARGET="${2:?--target requires a directory}"; shift 2 ;;
    --forge=*) FORGE="${1#--forge=}"; shift ;;
    --forge) FORGE="${2:?--forge requires github, gitlab, or gitea}"; shift 2 ;;
    --global) GLOBAL=1; shift ;;
    --regenerate) REGENERATE=1; shift ;;
    --uninstall) UNINSTALL=1; shift ;;
    --no-scripts) NO_SCRIPTS=1; shift ;;
    -y|--yes) YES=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

grok_home() { printf '%s\n' "${GROK_HOME:-$HOME/.grok}"; }

FORGE_HELPER="$SCRIPT_DIR/scripts/runtime-edition-forge.js"
if [[ ! -f "$FORGE_HELPER" ]]; then
  echo "Install error: forge layout helper missing: $FORGE_HELPER" >&2
  exit 1
fi
if ! FORGE_SUFFIX="$(node "$FORGE_HELPER" --forge="$FORGE" --out-suffix)"; then
  echo "Install error: unknown forge \"$FORGE\" (expected github, gitlab, or gitea)" >&2
  exit 2
fi
if ! FORGE_SCRIPTS_DIR="$(node "$FORGE_HELPER" --forge="$FORGE" --scripts-dir)"; then
  echo "Install error: cannot resolve the support-script dir for forge $FORGE" >&2
  exit 1
fi
if ! TREE_ROOT="$(node "$SCRIPT_DIR/scripts/sync-grok-edition.js" --print-tree-root)"; then
  echo "Install error: cannot resolve where the generated grok tree lands" >&2
  exit 1
fi
SOURCE_TREE="$TREE_ROOT/.grok$FORGE_SUFFIX"

if [[ "$UNINSTALL" -ne 1 ]]; then
  echo "Kaola-Workflow · grok edition ($FORGE) — refreshing generated tree..."
  node "$SCRIPT_DIR/scripts/sync-grok-edition.js" --forge="$FORGE" --check >/dev/null 2>&1 \
    || node "$SCRIPT_DIR/scripts/sync-grok-edition.js" --forge="$FORGE" --write >/dev/null
fi

if [[ "$REGENERATE" -eq 1 ]]; then
  echo "Regenerated $SOURCE_TREE from canonical. Done."
  exit 0
fi

# Names here are removed on install and uninstall by basename.
RETIRED_AGENTS=()
RETIRED_COMMANDS=()
RETIRED_HOOKS=(kaola-workflow-subagent-dispatch-log.sh)
RETIRED_SUPPORT_SCRIPTS=()
RETIRED_COMPACT_HOOK_SHA256="e2b3de7a84558d27d8f78fab2e2d83febce8019b44a6d2cb5399877d85daa96f"
RETIRED_COMPACT_PROMPT_SHA256="91d82092e5fc7245bcec2c412967239819a9bf9b38a74abd27d86df7a0b45dac"

WORKFLOW_COMMANDS=(
  kaola-workflow-finalize workflow-init workflow-next
)
in_array() { local needle="$1"; shift; local x; for x in "$@"; do [[ "$x" == "$needle" ]] && return 0; done; return 1; }

is_plain_basename() {
  local n="${1-}"
  [[ -n "$n" ]] || return 1
  case "$n" in
    */*|*\\*|.|..) return 1 ;;
  esac
  return 0
}

remove_retired_support_scripts() {
  local dir="$1"
  [[ -d "$dir" ]] || return 0
  local base name
  for base in "${RETIRED_SUPPORT_SCRIPTS[@]+"${RETIRED_SUPPORT_SCRIPTS[@]}"}"; do
    for name in "$base" \
      "${base/#kaola-workflow-/kaola-gitlab-workflow-}" \
      "${base/#kaola-workflow-/kaola-gitea-workflow-}"; do
      is_plain_basename "$name" || continue
      [[ -f "$dir/$name" ]] || continue
      rm -f "$dir/$name"
      echo "Removed retired support script: $dir/$name"
    done
  done
}

remove_retired_compact_hook_file() {
  local file="$1" actual
  [[ -f "$file" && ! -L "$file" ]] || return 0
  actual="$(shasum -a 256 "$file" | awk '{print $1}')"
  if [[ "$actual" == "$RETIRED_COMPACT_HOOK_SHA256" ]]; then
    rm -f "$file"
    echo "Removed retired Grok compact hook mapping: $file"
  else
    echo "Preserved modified/unowned historical Grok hook mapping: $file" >&2
  fi
}

remove_retired_compact_prompt_file() {
  local file="$1" actual
  [[ -f "$file" && ! -L "$file" ]] || return 0
  actual="$(shasum -a 256 "$file" | awk '{print $1}')"
  if [[ "$actual" == "$RETIRED_COMPACT_PROMPT_SHA256" ]]; then
    rm -f "$file"
    echo "Removed retired Grok hook prompt: $file"
  else
    echo "Preserved modified/unowned historical Grok hook prompt: $file" >&2
  fi
}

copy_agents() {
  local dest="$1"
  mkdir -p "$dest"
  if [[ "$SOURCE_TREE/agents" -ef "$dest" ]]; then
    echo "Self-dev deploy (source $SOURCE_TREE/agents is already the live tree) → copy skipped."
    return
  fi
  local retired
  for retired in "${RETIRED_AGENTS[@]+"${RETIRED_AGENTS[@]}"}"; do
    [[ -f "$dest/$retired.md" ]] || continue
    rm -f "$dest/$retired.md"
  done
  local src base count=0
  for src in "$SOURCE_TREE/agents/"*.md; do
    [[ -f "$src" ]] || continue
    base="$(basename "$src")"
    cp "$src" "$dest/$base"
    count=$((count + 1))
  done
  if [[ "$count" -eq 0 ]]; then
    echo "Install error: no agent sources found in $SOURCE_TREE/agents" >&2
    exit 1
  fi
  echo "Installed workflow agents → $dest/ ($count)"
}

copy_commands() {
  local dest="$1"
  mkdir -p "$dest"
  if [[ "$SOURCE_TREE/commands" -ef "$dest" ]]; then
    echo "Self-dev deploy (source $SOURCE_TREE/commands is already the live tree) → copy skipped."
    return
  fi
  local retired
  for retired in "${RETIRED_COMMANDS[@]+"${RETIRED_COMMANDS[@]}"}"; do
    [[ -f "$dest/$retired.md" ]] || continue
    rm -f "$dest/$retired.md"
  done
  local src base count=0 skipped=0
  for src in "$SOURCE_TREE/commands/"*.md; do
    [[ -f "$src" ]] || continue
    base="$(basename "$src" .md)"
    if ! in_array "$base" "${WORKFLOW_COMMANDS[@]}"; then
      echo "warning: skipping unrecognized command not in the workflow set: $base" >&2
      skipped=$((skipped + 1))
      continue
    fi
    cp "$src" "$dest/$base.md"
    count=$((count + 1))
  done
  if [[ "$count" -eq 0 ]]; then
    if [[ "$skipped" -gt 0 ]]; then
      echo "Install error: all $skipped command source(s) in $SOURCE_TREE/commands fall outside the workflow set" >&2
    else
      echo "Install error: no command sources found in $SOURCE_TREE/commands" >&2
    fi
    exit 1
  fi
  echo "Installed workflow commands → $dest/"
}

install_support_scripts() {
  if [[ "$NO_SCRIPTS" -eq 1 ]]; then
    echo "Support scripts skipped (--no-scripts)."
    return
  fi
  local home; home="$(grok_home)"
  local manifest="$SCRIPT_DIR/scripts/kaola-workflow-install-manifest.js"
  [[ -f "$manifest" ]] || { echo "warning: install manifest not found; skipping support scripts." >&2; return; }
  local dest="$home/kaola-workflow/scripts"
  mkdir -p "$dest"
  local name src
  local deployed=()
  while IFS= read -r name || [[ -n "$name" ]]; do
    [[ -n "$name" ]] || continue
    src="$FORGE_SCRIPTS_DIR/$name"
    [[ -f "$src" ]] || src="$SCRIPT_DIR/scripts/$name"
    if [[ ! -f "$src" ]]; then
      echo "Install error: allowlisted support script missing from source for forge $FORGE: $name" >&2
      exit 1
    fi
    cp "$src" "$dest/$name"
    chmod +x "$dest/$name"
    deployed+=("$name")
  done < <(node "$manifest" --forge="$FORGE" --scripts 2>/dev/null)
  if [[ ${#deployed[@]} -gt 0 ]]; then
    local stale_file stale_name is_current
    for stale_file in "$dest"/*.js; do
      [[ -f "$stale_file" ]] || continue
      stale_name="$(basename "$stale_file")"
      is_current=0
      for name in "${deployed[@]}"; do
        [[ "$name" == "$stale_name" ]] && is_current=1 && break
      done
      if [[ "$is_current" -eq 0 ]]; then
        rm -f "$stale_file"
        echo "Removed stale script: $stale_file"
      fi
    done
  fi
  echo "Installed support scripts → $dest (forge $FORGE)"
  local hooks_dest="$home/kaola-workflow/hooks"
  mkdir -p "$hooks_dest"
  local retired
  for retired in "${RETIRED_HOOKS[@]+"${RETIRED_HOOKS[@]}"}"; do
    [[ -f "$hooks_dest/$retired" ]] || continue
    rm -f "$hooks_dest/$retired"
    echo "Removed retired hook script: $hooks_dest/$retired"
  done
  local hook hook_base
  for hook in "$SOURCE_TREE/hooks/"*.sh; do
    [[ -f "$hook" ]] || continue
    hook_base="$(basename "$hook")"
    cp "$hook" "$hooks_dest/$hook_base"
    chmod 755 "$hooks_dest/$hook_base"
  done
  echo "Installed hook scripts → $hooks_dest"
}

install_recovery_rule() {
  local home dest src retired_mapping retired_prompt
  home="$(grok_home)"
  src="$SOURCE_TREE/rules/kaola-workflow-compact-recovery.md"
  [[ -f "$src" ]] || { echo "Install error: generated recovery Rule missing: $src" >&2; exit 1; }
  if [[ "$GLOBAL" -eq 1 ]]; then
    dest="$home/rules/kaola-workflow-compact-recovery.md"
    retired_mapping="$home/hooks/kaola-workflow-hooks.json"
    retired_prompt="$home/kaola-workflow/prompts/kaola-workflow-compact-recovery.md"
  else
    dest="$LAYOUT_DEST/rules/kaola-workflow-compact-recovery.md"
    retired_mapping="$LAYOUT_DEST/hooks/hooks.json"
    retired_prompt="$LAYOUT_DEST/hooks/kaola-workflow-compact-recovery.md"
  fi
  mkdir -p "$(dirname "$dest")"
  if [[ ! "$src" -ef "$dest" ]]; then
    cp "$src" "$dest"
  fi
  echo "Installed compact-safe Grok Rule → $dest"
  remove_retired_compact_hook_file "$retired_mapping"
  remove_retired_compact_prompt_file "$retired_prompt"
  rmdir "$(dirname "$retired_mapping")" 2>/dev/null || true
  rmdir "$(dirname "$retired_prompt")" 2>/dev/null || true
}

uninstall_edition() {
  local home layout
  home="$(grok_home)"
  if [[ "$GLOBAL" -eq 1 ]]; then
    layout="$home"
  else
    layout="${TARGET:-$PWD}/.grok"
  fi
  echo "Uninstalling Kaola-Workflow · grok edition ($FORGE) from → $layout"
  if [[ -d "$layout" && "$SOURCE_TREE" -ef "$layout" ]]; then
    echo "Refusing to uninstall the edition's OWN source tree ($layout). No-op." >&2
    return
  fi
  local f
  if [[ -d "$SOURCE_TREE/agents" && -d "$layout/agents" ]]; then
    for f in "$SOURCE_TREE/agents/"*.md; do
      [[ -f "$f" ]] || continue
      rm -f "$layout/agents/$(basename "$f")"
    done
  fi
  local retired
  for retired in "${RETIRED_AGENTS[@]+"${RETIRED_AGENTS[@]}"}"; do
    [[ -f "$layout/agents/$retired.md" ]] || continue
    rm -f "$layout/agents/$retired.md"
  done
  if [[ -d "$SOURCE_TREE/commands" && -d "$layout/commands" ]]; then
    for f in "$SOURCE_TREE/commands/"*.md; do
      [[ -f "$f" ]] || continue
      rm -f "$layout/commands/$(basename "$f")"
    done
  fi
  for retired in "${RETIRED_COMMANDS[@]+"${RETIRED_COMMANDS[@]}"}"; do
    [[ -f "$layout/commands/$retired.md" ]] || continue
    rm -f "$layout/commands/$retired.md"
  done
  if [[ -d "$layout/hooks" ]]; then
    remove_retired_compact_hook_file "$layout/hooks/hooks.json"
    local hook
    for hook in "$SOURCE_TREE/hooks/"*.sh; do
      [[ -f "$hook" ]] || continue
      rm -f "$layout/hooks/$(basename "$hook")"
    done
  fi
  rm -f "$layout/rules/kaola-workflow-compact-recovery.md"
  rmdir "$layout/agents" 2>/dev/null || true
  rmdir "$layout/commands" 2>/dev/null || true
  rmdir "$layout/hooks" 2>/dev/null || true
  rmdir "$layout/rules" 2>/dev/null || true
  if [[ "$GLOBAL" -ne 1 ]]; then rmdir "$layout" 2>/dev/null || true; fi
  echo "Removed deployed agents + commands."
  local scripts_dir="$home/kaola-workflow/scripts"
  local hooks_dir="$home/kaola-workflow/hooks"
  local prompts_dir="$home/kaola-workflow/prompts"
  local manifest="$SCRIPT_DIR/scripts/kaola-workflow-install-manifest.js"
  if [[ -f "$manifest" && -d "$scripts_dir" ]]; then
    local name
    while IFS= read -r name || [[ -n "$name" ]]; do
      [[ -n "$name" ]] || continue
      if ! is_plain_basename "$name"; then
        echo "warning: ignoring support-script manifest entry that is not a plain file name: $name" >&2
        continue
      fi
      rm -f "$scripts_dir/$name"
    done < <(node "$manifest" --forge="$FORGE" --scripts 2>/dev/null)
  fi
  remove_retired_support_scripts "$scripts_dir"
  if [[ -d "$hooks_dir" ]]; then
    local hook
    for hook in "$SOURCE_TREE/hooks/"*.sh; do
      [[ -f "$hook" ]] || continue
      rm -f "$hooks_dir/$(basename "$hook")"
    done
    for retired in "${RETIRED_HOOKS[@]+"${RETIRED_HOOKS[@]}"}"; do
      [[ -f "$hooks_dir/$retired" ]] || continue
      rm -f "$hooks_dir/$retired"
    done
  fi
  if [[ "$GLOBAL" -eq 1 ]]; then remove_retired_compact_hook_file "$home/hooks/kaola-workflow-hooks.json"; fi
  remove_retired_compact_prompt_file "$prompts_dir/kaola-workflow-compact-recovery.md"
  rmdir "$scripts_dir" 2>/dev/null || true
  rmdir "$hooks_dir" 2>/dev/null || true
  rmdir "$prompts_dir" 2>/dev/null || true
  rmdir "$home/kaola-workflow" 2>/dev/null || true
  echo "Removed deployed support scripts + hook scripts + retired compact artifacts."
  echo "Uninstall complete. A fresh ./install-grok.sh now deploys the workflow edition."
}

confirm_install() {
  if [[ "$YES" -eq 1 ]]; then return 0; fi
  if [[ ! -t 0 ]]; then return 0; fi
  cat <<EOF
About to install the Kaola-Workflow grok edition:
  agents + commands   → $LAYOUT_DEST
  support scripts     → $(grok_home)/kaola-workflow/scripts
  recovery Rule       → $([[ "$GLOBAL" -eq 1 ]] && printf '%s' "$(grok_home)/rules" || printf '%s' "$LAYOUT_DEST/rules")
  hook scripts        → $(grok_home)/kaola-workflow/hooks
  compact hook        → none (Grok passive hook stdout is ignored)
EOF
  local reply=""
  read -r -p "Proceed? [Y/n] " reply || reply="n"
  case "$reply" in
    n|N|no|No|NO) echo "Aborted."; exit 0 ;;
  esac
}

if [[ "$UNINSTALL" -eq 1 ]]; then
  uninstall_edition
  exit 0
fi

if [[ "$GLOBAL" -eq 1 ]]; then
  DEST_ROOT="$(grok_home)"
  LAYOUT_DEST="$DEST_ROOT"
  echo "Deploying globally ($FORGE) → $DEST_ROOT"
else
  DEST_ROOT="${TARGET:-$PWD}"
  LAYOUT_DEST="$DEST_ROOT/.grok"
  echo "Deploying into project ($FORGE) → $DEST_ROOT"
fi

confirm_install
copy_agents "$LAYOUT_DEST/agents"
copy_commands "$LAYOUT_DEST/commands"
install_support_scripts
install_recovery_rule

echo ""
echo "Next: open the project in Grok CLI and run a workflow command, e.g.:"
echo "  /workflow-init"
