#!/usr/bin/env bash
# install-droid.sh — deploy the Kaola-Workflow Droid CLI edition.
#
# Droid is a coding-agent RUNTIME, not a git forge. It is delivered the Droid-native
# way: skills under ~/.agents/skills/ — Droid's documented personal-compatibility root,
# shared with other tools — plus a managed machine-global AGENTS.md carrier at
# ~/.factory/AGENTS.md. This runtime installs no Kaola role profiles and NO hooks by
# design (the adapter records a measured capability; Droid's hook surface exists but this
# edition deliberately writes no hooks.json, no settings.json, no custom droids, and no
# MCP servers). The always-loaded carrier is the compact recovery path, exactly like the
# other native_only managed_region runtimes.
#
# Skills moved out of ~/.factory/skills (#1112) into the shared ~/.agents/skills root, which
# other runtimes that read ~/.agents/skills (dsh documents it) discover too — so the rendered
# skills are runtime-neutral: no Droid-home script paths, no --runtime flag, no Droid-only
# dispatch prose. Droid still reads ~/.factory/skills — the former Kaola-Workflow install
# root, still a supported Droid personal root — and a same-name Skill in both user roots is a
# duplicate (the owner observed Droid flag same-name pairs across the two roots; its docs call
# duplicate names within one source bucket invalid configuration), so install migrates
# ownership-proven copies out of the former root (kaola-workflow-droid-skills.js
# retire-legacy) and REFUSES on a same-name entry it cannot prove is ours —
# foreign, owner-edited, or not a plain one-file SKILL.md dir. The refusal is a preflight
# that exits before ANY write: no skills, no support scripts, no former-root sweep, no
# carrier.
#
# FORGE: --forge=github|gitlab|gitea selects which forge's workflow prose and
# support scripts to deploy (default github). The forge variants are GENERATED by
# sync-droid-edition.js from the same routing surfaces the other editions ship.
#
# Usage:
#   ./install-droid.sh                         # global install (~/.agents/skills + carrier)
#   ./install-droid.sh --global                # same as above
#   ./install-droid.sh --project[=DIR]         # project skills under DIR/.factory
#   ./install-droid.sh --check                 # verify installed artifacts
#   ./install-droid.sh --uninstall             # remove only Kaola-deployed artifacts
#   ./install-droid.sh --forge=gitlab          # deploy GitLab-shaped workflow prose
#
# Global layout:
#   ~/.agents/skills/<name>/SKILL.md   (shared personal-compatibility root; every
#                                      collision is preflighted against an ownership
#                                      record before anything is written)
#   ~/.factory/AGENTS.md   (managed global contract, via kaola-workflow-global-contract.js —
#                           per-target: --runtime droid installs/checks ONLY this runtime's own carrier,
#                           as the LAST install step; no other runtime's home is written)
#   ~/.agents/kaola-workflow/scripts  (support scripts; manifest-named copies under the former
#                                      $DROID_HOME/kaola-workflow/scripts are retired)
#   ~/.factory/kaola-workflow/agents-skills.record  (ownership record: name\tsha256)
#
# Migration: ownership-proven Kaola copies under ~/.factory/skills are retired on
# install (proven by the record, the staged render, or the frozen catalog of released
# renders); anything else with a Kaola skill name is preserved and reported, and the
# install exits non-zero so the duplicate cannot reach Droid. A same-name NON-Kaola skill
# present in both ~/.factory/skills and ~/.agents/skills is only reported as an advisory
# note — Kaola never touches another tool's copy.
#
# DROID_HOME relocates the Droid config home (carrier, ownership record, former-root sweep)
# for hermetic tests only; Droid discovers skills and the personal AGENTS.md carrier from the
# Droid config home (~/.factory by default). Skills and support scripts live under $HOME.
#
# Project layout:
#   <DIR>/.factory/skills/<name>/SKILL.md
#   plus the global recovery carrier above in ~/.factory.
#
# Uninstall: --uninstall removes ONLY Kaola-deployed artifacts — globally, the skills
# whose installed bytes the ownership record (or the staged render) proves ours
# (never a blind rm of the shared ~/.agents/skills root) plus any ownership-proven
# copies left in the former ~/.factory/skills root; the support scripts by manifest
# name (and any manifest-named leftovers under the former $DROID_HOME scripts dir).
# A global-scope uninstall (the default) also strips this runtime's OWN managed
# region in ~/.factory/AGENTS.md through its own per-target record
# (kaola-workflow-global-contract.js uninstall --runtime droid); an owner-edited carrier
# is refused and left in place. A --project uninstall leaves the machine-global carrier
# alone.

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
FORGE="github"
GLOBAL=1
TARGET=""
CHECK=0
UNINSTALL=0
YES=0

usage() {
  cat <<'EOF'
Usage: ./install-droid.sh [--global] [--project[=DIR]] [--forge=github|gitlab|gitea] [--check] [--uninstall] [-y|--yes]
  --global          install global skills into ~/.agents/skills (default), migrating
                    ownership-proven copies out of the former ~/.factory/skills root
  --project[=DIR]   install project skills into DIR/.factory (default: CWD)
  --forge F         github (default), gitlab, or gitea
  --check           verify installed artifacts without mutating
  --uninstall       remove only Kaola-deployed skills, support scripts, and (global scope)
                    this runtime's own global-contract carrier, then exit
  -y, --yes         non-interactive (ignored; accepted for install-all compatibility)
  -h, --help        show this help

Global Skills live in ~/.agents/skills/<name>/SKILL.md — Droid's documented
personal-compatibility root, shared with other tools and read by other runtimes that
discover ~/.agents/skills (dsh documents it), so the rendered skills are runtime-neutral.
A same-name entry that is not a proven Kaola-Workflow copy (foreign, owner-edited, or not a
plain one-file SKILL.md dir) is refused by a preflight before anything is written — no
skills, support scripts, former-root sweep, or carrier. Ownership is proven by
~/.factory/kaola-workflow/agents-skills.record, by the staged render, or by the frozen
catalog of released renders. Proven copies under the former ~/.factory/skills root (still a
supported Droid personal root) are removed — the owner observed Droid flag same-name pairs
across the two roots; anything else is preserved and reported, and a non-Kaola name present
in both roots is only an advisory note, never removed. Support scripts live in
~/.agents/kaola-workflow/scripts; manifest-named leftovers under the former
$DROID_HOME/kaola-workflow/scripts are retired on install and uninstall. --check reports
each deployed skill as missing, stale (drifted but provably a Kaola copy), or conflict
(not provably ours — install will refuse it).

Uninstall removes ONLY Kaola-deployed artifacts from the resolved scope: the deployed
skills (ownership-proven — never a blind rm of a dir), and the support
scripts (by manifest name). A global-scope uninstall also strips this runtime's own
managed region in ~/.factory/AGENTS.md through its own per-target global-contract record
(an owner-edited carrier is refused and left in place); --project leaves that carrier.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --forge=*) FORGE="${1#*=}"; shift ;;
    --forge) FORGE="${2:?--forge requires github, gitlab, or gitea}"; shift 2 ;;
    --global) GLOBAL=1; shift ;;
    --project) GLOBAL=0; TARGET="$PWD"; shift ;;
    --project=*) GLOBAL=0; TARGET="${1#*=}"; shift ;;
    --target) GLOBAL=0; TARGET="${2:?--target requires a directory}"; shift 2 ;;
    --check) CHECK=1; shift ;;
    --uninstall) UNINSTALL=1; shift ;;
    -y|--yes) YES=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

HOME_ROOT="${DROID_HOME:-${HOME:?}/.factory}"

STAGE="$(mktemp -d "${TMPDIR:-/tmp}/kw-droid-install.XXXXXX")"
cleanup() { rm -rf "$STAGE"; }
trap cleanup EXIT

echo "Kaola-Workflow · droid edition ($FORGE) — staging generated artifacts..."
node "$SCRIPT_DIR/scripts/sync-droid-edition.js" --forge="$FORGE" --tree-root="$STAGE" --write

FORGE_HELPER="$SCRIPT_DIR/scripts/runtime-edition-forge.js"
if [[ ! -f "$FORGE_HELPER" ]]; then
  echo "Install error: forge layout helper missing: $FORGE_HELPER" >&2
  exit 1
fi
if ! FORGE_SUFFIX="$(node "$FORGE_HELPER" --forge="$FORGE" --out-suffix)"; then
  echo "Install error: unknown forge \"$FORGE\" (expected github, gitlab, or gitea)" >&2
  exit 2
fi
if ! FORGE_SCRIPTS_DIR="$(node "$FORGE_HELPER" --forge="$FORGE" --scripts-dir)"; then
  echo "Install error: cannot resolve the support-script dir for forge $FORGE" >&2
  exit 1
fi

SOURCE_TREE="$STAGE/.factory$FORGE_SUFFIX"
# Support scripts moved to the runtime-neutral shared root (#1112): the rendered skills are
# discovered by every runtime that reads ~/.agents/skills, and their resolver resolves
# $HOME/.agents/kaola-workflow/scripts — a Droid-home path would break for them.
SUPPORT_DEST="${HOME:?}/.agents/kaola-workflow/scripts"
LEGACY_SUPPORT_DIR="$HOME_ROOT/kaola-workflow/scripts"
DROID_SKILLS_JS="$SCRIPT_DIR/scripts/kaola-workflow-droid-skills.js"
SUPPORT_MANIFEST=()
while IFS= read -r line; do [[ -n "$line" ]] && SUPPORT_MANIFEST+=("$line"); done \
  < <(node "$SCRIPT_DIR/scripts/kaola-workflow-install-manifest.js" --forge="$FORGE" --scripts)

# Global Skills live in the documented personal-compatibility root ~/.agents/skills
# (#1112), shared with other tools and other runtimes; the former personal root
# ~/.factory/skills (still a supported Droid personal root) is swept of ownership-proven
# copies so Droid never sees same-name duplicates. The ownership record stays under the
# Droid home (HOME_ROOT); the support scripts live under the shared ~/.agents root.
LEGACY_SKILLS_DIR="$HOME_ROOT/skills"
SKILLS_RECORD="$HOME_ROOT/kaola-workflow/agents-skills.record"
if [[ "$GLOBAL" == 1 ]]; then
  SKILLS_DEST="${HOME:?}/.agents/skills"
else
  PROJECT_DIR="${TARGET:-$PWD}"
  # Project scope keeps the documented primary Project root .factory/skills.
  SKILLS_DEST="$PROJECT_DIR/.factory/skills"
fi

# Install or check the managed global AGENTS.md carrier through the per-target
# global-contract CLI (#1087): --runtime droid selects ONLY the droid-local target, so
# another runtime's carrier conflict or drift can never fail this installer.
# Both modes report the droid-local target instead of discarding the CLI exit code.
global_contract() {
  local mode="$1" output rc=0
  output="$(node "$SCRIPT_DIR/scripts/kaola-workflow-global-contract.js" "$mode" --runtime droid --json 2>&1)" || rc=$?
  node - "$mode" "$rc" "$HOME_ROOT/AGENTS.md" "$output" <<'NODE'
const [mode, rcText, carrierPath, output] = process.argv.slice(2);
const rc = Number(rcText);
let doc = null;
try { doc = JSON.parse(output); } catch (_) { /* non-JSON output is reported verbatim below */ }
const target = doc && Array.isArray(doc.targets) ? doc.targets.find(t => t.id === 'droid-local') : null;
const overall = doc && doc.status ? doc.status : 'UNKNOWN';
const droid = target ? target.status : 'ABSENT';
if (rc === 0) process.exit(0);
console.error(`${mode}: droid global contract ${overall} (exit ${rc}); droid-local carrier ${droid} at ${carrierPath}`);
if (!doc) console.error(output);
else if (doc.error) console.error(`${mode}: ${doc.error}`);
if (mode === 'check') console.error('check: run ./install-droid.sh to refresh the droid global contract carrier');
process.exit(1);
NODE
}

install_global_carrier() { global_contract install; }
check_global_carrier() { global_contract check; }

# Install the forge-selected support scripts into the shared runtime-neutral helper root.
install_support_scripts() {
  mkdir -p "$SUPPORT_DEST"
  local src name
  for name in "${SUPPORT_MANIFEST[@]}"; do
    src="$FORGE_SCRIPTS_DIR/$name"
    [[ -f "$src" ]] || { echo "Install error: support script missing: $src" >&2; exit 1; }
    cp "$src" "$SUPPORT_DEST/$name"
  done
}

# Global scope only: remove manifest-named leftovers from the former support-script dir
# ($DROID_HOME/kaola-workflow/scripts), exactly the manifest names — never a blind rm — then
# drop the dir when it is empty.
retire_legacy_support_scripts() {
  [[ "$GLOBAL" == 1 ]] || return 0
  [[ -d "$LEGACY_SUPPORT_DIR" ]] || return 0
  local name
  for name in "${SUPPORT_MANIFEST[@]}"; do
    if [[ -f "$LEGACY_SUPPORT_DIR/$name" ]]; then
      rm -f "$LEGACY_SUPPORT_DIR/$name"
      echo "Removed former support script: $LEGACY_SUPPORT_DIR/$name"
    fi
  done
  rmdir "$LEGACY_SUPPORT_DIR" 2>/dev/null || true
  rmdir "$HOME_ROOT/kaola-workflow" 2>/dev/null || true
}

# Verify installed support scripts match the canonical source.
check_support_scripts() {
  local bad=0 src name
  if [[ ! -d "$SUPPORT_DEST" ]]; then
    echo "check: missing $SUPPORT_DEST" >&2; return 1
  fi
  for name in "${SUPPORT_MANIFEST[@]}"; do
    src="$FORGE_SCRIPTS_DIR/$name"
    if [[ ! -f "$SUPPORT_DEST/$name" ]]; then
      echo "check: missing support script $name" >&2; bad=1
    elif ! diff -q "$src" "$SUPPORT_DEST/$name" >/dev/null 2>&1; then
      echo "check: support script $name drifted from canonical" >&2; bad=1
    fi
  done
  return "$bad"
}

# Verify each staged skill against its destination by name — never a whole-dir diff:
# the global root ~/.agents/skills is shared with other tools' skills.
check_artifacts() {
  local record_args=()
  if [[ "$GLOBAL" == 1 ]]; then record_args=(--record "$SKILLS_RECORD"); fi
  node "$DROID_SKILLS_JS" check --src "$SOURCE_TREE/skills" --dest "$SKILLS_DEST" "${record_args[@]}"
}

# Report (never mutate) ownership-proven duplicate copies still in the former
# ~/.factory/skills root, plus advisory notes for same-name non-Kaola pairs across the two
# roots. Global scope only; a project install has no legacy root.
check_legacy_skills() {
  [[ "$GLOBAL" == 1 ]] || return 0
  node "$DROID_SKILLS_JS" retire-legacy --dir "$LEGACY_SKILLS_DIR" \
    --src "$SOURCE_TREE/skills" --shared "$SKILLS_DEST" --check
}

# #1087 (#1086 F3): a global-scope uninstall strips this runtime's OWN global-contract carrier
# through its own per-target record and releases that record's shared-block reference. A carrier
# the owner edited since install is refused (OWNER_CONFLICT) and left in place; no other runtime's
# carrier or record is read for removal. A project-scope uninstall leaves the machine-global carrier.
uninstall_global_carrier() {
  [[ "$GLOBAL" -eq 1 ]] || return 0
  local output rc=0 status
  output="$(node "$SCRIPT_DIR/scripts/kaola-workflow-global-contract.js" uninstall --runtime droid --json 2>&1)" || rc=$?
  status="$(node -e 'try { console.log(JSON.parse(process.argv[1]).status || "UNKNOWN"); } catch (_) { console.log("UNKNOWN"); }' "$output")"
  if [[ "$rc" -eq 0 ]]; then
    echo "droid global contract carrier: $status"
  else
    echo "warning: droid global contract carrier left in place ($status, exit $rc)" >&2
    printf '%s\n' "$output" >&2
  fi
}

# #1087 (#1086 F2): release this runtime's reference on the shared ~/.config/kaola-workflow block.
# The registry keeps the block while any other runtime (or another scope of this one) holds a
# reference and removes it only when this was the last one.
release_shared_config_ref() {
  local scope_args=(--scope global) out
  if [[ "$GLOBAL" -ne 1 ]]; then scope_args=(--scope project --target "${TARGET:-$PWD}"); fi
  if out="$(node "$SCRIPT_DIR/scripts/kaola-workflow-shared-refs.js" deregister \
      --runtime droid "${scope_args[@]}")"; then
    echo "Released shared config reference (droid): $out"
  else
    echo "warning: shared config reference not released ($out); ~/.config/kaola-workflow left in place." >&2
  fi
}

# Remove only Kaola-deployed artifacts: globally the ownership-proven skills (helper);
# for a project, rendered skill dirs by source-tree name (never a blind rm of the skills dir) and support scripts by manifest name.
uninstall_edition() {
  local bad=0 name
  if [[ "$GLOBAL" == 1 ]]; then
    # Ownership-proven removal from the shared ~/.agents/skills root (the record or the
    # staged render must prove each copy ours), then the former ~/.factory/skills root.
    # A preserved entry never aborts the rest of the uninstall — it is reported.
    node "$DROID_SKILLS_JS" uninstall --src "$SOURCE_TREE/skills" \
      --dest "$SKILLS_DEST" --record "$SKILLS_RECORD" || bad=1
    if ! node "$DROID_SKILLS_JS" retire-legacy --dir "$LEGACY_SKILLS_DIR" \
        --src "$SOURCE_TREE/skills" --shared "$SKILLS_DEST"; then
      echo "warning: entries preserved under $LEGACY_SKILLS_DIR (see above)" >&2
    fi
    retire_legacy_support_scripts
  elif [[ -d "$SKILLS_DEST" ]]; then
    # Remove rendered skill dirs by source-tree directory name — never a blind rm of a dir.
    for name in $(cd "$SOURCE_TREE/skills" 2>/dev/null && printf '%s\n' */ 2>/dev/null | sed 's#/##' || true); do
      [[ -n "$name" ]] || continue
      if [[ -d "$SKILLS_DEST/$name" ]]; then
        rm -rf "$SKILLS_DEST/$name"
        echo "Removed skill: $SKILLS_DEST/$name"
      fi
    done
    # Remove the skills dir itself only if Kaola artifacts left nothing else behind.
    rmdir "$SKILLS_DEST" 2>/dev/null || true
  fi
  if [[ -d "$SUPPORT_DEST" ]]; then
    for name in "${SUPPORT_MANIFEST[@]}"; do
      if [[ -f "$SUPPORT_DEST/$name" ]]; then
        rm -f "$SUPPORT_DEST/$name"
        echo "Removed support script: $SUPPORT_DEST/$name"
      fi
    done
    rmdir "$SUPPORT_DEST" 2>/dev/null || true
    # Zero-residue: drop the emptied kaola-workflow parent dir too — never ~/.agents itself.
    rmdir "$(dirname "$SUPPORT_DEST")" 2>/dev/null || true
  fi
  uninstall_global_carrier
  release_shared_config_ref
  echo "Droid edition uninstalled."
  return "$bad"
}

if [[ "$CHECK" == 1 ]]; then
  # Report EVERY failure, not just the first: carrier, support scripts, the skills in
  # the live root, and any ownership-proven duplicates still in the former root.
  check_bad=0
  check_global_carrier || check_bad=1
  check_support_scripts || check_bad=1
  check_artifacts || check_bad=1
  check_legacy_skills || check_bad=1
  [[ "$check_bad" -eq 0 ]] || exit 1
  echo "Droid edition check passed."
  exit 0
fi

if [[ "$UNINSTALL" == 1 ]]; then
  uninstall_edition
  exit 0
fi

# Hard refusal before ANY write (global scope only): a foreign or owner-edited same-name
# entry in ~/.agents/skills aborts here under set -e — before support scripts, skills,
# the former-root sweep, or the carrier are touched. Everything before this point only
# stages into mktemp and reads.
if [[ "$GLOBAL" == 1 ]]; then
  node "$DROID_SKILLS_JS" preflight --src "$SOURCE_TREE/skills" \
    --dest "$SKILLS_DEST" --record "$SKILLS_RECORD"
fi

install_support_scripts

retire_rc=0
if [[ "$GLOBAL" == 1 ]]; then
  # The batch was preflighted above; install keeps the same atomic conflict guard as a
  # backstop and still writes nothing when an entry conflicts.
  node "$DROID_SKILLS_JS" install --src "$SOURCE_TREE/skills" \
    --dest "$SKILLS_DEST" --record "$SKILLS_RECORD"
  # Migrate ownership-proven copies out of the former ~/.factory/skills root (Droid
  # reads both user roots; a same-name pair is a duplicate). A preserved
  # entry is remembered and fails the install AFTER the carrier step below.
  node "$DROID_SKILLS_JS" retire-legacy --dir "$LEGACY_SKILLS_DIR" \
    --src "$SOURCE_TREE/skills" --shared "$SKILLS_DEST" || retire_rc=$?
  # Only once no former-root Kaola copy (which still resolves the former script dir)
  # is left behind are the former support scripts retired.
  [[ "$retire_rc" -ne 0 ]] || retire_legacy_support_scripts
else
  mkdir -p "$SKILLS_DEST"
  if [[ -d "$SOURCE_TREE/skills" ]]; then
    for src in "$SOURCE_TREE/skills/"*; do
      [[ -d "$src" ]] || continue
      name="$(basename "$src")"
      mkdir -p "$SKILLS_DEST/$name"
      cp "$src/SKILL.md" "$SKILLS_DEST/$name/SKILL.md"
    done
  fi
fi

# Last step (#1087): this runtime's own global-contract carrier.
install_global_carrier

if [[ "$retire_rc" -ne 0 ]]; then
  echo "Installed Droid edition ($FORGE), but entries under $LEGACY_SKILLS_DIR were preserved — Droid reads both ~/.factory/skills and ~/.agents/skills, and the owner observed Droid flag same-name pairs across them; move them aside and rerun." >&2
  exit 1
fi

echo "Installed Droid edition ($FORGE) — skills: $SKILLS_DEST, support scripts: $SUPPORT_DEST, global carrier: $HOME_ROOT/AGENTS.md"
