#!/usr/bin/env bash
# install-kimi.sh — deploy the Kaola-Workflow kimi edition into a project (or globally).
#
# Additive standalone installer (does NOT modify install.sh, install-opencode.sh, or the
# claude/codex/gitlab/gitea/opencode editions). Kimi Code is a runtime (like opencode), not
# a git forge, so it is delivered the kimi-native way: SKILL.md skills under a skills/ dir +
# a managed [[hooks]] block in the kimi config.toml.
#
# FORGE: --forge=github|gitlab|gitea selects which forge's workflow prose and support scripts
# to deploy (default github). The runtime is still not a forge — this installer remains
# standalone and additive — but the workflow PROSE is forge-shaped (gh vs glab vs tea, PR vs
# MR, per-forge script basenames), so a GitLab/Gitea project must not be handed GitHub-shaped
# skills. The forge variants are GENERATED by sync-kimi-edition.js from the same routing
# surfaces the other editions ship; github renders .kimi/, a forge renders .kimi-<forge>/.
#
# Usage:
#   ./install-kimi.sh                         # deploy into the current directory
#   ./install-kimi.sh --target /path/to/repo  # deploy into a specific project
#   ./install-kimi.sh --forge=gitlab          # deploy the GitLab-shaped edition
#   ./install-kimi.sh --global                # deploy skills to ${KIMI_CODE_HOME:-~/.kimi-code}/skills
#   ./install-kimi.sh --regenerate            # refresh the generated tree from canonical here
#
# COMMAND SKILLS: the install deploys the workflow command skills (kaola-workflow-finalize,
# workflow-init, workflow-next) plus all 14 kaola-role-* skills into the skills/ dir. The
# generated .kimi/ tree is produced by sync-kimi-edition.js from the canonical sources.
#
# DEPLOY LAYOUT (scope-dependent):
#   - PROJECT (--target/$PWD): skills land under <project>/.kimi-code/skills/<name>/SKILL.md.
#   - GLOBAL (--global): skills land DIRECTLY under ${KIMI_CODE_HOME:-$HOME/.kimi-code}/skills/.
#   - Support scripts + hook scripts ALWAYS land under the kimi home (user-level, shared by
#     every project): ${KIMI_CODE_HOME:-$HOME/.kimi-code}/kaola-workflow/{scripts,hooks}.
#   - The hooks fragment (.kimi/hooks/kimi-hooks.toml, __KIMI_HOME__ substituted with the
#     resolved kimi home) is merged into ${KIMI_CODE_HOME:-$HOME/.kimi-code}/config.toml as a
#     MANAGED block between the "# >>> kaola-workflow kimi hooks" /
#     "# <<< kaola-workflow kimi hooks" markers. Re-install strips + re-appends the block:
#     idempotent, exactly one managed block. Post-merge the config is validated with
#     `kimi doctor config` when a kimi binary is on PATH; a validation failure restores the
#     pre-merge config and aborts non-zero. The hooks config is global regardless of install
#     scope — it is merged on every install unless --no-scripts.
#
# REINSTALL IS SELF-HEALING, AND NOTHING WIDER: copy_skills removes each skill dir it is about to
# re-copy (immediately before re-copying it) plus the RETIRED_ROLE_SKILLS this edition no longer
# ships, so a reinstall converges to the workflow skill set without destroying a deployed skill it
# has nothing to put back. --uninstall removes the full deployed surface; see uninstall_edition.

set -euo pipefail

# The temp base every mktemp below writes under. `${TMPDIR:-/tmp}` guards an EMPTY
# TMPDIR and NOT a relative one, and a bare `mktemp` reads TMPDIR the same way — on
# GNU coreutils a relative TMPDIR resolves against the invoking directory (the
# checkout, for a local install), so the temp files land beside tracked files.
# Same guard as install-all.sh: absolute or nothing.
KW_TMPDIR="${TMPDIR:-/tmp}"
case "$KW_TMPDIR" in
  /*) ;;
  *) KW_TMPDIR="/tmp" ;;
esac

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
TARGET=""
GLOBAL=0
REGENERATE=0
UNINSTALL=0
YES=0
NO_SCRIPTS=0
FORGE="github"

usage() {
  cat <<'EOF'
Usage: ./install-kimi.sh [--target DIR] [--forge=github|gitlab|gitea] [--global]
                         [--regenerate] [--uninstall] [--no-scripts] [--yes]
  --target DIR     deploy skills into DIR/.kimi-code/skills (default: current directory)
  --forge F        github (default), gitlab, or gitea — which forge's workflow prose
                   and support scripts to deploy
  --global         deploy skills into ${KIMI_CODE_HOME:-~/.kimi-code}/skills (all projects)
  --regenerate     refresh the in-repo .kimi/ tree from canonical, then exit
  --uninstall      remove the kaola-deployed kimi edition from the resolved scope
                   (honors --target/--global), then exit (see UNINSTALL below)
  --no-scripts     skip support scripts, hook scripts, and the config.toml hooks merge
  --yes            non-interactive (skip the confirmation prompt)

SUPPORT SCRIPTS + HOOKS: workflow skills resolve support scripts via
${KIMI_CODE_HOME:-$HOME/.kimi-code}/kaola-workflow/scripts (the list comes from
scripts/kaola-workflow-install-manifest.js); the 1 kimi hook script lands in
${KIMI_CODE_HOME:-$HOME/.kimi-code}/kaola-workflow/hooks and are wired into
${KIMI_CODE_HOME:-$HOME/.kimi-code}/config.toml as a managed [[hooks]] block (idempotent;
validated with `kimi doctor config` when a kimi binary is on PATH).

UNINSTALL: --uninstall removes ONLY kaola-deployed artifacts from the resolved scope
(project DEST_ROOT via --target/$PWD, or --global ${KIMI_CODE_HOME:-$HOME/.kimi-code}):
the deployed skills (by source-tree directory name — never a blind rm of a dir), the
support scripts + hook scripts under the kimi home, and the managed hooks block in config.toml
(the rest of the file is preserved). The SHARED ~/.config/kaola-workflow/config.json is
kept for any co-installed Claude/Codex/opencode edition. A
subsequent bare install then deploys the workflow edition.
EOF
}

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    --target) TARGET="${2:?--target requires a directory}"; shift 2 ;;
    --forge=*) FORGE="${1#--forge=}"; shift ;;
    --forge) FORGE="${2:?--forge requires github, gitlab, or gitea}"; shift 2 ;;
    --global) GLOBAL=1; shift ;;
    --regenerate) REGENERATE=1; shift ;;
    --uninstall) UNINSTALL=1; shift ;;
    --no-scripts) NO_SCRIPTS=1; shift ;;
    -y|--yes) YES=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

# The resolved kimi home honors $KIMI_CODE_HOME (the same override the kimi CLI itself uses).
kimi_home() { printf '%s\n' "${KIMI_CODE_HOME:-$HOME/.kimi-code}"; }

# Resolve the forge layout from the ONE source the generators use (scripts/runtime-edition-forge.js),
# so this installer never restates a forge dir or a per-forge script name. An unknown forge fails
# here, loudly, before anything is written.
FORGE_HELPER="$SCRIPT_DIR/scripts/runtime-edition-forge.js"
if [[ ! -f "$FORGE_HELPER" ]]; then
  echo "Install error: forge layout helper missing: $FORGE_HELPER" >&2
  exit 1
fi
if ! FORGE_SUFFIX="$(node "$FORGE_HELPER" --forge="$FORGE" --out-suffix)"; then
  echo "Install error: unknown forge \"$FORGE\" (expected github, gitlab, or gitea)" >&2
  exit 2
fi
if ! FORGE_SCRIPTS_DIR="$(node "$FORGE_HELPER" --forge="$FORGE" --scripts-dir)"; then
  echo "Install error: cannot resolve the support-script dir for forge $FORGE" >&2
  exit 1
fi
# The generated tree this forge deploys FROM: .kimi for github, .kimi-<forge> otherwise.
# WHERE that tree lives is the generator's answer, never this script's guess: it is not always the
# directory this installer sits in (a linked worktree's tree belongs to the main checkout), and a
# deploy that copies from a path the generator never writes installs nothing.
if ! TREE_ROOT="$(node "$SCRIPT_DIR/scripts/sync-kimi-edition.js" --print-tree-root)"; then
  echo "Install error: cannot resolve where the generated kimi tree lands" >&2
  exit 1
fi
SOURCE_TREE="$TREE_ROOT/.kimi$FORGE_SUFFIX"

# Always ensure the in-repo generated tree is fresh before copying from it (install only — an
# uninstall removes by source-tree name and must not regenerate the repo tree).
if [[ "$UNINSTALL" -ne 1 ]]; then
  echo "Kaola-Workflow · kimi edition ($FORGE) — refreshing generated tree..."
  node "$SCRIPT_DIR/scripts/sync-kimi-edition.js" --forge="$FORGE" --check >/dev/null 2>&1 \
    || node "$SCRIPT_DIR/scripts/sync-kimi-edition.js" --forge="$FORGE" --write >/dev/null
fi

if [[ "$REGENERATE" -eq 1 ]]; then
  echo "Regenerated $SOURCE_TREE from canonical. Done."
  exit 0
fi

# Skills this edition deployed on a PREVIOUS release and no longer generates. BOTH paths read
# this list: uninstall removes by source-tree name, and the install sweep is exactly the deploy
# set PLUS these names (#973 — a namespace-wide install prune destroys a deployed skill whenever
# the source renders fewer than the destination holds, which is silent and reported as success).
# So this is where "retired on purpose" is written down, and a name that is not here is treated
# as a skill this install simply has nothing to put back.
# Bounded by what this edition actually shipped: the kimi edition landed 2026-07-17, so it carries
# the fast/phase surfaces retired two days later plus the three roles and two commands retired
# since, and nothing older (kaola-workflow-auto went before it existed). One skill dir per TOP-LEVEL
# agents/*.md and per commands/*.md deleted since that date — census it from git, not from memory.
RETIRED_ROLE_SKILLS=(
  "kaola-role-issue-scout" "kaola-role-contractor" "kaola-role-workflow-planner"
  "kaola-workflow-adapt" "kaola-workflow-plan-run" "kaola-workflow-fast"
  "kaola-workflow-phase1" "kaola-workflow-phase2" "kaola-workflow-phase3"
  "kaola-workflow-phase4" "kaola-workflow-phase5"
)

# Hook scripts this edition deployed on a PREVIOUS release and no longer generates — the same
# declaration model as RETIRED_ROLE_SKILLS, read by BOTH paths: the hook deploy is a bare copy
# forward and uninstall removes by source-tree name, so a retired hook is invisible to both and
# would live in the kimi home for good. Removal is exactly these names plus what the deploy is
# about to write, never a sweep of the whole hooks dir. Bounded the same way as the skills list:
# the edition shipped pre-commit, write-lane, and the dispatch log before their retirement.
RETIRED_HOOKS=(
  "kaola-workflow-pre-commit.sh" "kaola-workflow-write-lane.sh"
  "kaola-workflow-subagent-dispatch-log.sh"
)

# Support scripts this edition deployed on a PREVIOUS release and no longer deploys — the same
# declaration model as the two lists above, and the same asymmetry the hooks list already closes:
# the INSTALL path converges (it enumerates the destination and drops whatever it did not just
# deploy), so a reinstall heals a stranded script, while uninstall removes strictly by the CURRENT
# manifest and a retired name survives it.
#
# Censused from the SUPPORT_SCRIPTS history in scripts/kaola-workflow-install-manifest.js
# (`git log -L` over that array), cross-checked against `git log --diff-filter=D` over scripts/ —
# never from the installer's own arrays, since a list validated against itself cannot show an
# omission. Bounded by what this edition shipped: kimi landed 2026-07-17 deploying support scripts
# from its first release, so it carries the three fast/full/phase4 advancers retired two days later
# and the eight retired with the DAG executor on 07-31 — and NOT autopilot (retired 2026-06-26) or
# parallel-batch (07-02), both of which were gone before this edition existed. A namespace sweep of
# the scripts dir is deliberately NOT used: it would reintroduce the defect #973 removed.
RETIRED_SUPPORT_SCRIPTS=(
  "kaola-workflow-fast-advance.js" "kaola-workflow-full-advance.js" "kaola-workflow-phase4-advance.js"
  "kaola-workflow-repair-state.js" "kaola-workflow-plan-validator.js" "kaola-workflow-next-action.js"
  "kaola-workflow-commit-node.js" "kaola-workflow-adaptive-handoff.js" "kaola-workflow-adaptive-node.js"
  "kaola-workflow-replan.js" "kaola-workflow-task-mirror.js"
)

# Remove the retired support scripts from a deployed scripts dir. Each canonical base is removed
# alongside its two forge-port spellings: the manifest renames kaola-workflow-<X> to
# kaola-<forge>-workflow-<X> for gitlab and gitea, so the deployed basename depends on the forge the
# home was installed under — which need not be the forge this uninstall was invoked with. All three
# spellings of a RETIRED name are safe to remove and none of them is a current artifact. Every name
# still goes through is_plain_basename before it becomes a delete path.
remove_retired_support_scripts() {
  local dir="$1"
  [[ -d "$dir" ]] || return 0
  local base name
  for base in "${RETIRED_SUPPORT_SCRIPTS[@]}"; do
    for name in "$base" \
      "${base/#kaola-workflow-/kaola-gitlab-workflow-}" \
      "${base/#kaola-workflow-/kaola-gitea-workflow-}"; do
      is_plain_basename "$name" || continue
      [[ -f "$dir/$name" ]] || continue
      rm -f "$dir/$name"
      echo "Removed retired support script: $dir/$name"
    done
  done
}

# Workflow command-skill set: deployed alongside all kaola-role-* skills. Any OTHER skill fails
# CLOSED (skipped + warned) so a future canonical command cannot silently widen the install.
# Single source of truth for the deploy set (used by copy_skills).
WORKFLOW_COMMANDS=(
  kaola-workflow-finalize workflow-init workflow-next
)
in_array() { local needle="$1"; shift; local x; for x in "$@"; do [[ "$x" == "$needle" ]] && return 0; done; return 1; }

# True when `$1` is a plain file name: non-empty, no path separator, not `.`/`..`, not absolute.
# The install manifest emits plain basenames; anything else must never become a filesystem path.
is_plain_basename() {
  local n="${1-}"
  [[ -n "$n" ]] || return 1
  case "$n" in
    */*|*\\*|.|..) return 1 ;;
  esac
  return 0
}

copy_skills() {
  local skills_dest="$1"   # project → <dest_root>/.kimi-code/skills; global → <kimi_home>/skills
  mkdir -p "$skills_dest"
  # Self-dev guard: deploying the edition into its OWN source tree means the canonical
  # .kimi/skills and the destination are the same directory — skip the (no-op) copy.
  if [[ "$SOURCE_TREE/skills" -ef "$skills_dest" ]]; then
    echo "Self-dev deploy (source $SOURCE_TREE/skills is already the live tree) → copy skipped."
    return
  fi
  # The COMMAND-skill deploy is SELF-HEALING, and it removes exactly two things: the names this
  # edition RETIRED on purpose (RETIRED_ROLE_SKILLS), and each skill dir it is about to WRITE,
  # immediately before writing it. A deployed dir that is neither is one this install has nothing
  # to put back, so it is left alone — a source tree that renders fewer skills than the
  # destination holds must not destroy the difference (#973; the loss was silent and reported as
  # a successful install). The per-name removal is NOT deferrable past that name's own copy:
  # `cp -R src dest` onto an EXISTING dest copies INTO it, leaving the live SKILL.md stale and the
  # new bytes at dest/X/X/SKILL.md, so a reinstall would stop updating skills at all.
  local stale retired
  for retired in "${RETIRED_ROLE_SKILLS[@]}"; do
    stale="$skills_dest/$retired"
    [[ -d "$stale" ]] || continue
    rm -rf "$stale"
  done
  # Re-copy via a fail-CLOSED ALLOWLIST: the workflow command skills + all kaola-role-* skills,
  # anything else skipped.
  local src_dir base skill_count=0 skipped=0
  for src_dir in "$SOURCE_TREE/skills/"*/; do
    [[ -d "$src_dir" ]] || continue
    base="$(basename "$src_dir")"
    if ! in_array "$base" "${WORKFLOW_COMMANDS[@]}"; then
      case "$base" in
        kaola-role-*) : ;;   # role skills: always
        *) echo "warning: skipping unrecognized skill not in the workflow command / role set: $base" >&2
           skipped=$((skipped + 1)); continue ;;
      esac
    fi
    # Replace, never merge — see the `cp -R` note above. Dirs only, so a non-directory entry a
    # user keeps under this name is left for `cp` to fail on rather than silently deleted.
    if [[ -d "$skills_dest/$base" ]]; then rm -rf "$skills_dest/$base"; fi
    cp -R "${src_dir%/}" "$skills_dest/$base"
    skill_count=$((skill_count + 1))
  done
  # Fail CLOSED on a deploy that landed nothing (the same guard install-opencode.sh's copy_tree
  # keeps over its agents). An empty skills dir reported as a successful install is the worst
  # outcome this script has: the user is told the edition is installed and it is not there.
  if [[ "$skill_count" -eq 0 ]]; then
    if [[ "$skipped" -gt 0 ]]; then
      # Say what actually happened: the sources are present and every one of them was rejected.
      echo "Install error: all $skipped skill source(s) in $SOURCE_TREE/skills fall outside the workflow command / role set" >&2
    else
      echo "Install error: no skill sources found in $SOURCE_TREE/skills" >&2
    fi
    exit 1
  fi
  echo "Installed workflow skills → $skills_dest/"
}

# Install the support scripts + hook scripts the workflow skills invoke. Scripts land in
# ${KIMI_CODE_HOME:-$HOME/.kimi-code}/kaola-workflow/scripts (list from the single-source
# install manifest, same as install-opencode.sh); the 1 kimi hook .sh script lands in
# .../kaola-workflow/hooks (chmod 755).
install_support_scripts() {
  if [[ "$NO_SCRIPTS" -eq 1 ]]; then
    echo "Support scripts skipped (--no-scripts)."
    return
  fi
  local home; home="$(kimi_home)"
  local manifest="$SCRIPT_DIR/scripts/kaola-workflow-install-manifest.js"
  [[ -f "$manifest" ]] || { echo "warning: install manifest not found; skipping support scripts." >&2; return; }
  local dest="$home/kaola-workflow/scripts"
  mkdir -p "$dest"
  local name src
  local deployed=()
  while IFS= read -r name || [[ -n "$name" ]]; do
    [[ -n "$name" ]] || continue
    src="$FORGE_SCRIPTS_DIR/$name"
    # The Oracle Kernel is de-duplicated to a single canonical source; a forge tree that
    # does not carry its own copy resolves it from scripts/ (mirrors install.sh).
    [[ -f "$src" ]] || src="$SCRIPT_DIR/scripts/$name"
    if [[ ! -f "$src" ]]; then
      echo "Install error: allowlisted support script missing from source for forge $FORGE: $name" >&2
      exit 1
    fi
    cp "$src" "$dest/$name"
    chmod +x "$dest/$name"
    deployed+=("$name")
  done < <(node "$manifest" --forge="$FORGE" --scripts 2>/dev/null)
  # Copying forward never REMOVES, so a script whose source the tree has since retired lives in
  # the kimi home for good and the deployed set drifts up release by release. Converge the dir on
  # the manifest instead, exactly as install.sh does ("Remove stale support scripts not present
  # in source.").
  #
  # ENUMERATES THE DESTINATION and intersects it against what was just deployed, so a delete path
  # is never CONSTRUCTED from a manifest-supplied name. Scoped to `*.js` — install.sh's scope, not
  # a wider one invented here — so anything else a user keeps alongside survives. A deploy that
  # copied NOTHING (an empty/failed manifest read) sweeps nothing rather than emptying the dir.
  if [[ ${#deployed[@]} -gt 0 ]]; then
    local stale_file stale_name is_current
    for stale_file in "$dest"/*.js; do
      [[ -f "$stale_file" ]] || continue
      stale_name="$(basename "$stale_file")"
      is_current=0
      for name in "${deployed[@]}"; do
        [[ "$name" == "$stale_name" ]] && is_current=1 && break
      done
      if [[ "$is_current" -eq 0 ]]; then
        rm -f "$stale_file"
        echo "Removed stale script: $stale_file"
      fi
    done
  fi
  echo "Installed support scripts → $dest (forge $FORGE)"
  local hooks_dest="$home/kaola-workflow/hooks"
  mkdir -p "$hooks_dest"
  # The copy below only writes forward, so a hook the tree has since retired would survive every
  # reinstall. Remove the retired names first (same self-healing copy_skills gives the skills).
  local retired
  for retired in "${RETIRED_HOOKS[@]}"; do
    [[ -f "$hooks_dest/$retired" ]] || continue
    rm -f "$hooks_dest/$retired"
    echo "Removed retired hook script: $hooks_dest/$retired"
  done
  local hook hook_base
  for hook in "$SOURCE_TREE/hooks/"*.sh; do
    [[ -f "$hook" ]] || continue
    hook_base="$(basename "$hook")"
    cp "$hook" "$hooks_dest/$hook_base"
    chmod 755 "$hooks_dest/$hook_base"
  done
  echo "Installed hook scripts → $hooks_dest"
}

# Merge the generated hooks fragment (.kimi/hooks/kimi-hooks.toml, __KIMI_HOME__ resolved)
# into <kimi_home>/config.toml as a MANAGED block (marker comments included). Idempotent:
# any prior managed block is stripped (markers inclusive) and the fresh fragment appended at
# EOF with exactly one preceding blank line. The hooks config is global — merged on every
# install (project or --global) unless --no-scripts. Post-merge, `kimi doctor config`
# validates the result when a kimi binary is on PATH; a failure restores the pre-merge file
# and aborts non-zero.
merge_hooks_config() {
  if [[ "$NO_SCRIPTS" -eq 1 ]]; then
    echo "Hooks config merge skipped (--no-scripts)."
    return
  fi
  local home cfg fragment backup=""
  home="$(kimi_home)"
  cfg="$home/config.toml"
  fragment="$SOURCE_TREE/hooks/kimi-hooks.toml"
  mkdir -p "$home"
  if [[ -f "$cfg" ]]; then
    # Explicit template, not `mktemp -t kaola-kimi-hooks`: on GNU coreutils a -t template
    # without X's is "too few X's in template", exit 1, and set -euo pipefail turned that
    # into an aborted install for every GNU user with an existing config.toml (macOS mktemp
    # accepts the X-less form, which is how it shipped unnoticed).
    backup="$(mktemp "$KW_TMPDIR/kaola-kimi-hooks.XXXXXX")"
    cp "$cfg" "$backup"
  fi
  KIMI_HOOKS_CFG="$cfg" KIMI_HOOKS_FRAGMENT="$fragment" KIMI_HOME_RESOLVED="$home" node -e '
    const fs = require("fs");
    const cfg = process.env.KIMI_HOOKS_CFG;
    const home = process.env.KIMI_HOME_RESOLVED;
    const START = "# >>> kaola-workflow kimi hooks";
    const END = "# <<< kaola-workflow kimi hooks";
    const frag = fs.readFileSync(process.env.KIMI_HOOKS_FRAGMENT, "utf8")
      .split("__KIMI_HOME__").join(home).replace(/\s+$/, "");
    let body = "";
    if (fs.existsSync(cfg)) body = fs.readFileSync(cfg, "utf8");
    const kept = [];
    let inBlock = false;
    for (const line of body.split("\n")) {
      if (line.trim() === START) { inBlock = true; continue; }
      if (line.trim() === END) { inBlock = false; continue; }
      if (!inBlock) kept.push(line);
    }
    const stripped = kept.join("\n").replace(/\s+$/, "");
    fs.writeFileSync(cfg, (stripped ? stripped + "\n\n" : "") + frag + "\n");
  '
  if command -v kimi >/dev/null 2>&1; then
    local doctor_out
    if ! doctor_out="$(kimi doctor config "$cfg" 2>&1)"; then
      if [[ -n "$backup" ]]; then cp "$backup" "$cfg"; else rm -f "$cfg"; fi
      if [[ -n "$backup" ]]; then rm -f "$backup"; fi
      echo "error: 'kimi doctor config' rejected $cfg after merging the kaola-workflow hooks block:" >&2
      echo "$doctor_out" >&2
      echo "Restored the pre-merge config; aborting. The generated fragment may be stale — check scripts/sync-kimi-edition.js." >&2
      exit 1
    fi
    echo "Validated merged config via 'kimi doctor config'."
  fi
  if [[ -n "$backup" ]]; then rm -f "$backup"; fi
  echo "Merged kaola-workflow hooks → $cfg (managed block; idempotent re-merge)."
}

# Remove the managed hooks block from <kimi_home>/config.toml (uninstall). The rest of the
# file is preserved; if the file held ONLY the managed block it is removed entirely.
strip_hooks_config() {
  local home cfg
  home="$(kimi_home)"
  cfg="$home/config.toml"
  if [[ ! -f "$cfg" ]]; then return 0; fi
  local had_block=0
  if grep -q '^# >>> kaola-workflow kimi hooks' "$cfg"; then had_block=1; fi
  KIMI_HOOKS_CFG="$cfg" node -e '
    const fs = require("fs");
    const cfg = process.env.KIMI_HOOKS_CFG;
    const START = "# >>> kaola-workflow kimi hooks";
    const END = "# <<< kaola-workflow kimi hooks";
    const body = fs.readFileSync(cfg, "utf8");
    const kept = [];
    let inBlock = false;
    for (const line of body.split("\n")) {
      if (line.trim() === START) { inBlock = true; continue; }
      if (line.trim() === END) { inBlock = false; continue; }
      if (!inBlock) kept.push(line);
    }
    const stripped = kept.join("\n").replace(/\s+$/, "");
    if (stripped) fs.writeFileSync(cfg, stripped + "\n");
    else if (body.includes(START)) fs.unlinkSync(cfg);
  '
  if [[ "$had_block" -eq 1 ]]; then
    if [[ -f "$cfg" ]]; then
      echo "Removed managed hooks block from $cfg (rest of the file preserved)."
    else
      echo "Removed managed hooks block; $cfg held only kaola content and was removed."
    fi
  fi
}

# Remove ONLY kaola-deployed artifacts from the resolved scope, by source-tree directory name
# (never a blind rm of a dir the user may share). Strips the managed hooks block from
# config.toml (preserving the rest). The SHARED ~/.config/kaola-workflow/config.json is
# kept for any co-installed Claude/Codex/opencode edition.
uninstall_edition() {
  local home skills_dest
  home="$(kimi_home)"
  if [[ "$GLOBAL" -eq 1 ]]; then
    skills_dest="$home/skills"
  else
    skills_dest="${TARGET:-$PWD}/.kimi-code/skills"
  fi
  echo "Uninstalling Kaola-Workflow · kimi edition ($FORGE) from → $skills_dest"
  if [[ -d "$skills_dest" && "$SOURCE_TREE/skills" -ef "$skills_dest" ]]; then
    echo "Refusing to uninstall the edition's OWN source tree ($skills_dest). No-op." >&2
    return
  fi
  local src_dir
  for src_dir in "$SOURCE_TREE/skills/"*/; do
    [[ -d "$src_dir" ]] || continue
    rm -rf "$skills_dest/$(basename "$src_dir")"
  done
  # Uninstall removes by SOURCE-TREE name, so a role skill RETIRED since the deployed install is
  # absent from the source tree and would linger forever. Remove the retired names explicitly.
  local retired
  for retired in "${RETIRED_ROLE_SKILLS[@]}"; do
    [[ -d "$skills_dest/$retired" ]] || continue
    rm -rf "$skills_dest/$retired"
    echo "Removed retired role skill: $skills_dest/$retired"
  done
  rmdir "$skills_dest" 2>/dev/null || true
  if [[ "$GLOBAL" -ne 1 ]]; then rmdir "${TARGET:-$PWD}/.kimi-code" 2>/dev/null || true; fi
  echo "Removed deployed skills."
  # Support scripts + hook scripts (kimi-home dir; honors $KIMI_CODE_HOME). Removed by name;
  # the kaola-workflow dirs are rmdir'd only once empty.
  local scripts_dir="$home/kaola-workflow/scripts"
  local hooks_dir="$home/kaola-workflow/hooks"
  local manifest="$SCRIPT_DIR/scripts/kaola-workflow-install-manifest.js"
  if [[ -f "$manifest" && -d "$scripts_dir" ]]; then
    local name
    while IFS= read -r name || [[ -n "$name" ]]; do
      [[ -n "$name" ]] || continue
      # Defense in depth: the manifest emits plain script basenames. Anything else never
      # becomes a delete path.
      if ! is_plain_basename "$name"; then
        echo "warning: ignoring support-script manifest entry that is not a plain file name: $name" >&2
        continue
      fi
      rm -f "$scripts_dir/$name"
    done < <(node "$manifest" --forge="$FORGE" --scripts 2>/dev/null)
  fi
  # Outside the manifest guard on purpose: a retired script is absent from the manifest by
  # definition, so its removal must not be conditional on the manifest being readable.
  remove_retired_support_scripts "$scripts_dir"
  if [[ -d "$hooks_dir" ]]; then
    local hook
    for hook in "$SOURCE_TREE/hooks/"*.sh; do
      [[ -f "$hook" ]] || continue
      rm -f "$hooks_dir/$(basename "$hook")"
    done
    # A hook RETIRED since the deployed install is absent from the source tree and would linger
    # forever (same reason as the retired role skills above). Remove the retired names explicitly.
    for retired in "${RETIRED_HOOKS[@]}"; do
      [[ -f "$hooks_dir/$retired" ]] || continue
      rm -f "$hooks_dir/$retired"
      echo "Removed retired hook script: $hooks_dir/$retired"
    done
  fi
  rmdir "$scripts_dir" 2>/dev/null || true
  rmdir "$hooks_dir" 2>/dev/null || true
  rmdir "$home/kaola-workflow" 2>/dev/null || true
  echo "Removed deployed support scripts + hook scripts."
  strip_hooks_config
  echo "Uninstall complete. A fresh ./install-kimi.sh now deploys the workflow edition."
}

# Interactive confirmation. --yes skips it; non-interactive stdin proceeds without prompting
# (mirrors install-opencode.sh, which accepts --yes and never blocks on a pipe).
confirm_install() {
  if [[ "$YES" -eq 1 ]]; then return 0; fi
  if [[ ! -t 0 ]]; then return 0; fi
  cat <<EOF
About to install the Kaola-Workflow kimi edition:
  skills              → $SKILLS_DEST
  support scripts     → $(kimi_home)/kaola-workflow/scripts
  hook scripts        → $(kimi_home)/kaola-workflow/hooks
  hooks config block  → $(kimi_home)/config.toml (managed block)
EOF
  local reply=""
  read -r -p "Proceed? [Y/n] " reply || reply="n"
  case "$reply" in
    n|N|no|No|NO) echo "Aborted."; exit 0 ;;
  esac
}

# --uninstall short-circuits the install entirely (functions are defined above).
if [[ "$UNINSTALL" -eq 1 ]]; then
  uninstall_edition
  exit 0
fi

if [[ "$GLOBAL" -eq 1 ]]; then
  DEST_ROOT="$(kimi_home)"
  SKILLS_DEST="$DEST_ROOT/skills"
  echo "Deploying globally ($FORGE) → $DEST_ROOT"
else
  DEST_ROOT="${TARGET:-$PWD}"
  SKILLS_DEST="$DEST_ROOT/.kimi-code/skills"
  echo "Deploying into project ($FORGE) → $DEST_ROOT"
fi

confirm_install
copy_skills "$SKILLS_DEST"
install_support_scripts
merge_hooks_config

echo ""
echo "Next: open the project in Kimi Code and run a workflow command, e.g.:"
echo "  /workflow-init"
