#!/usr/bin/env bash
# install-opencode.sh — deploy the Kaola-Workflow opencode edition into a project.
#
# Additive standalone installer (does NOT modify install.sh or the
# claude/codex/gitlab/gitea editions). opencode is a runtime (like Codex), not a
# git forge, so it is delivered the opencode-native way: .opencode/. This runtime installs
# no Kaola role profiles by design.
#
# FORGE: --forge=github|gitlab|gitea selects which forge's workflow prose and support
# scripts to deploy (default github). The runtime is still not a forge — this installer
# remains standalone and additive — but the workflow PROSE is forge-shaped (gh vs glab
# vs tea, PR vs MR, per-forge script basenames), so a GitLab/Gitea project must not be
# handed GitHub-shaped commands. The forge variants are GENERATED by
# sync-opencode-edition.js from the same routing surfaces the other editions ship;
# github renders .opencode/, a forge renders .opencode-<forge>/.
#
# Usage:
#   ./install-opencode.sh                         # deploy into the current directory
#   ./install-opencode.sh --target /path/to/repo  # deploy into a specific project
#   ./install-opencode.sh --forge=gitlab          # deploy the GitLab-shaped edition
#   ./install-opencode.sh --global                # deploy commands to ~/.config/opencode
#   ./install-opencode.sh --regenerate            # refresh the generated tree from canonical here
#
# COMMAND SET: the install deploys the workflow command set (finalize, workflow-init,
# workflow-next) into .opencode/commands/. The generated .opencode/commands/*
# are produced by sync-opencode-edition.js from the canonical sources.
#
# The generated commands resolve support scripts via an
# OPENCODE-NATIVE path (${OPENCODE_CONFIG_DIR:-$HOME/.config/opencode}/kaola-workflow/scripts)
# — there is NO $CLAUDE_PLUGIN_ROOT and NO ~/.claude/kaola-workflow in the deployed tree.
# install_support_scripts deploys to that opencode-native dir (not ~/.claude/).
#
# DEPLOY LAYOUT (scope-dependent — opencode resolves commands/plugins differently by scope):
#   - PROJECT (--target/$PWD): commands/plugins/hooks live under <project>/.opencode/{...}
#     (the project-local .opencode dir opencode scans).
#   - GLOBAL (--global): they live DIRECTLY under the config root ${OPENCODE_CONFIG_DIR:-$HOME/.config/opencode}/{...}
#     (NOT a nested .opencode/ — the config dir IS opencode's global ".opencode equivalent"; a nested
#     ~/.config/opencode/.opencode/ is never scanned). copy_tree takes a `layout_root` arg for exactly this.
#   - opencode.json is user-owned and is never written by this installer.
#
# REINSTALL IS SELF-HEALING, AND NOTHING WIDER: copy_tree removes each command file it is about
# to re-copy (immediately before re-copying it) plus the RETIRED_WORKFLOW_COMMANDS this edition no
# longer ships, so a reinstall converges to the workflow command set without destroying a deployed
# command it has nothing to put back. --uninstall removes the full deployed surface; see
# uninstall_edition.
#
# THE DEPLOY NAMES WHAT IT RETIRES. Commands DECLARE it: RETIRED_WORKFLOW_COMMANDS lists the
# names this edition once shipped and no longer does, and a deployed command that is neither
# retired nor about to be written is left alone. The namespace glob that used to stand in for
# that list could not tell the two apart, so it swept whatever the source failed to render —
# silently, and reported as a successful install. Retired agents (#1101) are proven, never
# named: a previous release's manifest row (`<filename>\t<sha256>`) still matching the file, or
# bytes that are a released render (the first releases wrote no manifest), prove Kaola wrote it.
# Any other Kaola-named file — edited or unrecorded — is kept and reported.

set -euo pipefail

# The temp base every mktemp below writes under. `${TMPDIR:-/tmp}` guards an EMPTY
# TMPDIR and NOT a relative one, and a bare `mktemp` reads TMPDIR the same way — on
# GNU coreutils a relative TMPDIR resolves against the invoking directory (the
# checkout, for a local install), so the temp files land beside tracked files.
# Same guard as install-all.sh: absolute or nothing.
KW_TMPDIR="${TMPDIR:-/tmp}"
case "$KW_TMPDIR" in
  /*) ;;
  *) KW_TMPDIR="/tmp" ;;
esac

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
TARGET=""
GLOBAL=0
REGENERATE=0
UNINSTALL=0
YES=0
NO_SCRIPTS=0
FORGE="github"

usage() {
  cat <<'EOF'
Usage: ./install-opencode.sh [--target DIR] [--forge=github|gitlab|gitea] [--global]
                            [--regenerate] [--uninstall] [--no-scripts] [--yes]
  --target DIR     deploy into DIR (default: current directory)
  --forge F        github (default), gitlab, or gitea — which forge's workflow prose
                   and support scripts to deploy
  --global         deploy commands+plugin+hooks into ~/.config/opencode (all projects)
  --regenerate     refresh the in-repo .opencode/ tree from canonical, then exit
  --uninstall      remove the kaola-deployed opencode edition from the resolved scope
                   (honors --target/--global), then exit (see UNINSTALL below)
  --no-scripts     skip installing support scripts (see SUPPORT SCRIPTS below)
  --yes            non-interactive (accept the default deploy path)

CONFIG: opencode.json is user-owned and is never written by this installer. Any
agent.<role> binding for a Kaola role an older release may have seeded is reported, not edited.

SUPPORT SCRIPTS: workflow commands locate scripts via kaola_script(), which searches
./scripts/ and ${OPENCODE_CONFIG_DIR:-$HOME/.config/opencode}/kaola-workflow/scripts/
(opencode-native, honoring $OPENCODE_CONFIG_DIR). For a CONSUMER project (not this repo)
the installer copies the support scripts there so the commands resolve. Self-dev in this
repo needs none of that (./scripts/ is used directly).

UNINSTALL: --uninstall removes ONLY kaola-deployed artifacts from the resolved scope
(project DEST_ROOT via --target/$PWD, or --global ${OPENCODE_CONFIG_DIR:-$HOME/.config/opencode}):
the deployed commands/plugin/hooks, the subagent profiles earlier releases deployed (only on
proof: a manifest row still matching, or a released render; others are kept and reported)
and the opencode-native support scripts.
The SHARED ~/.config/kaola-workflow/config.json is reference-counted: it is removed only when no
runtime still holds a reference.
Your own opencode.json (model/permission config) is PRESERVED. A subsequent bare install
then deploys the workflow edition.
EOF
}

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    --target) TARGET="${2:?--target requires a directory}"; shift 2 ;;
    --forge=*) FORGE="${1#--forge=}"; shift ;;
    --forge) FORGE="${2:?--forge requires github, gitlab, or gitea}"; shift 2 ;;
    --global) GLOBAL=1; shift ;;
    --regenerate) REGENERATE=1; shift ;;
    --uninstall) UNINSTALL=1; shift ;;
    --no-scripts) NO_SCRIPTS=1; shift ;;
    -y|--yes) YES=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

# Resolve the forge layout from the ONE source the generators use (scripts/runtime-edition-forge.js),
# so this installer never restates a forge dir or a per-forge script name. An unknown forge fails
# here, loudly, before anything is written.
FORGE_HELPER="$SCRIPT_DIR/scripts/runtime-edition-forge.js"
if [[ ! -f "$FORGE_HELPER" ]]; then
  echo "Install error: forge layout helper missing: $FORGE_HELPER" >&2
  exit 1
fi
if ! FORGE_SUFFIX="$(node "$FORGE_HELPER" --forge="$FORGE" --out-suffix)"; then
  echo "Install error: unknown forge \"$FORGE\" (expected github, gitlab, or gitea)" >&2
  exit 2
fi
if ! FORGE_SCRIPTS_DIR="$(node "$FORGE_HELPER" --forge="$FORGE" --scripts-dir)"; then
  echo "Install error: cannot resolve the support-script dir for forge $FORGE" >&2
  exit 1
fi
# The generated tree this forge deploys FROM: .opencode for github, .opencode-<forge> otherwise.
# WHERE that tree lives is the generator's answer, never this script's guess: it is not always the
# directory this installer sits in (a linked worktree's tree belongs to the main checkout), and a
# deploy that copies from a path the generator never writes installs nothing.
if ! TREE_ROOT="$(node "$SCRIPT_DIR/scripts/sync-opencode-edition.js" --print-tree-root)"; then
  echo "Install error: cannot resolve where the generated opencode tree lands" >&2
  exit 1
fi
SOURCE_TREE="$TREE_ROOT/.opencode$FORGE_SUFFIX"

# Always ensure the in-repo generated tree is fresh before copying from it (install only — an
# uninstall removes by source filename and must not regenerate the repo tree).
if [[ "$UNINSTALL" -ne 1 ]]; then
  echo "Kaola-Workflow · opencode edition ($FORGE) — refreshing generated tree..."
  node "$SCRIPT_DIR/scripts/sync-opencode-edition.js" --forge="$FORGE" --check >/dev/null 2>&1 \
    || node "$SCRIPT_DIR/scripts/sync-opencode-edition.js" --forge="$FORGE" --write >/dev/null
fi

if [[ "$REGENERATE" -eq 1 ]]; then
  echo "Regenerated $SOURCE_TREE from canonical. Done."
  exit 0
fi

# Workflow command set: the commands deployed into .opencode/commands/. Any OTHER command fails
# CLOSED (skipped + warned) so a future canonical command cannot silently widen the install.
# Single source of truth for the deploy set (used by copy_tree).
WORKFLOW_COMMANDS=(
  kaola-workflow-finalize.md workflow-init.md workflow-next.md
)
# Commands this edition deployed on a PREVIOUS release and no longer generates. This is where
# "retired on purpose" is written down, and BOTH paths read it: the install sweep is exactly the
# deploy set PLUS these names, and a deployed command that is neither is one this install simply
# has nothing to put back (#973 — a namespace-wide prune destroyed it silently, and no count
# guard covers commands); uninstall removes by current source-tree name, which a retired command
# no longer carries, so it removes these names explicitly as well.
# Bounded by what this edition actually shipped, measured from .opencode/commands/ history.
RETIRED_WORKFLOW_COMMANDS=(
  kaola-workflow-adapt.md kaola-workflow-auto.md kaola-workflow-fast.md
  kaola-workflow-phase1.md kaola-workflow-phase2.md kaola-workflow-phase3.md
  kaola-workflow-phase4.md kaola-workflow-phase5.md kaola-workflow-plan-run.md
)
# Hook scripts this edition deployed on a PREVIOUS release and no longer generates — the same
# declaration model as the commands above, read by BOTH paths: removal is exactly these names
# plus what the deploy is about to write, never a sweep of the whole hooks dir. Bounded by what
# the edition's hook set ever carried: pre-commit, write-lane, and the dispatch log shipped from
# earlier hook deployments and are now retired.
RETIRED_HOOKS=(
  kaola-workflow-pre-commit.sh kaola-workflow-write-lane.sh
  kaola-workflow-subagent-dispatch-log.sh
)
# Support scripts this edition deployed on a PREVIOUS release and no longer deploys. The INSTALL path
# already converges (it enumerates the destination and drops anything absent from what it just
# deployed), which is why a reinstall heals a stranded script; uninstall removes strictly by the
# CURRENT manifest, so a retired name survives an uninstall that removes every current artifact
# around it. Same declaration model as the two lists above, read by the uninstall path.
#
# Censused from the SUPPORT_SCRIPTS history in scripts/kaola-workflow-install-manifest.js
# (`git log -L` over that array), cross-checked against `git log --diff-filter=D` over scripts/ —
# never from the installer's own arrays, since a list validated against itself cannot show an
# omission. Bounded by what this edition shipped: it deploys support scripts from its first release
# (2026-06-19), so it carries every name retired since — autopilot (2026-06-26), parallel-batch
# (07-02), the three fast/full/phase4 advancers (07-19), and the eight retired with the DAG executor
# (07-31). A namespace sweep of the scripts dir is deliberately NOT used here: it would reintroduce
# exactly the defect #973 removed.
RETIRED_SUPPORT_SCRIPTS=(
  kaola-workflow-autopilot.js kaola-workflow-parallel-batch.js
  kaola-workflow-fast-advance.js kaola-workflow-full-advance.js kaola-workflow-phase4-advance.js
  kaola-workflow-repair-state.js kaola-workflow-plan-validator.js kaola-workflow-next-action.js
  kaola-workflow-commit-node.js kaola-workflow-adaptive-handoff.js kaola-workflow-adaptive-node.js
  kaola-workflow-replan.js kaola-workflow-task-mirror.js
  kaola-workflow-ledger-compare.js
)

# Remove the retired support scripts from a deployed scripts dir. Each canonical base is removed
# alongside its two forge-port spellings: the manifest renames kaola-workflow-<X> to
# kaola-<forge>-workflow-<X> for gitlab and gitea, so the deployed basename depends on the forge the
# home was installed under — which need not be the forge this uninstall was invoked with. All three
# spellings of a RETIRED name are safe to remove and none of them is a current artifact. Every name
# still goes through is_plain_basename before it becomes a delete path.
remove_retired_support_scripts() {
  local dir="$1"
  [[ -d "$dir" ]] || return 0
  local base name
  for base in "${RETIRED_SUPPORT_SCRIPTS[@]}"; do
    for name in "$base" \
      "${base/#kaola-workflow-/kaola-gitlab-workflow-}" \
      "${base/#kaola-workflow-/kaola-gitea-workflow-}"; do
      is_plain_basename "$name" || continue
      [[ -f "$dir/$name" ]] || continue
      rm -f "$dir/$name"
      echo "Removed retired support script: $dir/$name"
    done
  done
}
in_array() { local needle="$1"; shift; local x; for x in "$@"; do [[ "$x" == "$needle" ]] && return 0; done; return 1; }

# Name of the deploy manifest recorded inside the deployed agent dir (a dotfile, so it never
# shadows an agent). Same tab-separated `<filename>\t<sha256>` shape install.sh uses.
AGENT_MANIFEST_NAME=".kaola-workflow-agent-manifest"
SOURCE_COMMAND_DIR="$SOURCE_TREE/commands"

sha256_file() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  else
    shasum -a 256 "$1" | awk '{print $1}'
  fi
}

# True when `$1` is a plain file name: non-empty, no path separator, not `.`/`..`,
# not absolute. A deploy manifest records BASENAMES only, so anything else is corruption or
# tampering and must never be turned into a filesystem path.
is_plain_basename() {
  local n="${1-}"
  [[ -n "$n" ]] || return 1
  case "$n" in
    */*|*\\*|.|..) return 1 ;;
  esac
  return 0
}

# Retire the subagent profiles earlier releases installed (#1101), with
# scripts/kaola-workflow-retired-agents.js: <layout>/agents (manifest), the retired singular
# <layout>/agent (its own manifest, or none in the first releases) and, for the global scope, the
# nested <config>/.opencode/agent the v6.7-v6.8 global installs wrote. A file a manifest records
# with the digest it still has, or whose bytes are a released render, is removed; every other
# Kaola-named file is kept and reported; each manifest is retired once read. A symlinked or
# non-directory carrier is reported and never followed; it does not block the install (H9).
# opencode.json is never written: its agent.<role> bindings carry no ownership evidence, so a
# Kaola-role binding is only reported.
retire_opencode_agents() {
  local dest_root="$1" layout_root="$2" global="$3" dir
  local sweep="$SCRIPT_DIR/scripts/kaola-workflow-retired-agents.js"
  for dir in "$layout_root/agents" "$layout_root/agent"; do
    node "$sweep" retire --runtime opencode --dir "$dir" --record "$dir/$AGENT_MANIFEST_NAME" || {
      echo "error: retired OpenCode agent sweep failed for $dir" >&2
      exit 1
    }
    if [[ -d "$dir" && ! -L "$dir" ]]; then rmdir "$dir" 2>/dev/null || true; fi
  done
  if [[ "$global" -eq 1 ]]; then
    dir="$dest_root/.opencode/agent"
    node "$sweep" retire --runtime opencode --dir "$dir" --record "$dir/$AGENT_MANIFEST_NAME" || {
      echo "error: retired OpenCode agent sweep failed for $dir" >&2
      exit 1
    }
    if [[ -d "$dir" && ! -L "$dir" ]]; then
      rmdir "$dir" 2>/dev/null || true
      rmdir "$dest_root/.opencode" 2>/dev/null || true
    fi
  fi
  node "$sweep" report-bindings --runtime opencode --config "$dest_root/opencode.json" || true
}

copy_tree() {
  local dest_root="$1"    # holds opencode.json (config/project root)
  # layout_root: the dir that DIRECTLY holds agents/commands/plugins/hooks. Project → $dest_root/.opencode;
  # Global → $dest_root (the config root itself; opencode never scans a nested .opencode/ there).
  local layout_root="${2:-$dest_root/.opencode}"
  local global_scope=0
  [[ "$layout_root" == "$dest_root" ]] && global_scope=1
  retire_opencode_agents "$dest_root" "$layout_root" "$global_scope"

  mkdir -p "$layout_root/commands" "$layout_root/plugins" "$layout_root/hooks"
  # #1044 retires the old OpenCode compact reader. Remove only the exact historical bytes; preserve
  # a modified or user-authored file at the same path.
  local retired_plugin="$layout_root/plugins/kaola-workflow-hooks.js"
  local retired_plugin_sha="ce9493a152f9982a286787b8098714188757dd11824b9dff8cf442845d3a8ecc"
  if [[ -f "$retired_plugin" && ! -L "$retired_plugin" ]]; then
    if [[ "$(sha256_file "$retired_plugin")" == "$retired_plugin_sha" ]]; then
      rm -f "$retired_plugin"
      echo "Removed retired OpenCode compact plugin: $retired_plugin"
    else
      echo "Preserved modified OpenCode plugin at retired path: $retired_plugin" >&2
    fi
  fi
  # Self-dev guard: deploying the edition into its OWN source repo means the canonical .opencode and
  # the destination layout are the same directory, so `cp` would refuse ("X and X are identical") and
  # trip `set -e`. In that case the generated tree already IS the live one — skip the (no-op) copy.
  if [[ "$SOURCE_TREE" -ef "$layout_root" ]]; then
    echo "Self-dev deploy (source .opencode is already the live tree) → copy skipped."
    return
  fi
  # The COMMAND deploy is SELF-HEALING, and it removes exactly two things: the names this edition
  # RETIRED on purpose, and each command file it is about to WRITE, immediately before writing it.
  # A deployed command that is neither is one this install has nothing to put back, so a source
  # tree that renders fewer commands than the destination holds leaves the difference alone rather
  # than destroying it (#973 — silent here, since nothing counts commands the way the agent deploy
  # counts agents). The re-copy is a fail-CLOSED ALLOWLIST: a command not in WORKFLOW_COMMANDS is
  # skipped + warned, so a future canonical command cannot silently widen the install.
  # Agents/plugins/hooks are always fully deployed; the hook deploy below gets the same
  # self-healing — the RETIRED_HOOKS names are removed first, since the copy alone would leave a
  # hook an older release deployed on disk for good.
  local stale_file retired
  for retired in "${RETIRED_WORKFLOW_COMMANDS[@]}"; do
    stale_file="$layout_root/commands/$retired"
    [[ -f "$stale_file" ]] || continue
    rm -f "$stale_file"
  done
  local command_file base
  for command_file in "$SOURCE_COMMAND_DIR/"*.md; do
    [[ -f "$command_file" ]] || continue
    base="$(basename "$command_file")"
    if ! in_array "$base" "${WORKFLOW_COMMANDS[@]}"; then
      echo "warning: skipping unrecognized command not in the workflow command set: $base" >&2
      continue
    fi
    # Replace the file this install is about to write, so `cp` never has to overwrite in place.
    rm -f "$layout_root/commands/$base"
    cp "$command_file" "$layout_root/commands/$base"
  done
  # A singular command name is not ownership proof. Retire only a current command whose complete
  # bytes still equal the generated source; retired-name and owner-modified near misses survive.
  local legacy_command_dir="$layout_root/command"
  for base in "${WORKFLOW_COMMANDS[@]}"; do
    [[ -f "$legacy_command_dir/$base" && ! -L "$legacy_command_dir/$base" ]] || continue
    [[ -f "$SOURCE_COMMAND_DIR/$base" ]] || continue
    [[ "$(sha256_file "$legacy_command_dir/$base")" == "$(sha256_file "$SOURCE_COMMAND_DIR/$base")" ]] || continue
    rm -f "$legacy_command_dir/$base"
  done
  rmdir "$legacy_command_dir" 2>/dev/null || true
  for retired in "${RETIRED_HOOKS[@]}"; do
    rm -f "$layout_root/hooks/$retired"
  done
  cp "$SOURCE_TREE/hooks/"*.sh "$layout_root/hooks/" 2>/dev/null || true
  chmod +x "$layout_root/hooks/"*.sh 2>/dev/null || true
  echo "Installed workflow commands+plugin+hooks → $layout_root/"
}

# #1087 (#1086 F3): a global-scope uninstall strips this runtime's OWN global-contract carrier
# through its own per-target record and releases that record's shared-block reference. A carrier
# the owner edited since install is refused (OWNER_CONFLICT) and left in place; no other runtime's
# carrier or record is read for removal. A project-scope uninstall leaves the machine-global carrier.
uninstall_global_carrier() {
  [[ "$GLOBAL" -eq 1 ]] || return 0
  local output rc=0 status
  output="$(node "$SCRIPT_DIR/scripts/kaola-workflow-global-contract.js" uninstall --runtime opencode --json 2>&1)" || rc=$?
  status="$(node -e 'try { console.log(JSON.parse(process.argv[1]).status || "UNKNOWN"); } catch (_) { console.log("UNKNOWN"); }' "$output")"
  if [[ "$rc" -eq 0 ]]; then
    echo "opencode global contract carrier: $status"
  else
    echo "warning: opencode global contract carrier left in place ($status, exit $rc)" >&2
    printf '%s\n' "$output" >&2
  fi
}

# #1087 (#1086 F2): release this runtime's reference on the shared ~/.config/kaola-workflow block.
# The registry keeps the block while any other runtime (or another scope of this one) holds a
# reference and removes it only when this was the last one.
release_shared_config_ref() {
  local scope_args=(--scope global) out
  if [[ "$GLOBAL" -ne 1 ]]; then scope_args=(--scope project --target "${TARGET:-$PWD}"); fi
  if out="$(node "$SCRIPT_DIR/scripts/kaola-workflow-shared-refs.js" deregister \
      --runtime opencode "${scope_args[@]}")"; then
    echo "Released shared config reference (opencode): $out"
  else
    echo "warning: shared config reference not released ($out); ~/.config/kaola-workflow left in place." >&2
  fi
}

# Remove ONLY kaola-deployed artifacts from the resolved scope, by source-tree filename plus the
# names this edition retired on purpose (never a blind rm of a dir the user may share). Preserves
# the user-owned opencode.json; the SHARED ~/.config/kaola-workflow/config.json is released by
# reference (release_shared_config_ref), never deleted here.
uninstall_edition() {
  local dest_root layout_root
  if [[ "$GLOBAL" -eq 1 ]]; then
    dest_root="${OPENCODE_CONFIG_DIR:-$HOME/.config/opencode}"
    layout_root="$dest_root"
  else
    dest_root="${TARGET:-$PWD}"
    layout_root="$dest_root/.opencode"
  fi
  echo "Uninstalling Kaola-Workflow · opencode edition ($FORGE) from → $layout_root"
  if [[ "$SOURCE_TREE" -ef "$layout_root" ]]; then
    echo "Refusing to uninstall the edition's OWN source tree ($layout_root). No-op." >&2
    return
  fi
  local f base sub
  local dest
  # Retired agents: the same proof the install uses (retire_opencode_agents).
  retire_opencode_agents "$dest_root" "$layout_root" "$GLOBAL"
  for f in "$SOURCE_COMMAND_DIR/"*.md; do
    [[ -f "$f" ]] || continue
    dest="$layout_root/commands/$(basename "$f")"
    [[ -f "$dest" && ! -L "$dest" ]] || continue
    [[ "$(sha256_file "$dest")" == "$(sha256_file "$f")" ]] && rm -f "$dest"
  done
  rm -f "$layout_root/plugins/kaola-workflow-hooks.js"
  for f in "$SOURCE_TREE/hooks/"*.sh;                        do [[ -f "$f" ]] || continue; rm -f "$layout_root/hooks/$(basename "$f")"; done
  # A command or hook RETIRED since the deployed install is absent from the source tree, so the
  # loops above never name it and it would linger forever. Remove the retired names explicitly.
  for base in "${RETIRED_WORKFLOW_COMMANDS[@]}"; do
    [[ -f "$layout_root/commands/$base" ]] || continue
    rm -f "$layout_root/commands/$base"
    echo "Removed retired command: $layout_root/commands/$base"
  done
  for base in "${RETIRED_HOOKS[@]}"; do
    [[ -f "$layout_root/hooks/$base" ]] || continue
    rm -f "$layout_root/hooks/$base"
    echo "Removed retired hook: $layout_root/hooks/$base"
  done
  for base in "${WORKFLOW_COMMANDS[@]}"; do
    dest="$layout_root/command/$base"
    [[ -f "$dest" && ! -L "$dest" && -f "$SOURCE_COMMAND_DIR/$base" ]] || continue
    [[ "$(sha256_file "$dest")" == "$(sha256_file "$SOURCE_COMMAND_DIR/$base")" ]] && rm -f "$dest"
  done
  for sub in commands agents command agent plugins hooks; do rmdir "$layout_root/$sub" 2>/dev/null || true; done
  [[ "$GLOBAL" -eq 1 ]] || rmdir "$layout_root" 2>/dev/null || true
  echo "Removed deployed agents/commands/plugin/hooks."
  # Support scripts (opencode-native dir; honors $OPENCODE_CONFIG_DIR).
  local scripts_dir="${OPENCODE_CONFIG_DIR:-$HOME/.config/opencode}/kaola-workflow/scripts"
  local manifest="$SCRIPT_DIR/scripts/kaola-workflow-install-manifest.js"
  if [[ -f "$manifest" && -d "$scripts_dir" ]]; then
    local name
    while IFS= read -r name || [[ -n "$name" ]]; do
      [[ -n "$name" ]] || continue
      # Defense in depth: the manifest emits plain script basenames. Anything else never
      # becomes a delete path.
      if ! is_plain_basename "$name"; then
        echo "warning: ignoring support-script manifest entry that is not a plain file name: $name" >&2
        continue
      fi
      rm -f "$scripts_dir/$name"
    done < <(node "$manifest" --forge="$FORGE" --scripts 2>/dev/null)
    echo "Removed deployed support scripts."
  fi
  # Outside the manifest guard on purpose: a retired script is absent from the manifest by
  # definition, so its removal must not be conditional on the manifest being readable.
  remove_retired_support_scripts "$scripts_dir"
  rmdir "$scripts_dir" 2>/dev/null || true
  rmdir "${OPENCODE_CONFIG_DIR:-$HOME/.config/opencode}/kaola-workflow" 2>/dev/null || true
  if [[ -f "$dest_root/opencode.json" ]]; then
    echo "Preserved $dest_root/opencode.json (user-owned model/permission config)."
  fi
  uninstall_global_carrier
  release_shared_config_ref
  echo "Uninstall complete. A fresh ./install-opencode.sh now deploys the workflow edition."
}

# Install the support scripts the workflow commands invoke (kaola_script() search path includes
# ${OPENCODE_CONFIG_DIR:-$HOME/.config/opencode}/kaola-workflow/scripts/ — opencode-native, #544).
# Reuses the single-source install manifest; only meaningful for consumer projects.
install_support_scripts() {
  if [[ "$NO_SCRIPTS" -eq 1 ]]; then
    echo "Support scripts skipped (--no-scripts)."
    return
  fi
  local manifest="$SCRIPT_DIR/scripts/kaola-workflow-install-manifest.js"
  [[ -f "$manifest" ]] || { echo "warning: install manifest not found; skipping support scripts." >&2; return; }
  local dest="${OPENCODE_CONFIG_DIR:-$HOME/.config/opencode}/kaola-workflow/scripts"
  mkdir -p "$dest"
  local name src
  local deployed=()
  while IFS= read -r name || [[ -n "$name" ]]; do
    [[ -n "$name" ]] || continue
    src="$FORGE_SCRIPTS_DIR/$name"
    # The Oracle Kernel is de-duplicated to a single canonical source; a forge tree that
    # does not carry its own copy resolves it from scripts/ (mirrors install.sh).
    [[ -f "$src" ]] || src="$SCRIPT_DIR/scripts/$name"
    if [[ ! -f "$src" ]]; then
      echo "Install error: allowlisted support script missing from source for forge $FORGE: $name" >&2
      exit 1
    fi
    cp "$src" "$dest/$name"
    chmod +x "$dest/$name"
    deployed+=("$name")
  done < <(node "$manifest" --forge="$FORGE" --scripts 2>/dev/null)
  # Copying forward never REMOVES, so a script whose source the tree has since retired lives in
  # the config home for good and the deployed set drifts up release by release. Converge the dir
  # on the manifest instead, exactly as install.sh does ("Remove stale support scripts not
  # present in source.").
  #
  # ENUMERATES THE DESTINATION and intersects it against what was just deployed, so a delete path
  # is never CONSTRUCTED from a manifest-supplied name (same discipline as the retired-agent sweep).
  # Scoped to `*.js` — install.sh's scope, not a wider one invented here — so anything else a user
  # keeps alongside survives. A deploy that copied NOTHING (an empty/failed manifest read) sweeps
  # nothing rather than emptying the directory.
  if [[ ${#deployed[@]} -gt 0 ]]; then
    local stale_file stale_name is_current
    for stale_file in "$dest"/*.js; do
      [[ -f "$stale_file" ]] || continue
      stale_name="$(basename "$stale_file")"
      is_current=0
      for name in "${deployed[@]}"; do
        [[ "$name" == "$stale_name" ]] && is_current=1 && break
      done
      if [[ "$is_current" -eq 0 ]]; then
        rm -f "$stale_file"
        echo "Removed stale script: $stale_file"
      fi
    done
  fi
  echo "Installed support scripts → $dest (kaola_script() search path; forge $FORGE)"
}

# --uninstall short-circuits the install entirely (functions are defined above).
if [[ "$UNINSTALL" -eq 1 ]]; then
  uninstall_edition
  exit 0
fi

if [[ "$GLOBAL" -eq 1 ]]; then
  DEST_ROOT="${OPENCODE_CONFIG_DIR:-$HOME/.config/opencode}"
  echo "Deploying globally ($FORGE) → $DEST_ROOT"
  # GLOBAL: opencode scans the config root DIRECTLY (commands/plugins under ~/.config/opencode/,
  # NOT a nested .opencode/). layout_root = the config root itself.
  copy_tree "$DEST_ROOT" "$DEST_ROOT"
  install_support_scripts
else
  DEST_ROOT="${TARGET:-$PWD}"
  echo "Deploying into project ($FORGE) → $DEST_ROOT"
  # PROJECT: opencode scans <project>/.opencode/. layout_root = $DEST_ROOT/.opencode (copy_tree default).
  copy_tree "$DEST_ROOT" "$DEST_ROOT/.opencode"
  install_support_scripts
fi

# Machine-global contract carrier (#1087). The LAST install step installs ONLY this runtime's own
# adapter target through the per-target global-contract CLI: no other runtime's home is written,
# no install order is assumed, and a carrier conflict blocks only this runtime.
install_global_carrier() {
  local output rc=0
  output="$(node "$SCRIPT_DIR/scripts/kaola-workflow-global-contract.js" install --runtime opencode --json 2>&1)" || rc=$?
  if [[ "$rc" -ne 0 ]]; then
    echo "Install error: opencode global contract carrier not installed (exit $rc)" >&2
    printf '%s\n' "$output" >&2
    exit 1
  fi
  echo "Installed opencode global contract carrier (per-target record under ~/.config/kaola-workflow)"
}
install_global_carrier

echo ""
echo "Next: open the project in opencode and run a workflow command, e.g.:"
echo "  /workflow-init"
