#!/usr/bin/env bash
# install-zcode.sh — deploy the Kaola-Workflow ZCode edition into a project (or globally).
#
# Additive standalone installer (does NOT modify install.sh, install-opencode.sh,
# install-kimi.sh, install-grok.sh, install-cursor.sh, or the claude/codex/gitlab/gitea
# editions). ZCode is a runtime (like opencode, Kimi, Grok, and Cursor), not a git forge,
# so it is delivered the ZCode-native way: named agents under .zcode/agents/, flat
# commands under .zcode/commands/, and a merged .zcode/config.json (top-level `hooks`
# object, `"enabled": true`, ZCode's seven events — there is no SubagentStart).
#
# ZCode discovers subagents ONLY at user scope: a project install stages the agent
# roster under <project>/.zcode/agents/ AND syncs the same files to
# ${ZCODE_HOME:-$HOME/.zcode}/agents/ — the user scope is the one ZCode reads agents
# from; workspace-scope agents are unsupported in this beta.
#
# FORGE: --forge=github|gitlab|gitea selects which forge's workflow prose and support
# scripts to deploy (default github). The forge variants are GENERATED by
# sync-zcode-edition.js from the same routing surfaces the other editions ship;
# github renders .zcode/, a forge renders .zcode-<forge>/.
#
# Usage:
#   ./install-zcode.sh                         # deploy into the current directory
#   ./install-zcode.sh --target /path/to/repo  # deploy into a specific project
#   ./install-zcode.sh --forge=gitlab          # deploy the GitLab-shaped edition
#   ./install-zcode.sh --global                # deploy agents+commands to ${ZCODE_HOME:-~/.zcode}
#   ./install-zcode.sh --regenerate            # refresh the generated tree from canonical here
#
# DEPLOY LAYOUT (scope-dependent):
#   - PROJECT (--target/$PWD): agents and commands land under <project>/.zcode/{agents,commands},
#     the edition's hook shells + script launchers under <project>/.zcode/kaola-workflow/,
#     and the hook mapping merges into <project>/.zcode/config.json. The agent roster is
#     ALSO synced to ${ZCODE_HOME:-~/.zcode}/agents/ (ZCode discovers subagents only at
#     user scope).
#   - GLOBAL (--global): agents and commands land DIRECTLY under
#     ${ZCODE_HOME:-$HOME/.zcode}/{agents,commands} with no nested .zcode/ under the
#     ZCode home, and the hook mapping merges into ${ZCODE_HOME:-$HOME/.zcode}/config.json.
#   - Support scripts (the real ones, from the install manifest) ALWAYS land under
#     ${ZCODE_HOME:-$HOME/.zcode}/kaola-workflow/{scripts,hooks}. Skip with --no-scripts.
#
# Models: generated agents pin model GLM-5.3 plus a canonical-tier thoughtLevel
# (standard high, reasoning max, heavy max) in frontmatter; this installer seeds no
# user-specific per-role model or effort config.

set -euo pipefail

KW_TMPDIR="${TMPDIR:-/tmp}"
case "$KW_TMPDIR" in
  /*) ;;
  *) KW_TMPDIR="/tmp" ;;
esac

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
TARGET=""
GLOBAL=0
REGENERATE=0
UNINSTALL=0
YES=0
NO_SCRIPTS=0
FORGE="github"

usage() {
  cat <<'EOF'
Usage: ./install-zcode.sh [--target DIR] [--forge=github|gitlab|gitea] [--global]
                         [--regenerate] [--uninstall] [--no-scripts] [--yes]
  --target DIR     deploy agents+commands into DIR/.zcode (default: current directory)
  --forge F        github (default), gitlab, or gitea — which forge's workflow prose
                   and support scripts to deploy
  --global         deploy agents+commands into ${ZCODE_HOME:-~/.zcode} (all projects)
  --regenerate     refresh the in-repo generated zcode tree from canonical, then exit
  --uninstall      remove the kaola-deployed zcode edition from the resolved scope
                   (honors --target/--global), then exit
  --no-scripts     skip support scripts, hook shells, and the kaola-workflow tree copy
  --yes            non-interactive (skip the confirmation prompt)

SUPPORT SCRIPTS + HOOKS: workflow commands resolve support scripts via
${ZCODE_HOME:-$HOME/.zcode}/kaola-workflow/scripts (the list comes from
scripts/kaola-workflow-install-manifest.js); hook shells land in the live
.zcode/kaola-workflow/hooks (or ~/.zcode/kaola-workflow/hooks) and are wired by a
merged .zcode/config.json whose top-level hooks object requires "enabled": true.

USER-SCOPE AGENTS: ZCode discovers subagents only at user scope (~/.zcode/agents),
so every project install also syncs the staged .zcode/agents/ roster there.

UNINSTALL: --uninstall removes ONLY kaola-deployed artifacts from the resolved
scope: the deployed agents and commands (by source-tree filename, both the staged
<project>/.zcode/agents copies and the ~/.zcode/agents sync), the support scripts
and hook shells, the .zcode/kaola-workflow tree, and kaola entries in config.json
(other hook entries and foreign config keys stay).
EOF
}

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    --target) TARGET="${2:?--target requires a directory}"; shift 2 ;;
    --forge=*) FORGE="${1#--forge=}"; shift ;;
    --forge) FORGE="${2:?--forge requires github, gitlab, or gitea}"; shift 2 ;;
    --global) GLOBAL=1; shift ;;
    --regenerate) REGENERATE=1; shift ;;
    --uninstall) UNINSTALL=1; shift ;;
    --no-scripts) NO_SCRIPTS=1; shift ;;
    -y|--yes) YES=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

zcode_home() { printf '%s\n' "${ZCODE_HOME:-$HOME/.zcode}"; }

# Validate the forge BEFORE anything is written: an unknown forge refuses with
# exit 2 and leaves the target untouched.
FORGE_HELPER="$SCRIPT_DIR/scripts/runtime-edition-forge.js"
if [[ ! -f "$FORGE_HELPER" ]]; then
  echo "Install error: forge layout helper missing: $FORGE_HELPER" >&2
  exit 1
fi
if ! FORGE_SUFFIX="$(node "$FORGE_HELPER" --forge="$FORGE" --out-suffix)"; then
  echo "Install error: unknown forge \"$FORGE\" (expected github, gitlab, or gitea)" >&2
  exit 2
fi
if ! FORGE_SCRIPTS_DIR="$(node "$FORGE_HELPER" --forge="$FORGE" --scripts-dir)"; then
  echo "Install error: cannot resolve the support-script dir for forge $FORGE" >&2
  exit 1
fi
SYNC_JS="$SCRIPT_DIR/scripts/sync-zcode-edition.js"
if ! TREE_ROOT="$(node "$SYNC_JS" --print-tree-root)"; then
  echo "Install error: cannot resolve where the generated zcode tree lands" >&2
  exit 1
fi
SOURCE_TREE="$TREE_ROOT/.zcode$FORGE_SUFFIX"

if [[ "$UNINSTALL" -ne 1 ]]; then
  echo "Kaola-Workflow · zcode edition ($FORGE) — refreshing generated tree..."
  node "$SYNC_JS" --forge="$FORGE" --check >/dev/null 2>&1 \
    || node "$SYNC_JS" --forge="$FORGE" --write >/dev/null
fi

if [[ "$REGENERATE" -eq 1 ]]; then
  echo "Regenerated $SOURCE_TREE from canonical. Done."
  exit 0
fi

# Names here are removed on install and uninstall by basename.
RETIRED_AGENTS=()
RETIRED_COMMANDS=()
RETIRED_HOOKS=(kaola-workflow-subagent-dispatch-log.sh)
RETIRED_SUPPORT_SCRIPTS=()

WORKFLOW_COMMANDS=(
  kaola-workflow-finalize workflow-init workflow-next
)
in_array() { local needle="$1"; shift; local x; for x in "$@"; do [[ "$x" == "$needle" ]] && return 0; done; return 1; }

is_plain_basename() {
  local n="${1-}"
  [[ -n "$n" ]] || return 1
  case "$n" in
    */*|*\\*|.|..) return 1 ;;
  esac
  return 0
}

copy_agents() {
  local dest="$1"
  mkdir -p "$dest"
  if [[ "$SOURCE_TREE/agents" -ef "$dest" ]]; then
    echo "Self-dev deploy (source $SOURCE_TREE/agents is already the live tree) → copy skipped."
    return
  fi
  local retired
  for retired in "${RETIRED_AGENTS[@]+"${RETIRED_AGENTS[@]}"}"; do
    [[ -f "$dest/$retired.md" ]] || continue
    rm -f "$dest/$retired.md"
  done
  local src base count=0
  for src in "$SOURCE_TREE/agents/"*.md; do
    [[ -f "$src" ]] || continue
    base="$(basename "$src")"
    cp "$src" "$dest/$base"
    count=$((count + 1))
  done
  if [[ "$count" -eq 0 ]]; then
    echo "Install error: no agent sources found in $SOURCE_TREE/agents" >&2
    exit 1
  fi
  echo "Installed workflow agents → $dest/ ($count)"
}

copy_commands() {
  local dest="$1"
  mkdir -p "$dest"
  if [[ "$SOURCE_TREE/commands" -ef "$dest" ]]; then
    echo "Self-dev deploy (source $SOURCE_TREE/commands is already the live tree) → copy skipped."
    return
  fi
  local retired
  for retired in "${RETIRED_COMMANDS[@]+"${RETIRED_COMMANDS[@]}"}"; do
    [[ -f "$dest/$retired.md" ]] || continue
    rm -f "$dest/$retired.md"
  done
  local src base count=0 skipped=0
  for src in "$SOURCE_TREE/commands/"*.md; do
    [[ -f "$src" ]] || continue
    base="$(basename "$src" .md)"
    if ! in_array "$base" "${WORKFLOW_COMMANDS[@]}"; then
      echo "warning: skipping unrecognized command not in the workflow set: $base" >&2
      skipped=$((skipped + 1))
      continue
    fi
    cp "$src" "$dest/$base.md"
    count=$((count + 1))
  done
  if [[ "$count" -eq 0 ]]; then
    if [[ "$skipped" -gt 0 ]]; then
      echo "Install error: all $skipped command source(s) in $SOURCE_TREE/commands fall outside the workflow set" >&2
    else
      echo "Install error: no command sources found in $SOURCE_TREE/commands" >&2
    fi
    exit 1
  fi
  echo "Installed workflow commands → $dest/"
}

# ZCode discovers subagents only at user scope, so a project install syncs the
# staged roster to ${ZCODE_HOME:-~/.zcode}/agents as well.
sync_agents_to_user_scope() {
  local home; home="$(zcode_home)"
  copy_agents "$home/agents"
  echo "Synced agent roster to user scope → $home/agents (ZCode reads agents from user scope only)"
}

install_support_scripts() {
  if [[ "$NO_SCRIPTS" -eq 1 ]]; then
    echo "Support scripts skipped (--no-scripts)."
    return
  fi
  local home; home="$(zcode_home)"
  local manifest="$SCRIPT_DIR/scripts/kaola-workflow-install-manifest.js"
  [[ -f "$manifest" ]] || { echo "warning: install manifest not found; skipping support scripts." >&2; return; }
  local dest="$home/kaola-workflow/scripts"
  mkdir -p "$dest"
  local name src
  local deployed=()
  while IFS= read -r name || [[ -n "$name" ]]; do
    [[ -n "$name" ]] || continue
    src="$FORGE_SCRIPTS_DIR/$name"
    [[ -f "$src" ]] || src="$SCRIPT_DIR/scripts/$name"
    if [[ ! -f "$src" ]]; then
      echo "Install error: allowlisted support script missing from source for forge $FORGE: $name" >&2
      exit 1
    fi
    cp "$src" "$dest/$name"
    chmod +x "$dest/$name"
    deployed+=("$name")
  done < <(node "$manifest" --forge="$FORGE" --scripts 2>/dev/null)
  if [[ ${#deployed[@]} -gt 0 ]]; then
    local stale_file stale_name is_current
    for stale_file in "$dest"/*.js; do
      [[ -f "$stale_file" ]] || continue
      stale_name="$(basename "$stale_file")"
      is_current=0
      for name in "${deployed[@]}"; do
        [[ "$name" == "$stale_name" ]] && is_current=1 && break
      done
      if [[ "$is_current" -eq 0 ]]; then
        rm -f "$stale_file"
        echo "Removed stale script: $stale_file"
      fi
    done
  fi
  echo "Installed support scripts → $dest (forge $FORGE)"
  local hooks_dest="$home/kaola-workflow/hooks"
  mkdir -p "$hooks_dest"
  local retired hook hook_base
  for retired in "${RETIRED_HOOKS[@]+"${RETIRED_HOOKS[@]}"}"; do
    [[ -f "$hooks_dest/$retired" ]] || continue
    rm -f "$hooks_dest/$retired"
    echo "Removed retired hook shell: $hooks_dest/$retired"
  done
  for hook in "$SOURCE_TREE/kaola-workflow/hooks/"*.sh; do
    [[ -f "$hook" ]] || continue
    hook_base="$(basename "$hook")"
    cp "$hook" "$hooks_dest/$hook_base"
    chmod 755 "$hooks_dest/$hook_base"
  done
  echo "Installed hook shells → $hooks_dest"
}

# Copy the generated edition dir (hook shells + script launchers) into the project
# .zcode/kaola-workflow so the merged config.json's hook paths resolve there.
install_edition_dir() {
  if [[ "$NO_SCRIPTS" -eq 1 ]]; then
    return
  fi
  local dest="$LAYOUT_DEST/kaola-workflow"
  mkdir -p "$dest/hooks" "$dest/scripts"
  local f
  for f in "$SOURCE_TREE/kaola-workflow/hooks/"*.sh; do
    [[ -f "$f" ]] || continue
    cp "$f" "$dest/hooks/$(basename "$f")"
    chmod 755 "$dest/hooks/$(basename "$f")"
  done
  for f in "$SOURCE_TREE/kaola-workflow/scripts/"*.js; do
    [[ -f "$f" ]] || continue
    cp "$f" "$dest/scripts/$(basename "$f")"
    chmod 755 "$dest/scripts/$(basename "$f")"
  done
  echo "Installed edition hooks + script launchers → $dest"
}

merge_config() {
  local dest_json="$LAYOUT_DEST/config.json"
  local merge_args=(--merge-hooks "--dest=$dest_json" "--forge=$FORGE")
  if [[ "$GLOBAL" -eq 1 ]]; then
    merge_args+=(--global)
  fi
  if ! node "$SYNC_JS" "${merge_args[@]}"; then
    echo "Install error: failed to merge $dest_json" >&2
    exit 1
  fi
  echo "Merged hook mapping → $dest_json"
}

uninstall_edition() {
  local home layout
  home="$(zcode_home)"
  if [[ "$GLOBAL" -eq 1 ]]; then
    layout="$home"
  else
    layout="${TARGET:-$PWD}/.zcode"
  fi
  echo "Uninstalling Kaola-Workflow · zcode edition ($FORGE) from → $layout"
  if [[ -d "$layout" && "$SOURCE_TREE" -ef "$layout" ]]; then
    echo "Refusing to uninstall the edition's OWN source tree ($layout). No-op." >&2
    return
  fi
  local f retired
  # Kaola-deployed agent names, from the generated source tree.
  if [[ -d "$SOURCE_TREE/agents" ]]; then
    for f in "$SOURCE_TREE/agents/"*.md; do
      [[ -f "$f" ]] || continue
      # staged copies (project scope) ...
      [[ -d "$layout/agents" ]] && rm -f "$layout/agents/$(basename "$f")"
      # ... and the user-scope sync (ZCode discovery).
      [[ -d "$home/agents" ]] && rm -f "$home/agents/$(basename "$f")"
    done
  fi
  for retired in "${RETIRED_AGENTS[@]+"${RETIRED_AGENTS[@]}"}"; do
    [[ -f "$layout/agents/$retired.md" ]] || continue
    rm -f "$layout/agents/$retired.md"
  done
  if [[ -d "$SOURCE_TREE/commands" && -d "$layout/commands" ]]; then
    for f in "$SOURCE_TREE/commands/"*.md; do
      [[ -f "$f" ]] || continue
      rm -f "$layout/commands/$(basename "$f")"
    done
  fi
  for retired in "${RETIRED_COMMANDS[@]+"${RETIRED_COMMANDS[@]}"}"; do
    [[ -f "$layout/commands/$retired.md" ]] || continue
    rm -f "$layout/commands/$retired.md"
  done
  # The kaola-workflow edition dir under the project layout.
  if [[ -d "$layout/kaola-workflow" ]]; then
    if [[ -d "$SOURCE_TREE/kaola-workflow/hooks" ]]; then
      for f in "$SOURCE_TREE/kaola-workflow/hooks/"*.sh; do
        [[ -f "$f" ]] || continue
        rm -f "$layout/kaola-workflow/hooks/$(basename "$f")"
      done
    fi
    for retired in "${RETIRED_HOOKS[@]+"${RETIRED_HOOKS[@]}"}"; do
      [[ -f "$layout/kaola-workflow/hooks/$retired" ]] || continue
      rm -f "$layout/kaola-workflow/hooks/$retired"
    done
    if [[ -d "$SOURCE_TREE/kaola-workflow/scripts" ]]; then
      for f in "$SOURCE_TREE/kaola-workflow/scripts/"*.js; do
        [[ -f "$f" ]] || continue
        rm -f "$layout/kaola-workflow/scripts/$(basename "$f")"
      done
    fi
  fi
  if [[ -f "$layout/config.json" ]]; then
    node "$SYNC_JS" --strip-hooks "--dest=$layout/config.json" "--forge=$FORGE" || true
  fi
  rmdir "$layout/kaola-workflow/hooks" 2>/dev/null || true
  rmdir "$layout/kaola-workflow/scripts" 2>/dev/null || true
  rmdir "$layout/kaola-workflow" 2>/dev/null || true
  rmdir "$layout/agents" 2>/dev/null || true
  rmdir "$layout/commands" 2>/dev/null || true
  if [[ "$GLOBAL" -ne 1 ]]; then rmdir "$layout" 2>/dev/null || true; fi
  echo "Removed deployed agents + commands (staged and user-scope) and the edition dir."
  local scripts_dir="$home/kaola-workflow/scripts"
  local hooks_dir="$home/kaola-workflow/hooks"
  local manifest="$SCRIPT_DIR/scripts/kaola-workflow-install-manifest.js"
  if [[ -f "$manifest" && -d "$scripts_dir" ]]; then
    local name
    while IFS= read -r name || [[ -n "$name" ]]; do
      [[ -n "$name" ]] || continue
      if ! is_plain_basename "$name"; then
        echo "warning: ignoring support-script manifest entry that is not a plain file name: $name" >&2
        continue
      fi
      rm -f "$scripts_dir/$name"
    done < <(node "$manifest" --forge="$FORGE" --scripts 2>/dev/null)
  fi
  if [[ -d "$hooks_dir" && -d "$SOURCE_TREE/kaola-workflow/hooks" ]]; then
    local hook
    for hook in "$SOURCE_TREE/kaola-workflow/hooks/"*.sh; do
      [[ -f "$hook" ]] || continue
      rm -f "$hooks_dir/$(basename "$hook")"
    done
  fi
  if [[ -d "$hooks_dir" ]]; then
    local retired_hook
    for retired_hook in "${RETIRED_HOOKS[@]+"${RETIRED_HOOKS[@]}"}"; do
      [[ -f "$hooks_dir/$retired_hook" ]] || continue
      rm -f "$hooks_dir/$retired_hook"
    done
  fi
  rmdir "$scripts_dir" 2>/dev/null || true
  rmdir "$hooks_dir" 2>/dev/null || true
  rmdir "$home/kaola-workflow" 2>/dev/null || true
  echo "Removed deployed support scripts + hook shells; stripped kaola entries from config.json."
  echo "Uninstall complete. A fresh ./install-zcode.sh now deploys the workflow edition."
}

confirm_install() {
  if [[ "$YES" -eq 1 ]]; then return 0; fi
  if [[ ! -t 0 ]]; then return 0; fi
  cat <<EOF
About to install the Kaola-Workflow zcode edition:
  agents + commands   → $LAYOUT_DEST (+ agent roster synced to $(zcode_home)/agents)
  support scripts     → $(zcode_home)/kaola-workflow/scripts
  hook mapping        → $LAYOUT_DEST/config.json (merged; other entries kept)
EOF
  local reply=""
  read -r -p "Proceed? [Y/n] " reply || reply="n"
  case "$reply" in
    n|N|no|No|NO) echo "Aborted."; exit 0 ;;
  esac
}

if [[ "$UNINSTALL" -eq 1 ]]; then
  uninstall_edition
  exit 0
fi

if [[ "$GLOBAL" -eq 1 ]]; then
  DEST_ROOT="$(zcode_home)"
  LAYOUT_DEST="$DEST_ROOT"
  echo "Deploying globally ($FORGE) → $DEST_ROOT"
else
  DEST_ROOT="${TARGET:-$PWD}"
  LAYOUT_DEST="$DEST_ROOT/.zcode"
  echo "Deploying into project ($FORGE) → $DEST_ROOT"
fi

confirm_install
copy_agents "$LAYOUT_DEST/agents"
copy_commands "$LAYOUT_DEST/commands"
sync_agents_to_user_scope
# The edition dir and the support-script home can alias (globally or when a
# project sets ZCODE_HOME to its .zcode directory), so real manifest scripts
# must always be the final copy. Hooks are safe to refresh in either location.
install_edition_dir
install_support_scripts
merge_config

echo ""
echo "Next: open the project in ZCode and run a workflow command, e.g.:"
echo "  /workflow-init"
