#!/usr/bin/env bash
# install-devin.sh — deploy the Kaola-Workflow Devin CLI edition.
#
# Devin is a coding-agent RUNTIME, not a git forge. It is delivered the Devin-native
# way: named agent profiles, skills, and one UserPromptSubmit lifecycle hook that
# reloads the global contract after compaction drops rules.
#
# FORGE: --forge=github|gitlab|gitea selects which forge's workflow prose and
# support scripts to deploy (default github). The forge variants are GENERATED by
# sync-devin-edition.js from the same routing surfaces the other editions ship.
#
# Usage:
#   ./install-devin.sh                         # global install into ~/.config/devin
#   ./install-devin.sh --global                # same as above
#   ./install-devin.sh --project[=DIR]         # project profiles under DIR/.devin
#   ./install-devin.sh --check                 # verify installed artifacts
#   ./install-devin.sh --forge=gitlab          # deploy GitLab-shaped workflow prose
#
# Global layout:
#   ~/.config/devin/agents/<role>.md
#   ~/.config/devin/skills/<name>/SKILL.md
#   ~/.config/devin/AGENTS.md   (managed global contract, via kaola-workflow-global-contract.js —
#                                the machine-wide transaction shared with install-all.sh; it
#                                refreshes every detected runtime's carrier, not only Devin's)
#   ~/.config/devin/config.json (one Kaola UserPromptSubmit hook)
#
# DEVIN_CONFIG_DIR relocates this install for hermetic tests only. Devin itself does not read
# it; Devin resolves its user config directory from XDG_CONFIG_HOME (or %APPDATA%\devin).
#
# Project layout:
#   <DIR>/.devin/agents/<role>.md
#   <DIR>/.devin/skills/<name>/SKILL.md
#   plus the global recovery carrier above in ~/.config/devin.

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
FORGE="github"
GLOBAL=1
TARGET=""
CHECK=0
YES=0

usage() {
  cat <<'EOF'
Usage: ./install-devin.sh [--global] [--project[=DIR]] [--forge=github|gitlab|gitea] [--check] [-y|--yes]
  --global          install global profiles/skills into ~/.config/devin (default)
  --project[=DIR]   install project profiles/skills into DIR/.devin (default: CWD)
  --forge F         github (default), gitlab, or gitea
  --check           verify installed artifacts without mutating
  -y, --yes         non-interactive (ignored; accepted for install-all compatibility)
  -h, --help        show this help
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --forge=*) FORGE="${1#*=}"; shift ;;
    --forge) FORGE="${2:?--forge requires github, gitlab, or gitea}"; shift 2 ;;
    --global) GLOBAL=1; shift ;;
    --project) GLOBAL=0; TARGET="$PWD"; shift ;;
    --project=*) GLOBAL=0; TARGET="${1#*=}"; shift ;;
    --target) GLOBAL=0; TARGET="${2:?--target requires a directory}"; shift 2 ;;
    --check) CHECK=1; shift ;;
    -y|--yes) YES=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

HOME_ROOT="${DEVIN_CONFIG_DIR:-${HOME:?}/.config/devin}"

STAGE="$(mktemp -d "${TMPDIR:-/tmp}/kw-devin-install.XXXXXX")"
cleanup() { rm -rf "$STAGE"; }
trap cleanup EXIT

echo "Kaola-Workflow · devin edition ($FORGE) — staging generated artifacts..."
node "$SCRIPT_DIR/scripts/sync-devin-edition.js" --forge="$FORGE" --tree-root="$STAGE" --write

FORGE_HELPER="$SCRIPT_DIR/scripts/runtime-edition-forge.js"
if [[ ! -f "$FORGE_HELPER" ]]; then
  echo "Install error: forge layout helper missing: $FORGE_HELPER" >&2
  exit 1
fi
if ! FORGE_SUFFIX="$(node "$FORGE_HELPER" --forge="$FORGE" --out-suffix)"; then
  echo "Install error: unknown forge \"$FORGE\" (expected github, gitlab, or gitea)" >&2
  exit 2
fi
if ! FORGE_SCRIPTS_DIR="$(node "$FORGE_HELPER" --forge="$FORGE" --scripts-dir)"; then
  echo "Install error: cannot resolve the support-script dir for forge $FORGE" >&2
  exit 1
fi

SOURCE_TREE="$STAGE/.devin$FORGE_SUFFIX"
SUPPORT_DEST="$HOME_ROOT/kaola-workflow/scripts"
SUPPORT_MANIFEST=()
while IFS= read -r line; do [[ -n "$line" ]] && SUPPORT_MANIFEST+=("$line"); done \
  < <(node "$SCRIPT_DIR/scripts/kaola-workflow-install-manifest.js" --forge="$FORGE" --scripts)

if [[ "$GLOBAL" == 1 ]]; then
  AGENTS_DEST="$HOME_ROOT/agents"
  SKILLS_DEST="$HOME_ROOT/skills"
else
  PROJECT_DIR="${TARGET:-$PWD}"
  AGENTS_DEST="$PROJECT_DIR/.devin/agents"
  SKILLS_DEST="$PROJECT_DIR/.devin/skills"
fi

# The exact additionalContext text used by the UserPromptSubmit hook.
UPS_TEXT="Kaola-Workflow: if KW-COMPACT-RECOVERY-V2 is not in your context, read $HOME_ROOT/AGENTS.md and the active kaola-workflow/*/workflow-state.md and mission-list.md before acting."
# Marker that lets us identify and replace only the Kaola-owned hook entry.
HOOK_MARKER='# kaola-workflow-userpromptsubmit-hook'

# Print the shell command a Devin UserPromptSubmit hook should run.
ups_command() {
  printf "node -e 'console.log(JSON.stringify({hookSpecificOutput:{hookEventName:%s,additionalContext:%s}}))' %s\n" \
    '"UserPromptSubmit"' \
    '"'"${UPS_TEXT}"'"' \
    "$HOOK_MARKER"
}

# Install or refresh the managed global AGENTS.md carrier through the shared
# global-contract CLI, which follows the same receipt/ownership rules as the
# other runtimes. That CLI is one machine-wide transaction: it refreshes the
# carrier of every runtime it detects on this machine, not only Devin.
# Both modes report the devin-local target instead of discarding the CLI exit code.
global_contract() {
  local mode="$1" output rc=0
  output="$(node "$SCRIPT_DIR/scripts/kaola-workflow-global-contract.js" "$mode" --json 2>&1)" || rc=$?
  node - "$mode" "$rc" "$HOME_ROOT/AGENTS.md" "$output" <<'NODE'
const [mode, rcText, carrierPath, output] = process.argv.slice(2);
const rc = Number(rcText);
let doc = null;
try { doc = JSON.parse(output); } catch (_) { /* non-JSON output is reported verbatim below */ }
const target = doc && Array.isArray(doc.targets) ? doc.targets.find(t => t.id === 'devin-local') : null;
const overall = doc && doc.status ? doc.status : 'UNKNOWN';
const devin = target ? target.status : 'ABSENT';
if (rc === 0) process.exit(0);
console.error(`${mode}: global contract ${overall} (exit ${rc}); devin-local carrier ${devin} at ${carrierPath}`);
if (!doc) console.error(output);
else if (doc.error) console.error(`${mode}: ${doc.error}`);
if (mode === 'check') console.error('check: run ./install-all.sh --yes (or ./install-devin.sh) to refresh the machine-global contract');
process.exit(1);
NODE
}

install_global_carrier() { global_contract install; }
check_global_carrier() { global_contract check; }

# Manage the single Kaola UserPromptSubmit hook in Devin config.json.
# Existing non-Kaola entries are preserved; any prior Kaola entry is replaced.
manage_config_hook() {
  local config_file="$1" mode="$2"
  local cmd
  cmd="$(ups_command)"
  node - "$config_file" "$mode" "$HOOK_MARKER" "$cmd" <<'NODE'
const fs = require('fs'), path = require('path');
const file = process.argv[2];
const mode = process.argv[3];
const marker = process.argv[4];
const command = process.argv[5];
let config = {};
try { config = JSON.parse(fs.readFileSync(file, 'utf8')); }
catch (e) { if (e.code !== 'ENOENT') throw e; }
if (!config.hooks || typeof config.hooks !== 'object' || Array.isArray(config.hooks)) config.hooks = {};
const ups = Array.isArray(config.hooks.UserPromptSubmit) ? config.hooks.UserPromptSubmit.slice() : [];
const kaola = ups.filter(entry => {
  const hooks = Array.isArray(entry && entry.hooks) ? entry.hooks : [];
  return hooks.some(h => h && typeof h.command === 'string' && h.command.includes(marker));
});
if (mode === 'check') {
  if (kaola.length !== 1) {
    console.error('check: expected exactly one Kaola UserPromptSubmit hook, found ' + kaola.length);
    process.exit(1);
  }
  const entry = kaola[0];
  if (entry.matcher !== '' && entry.matcher !== undefined) {
    console.error('check: Kaola UserPromptSubmit matcher must be empty/missing');
    process.exit(1);
  }
  const hook = entry.hooks[0];
  if (!hook || hook.type !== 'command' || !hook.command.includes('hookEventName')) {
    console.error('check: Kaola UserPromptSubmit hook is malformed');
    process.exit(1);
  }
  process.exit(0);
}
// install mode: remove old Kaola entries, append fresh one, preserve everything else.
const kept = ups.filter(entry => !kaola.some(k => k === entry));
kept.push({ matcher: '', hooks: [{ type: 'command', command }] });
config.hooks.UserPromptSubmit = kept;
fs.mkdirSync(path.dirname(file), { recursive: true });
fs.writeFileSync(file, JSON.stringify(config, null, 2) + '\n');
NODE
}

# Install the forge-selected support scripts into the Devin-native helper root.
install_support_scripts() {
  mkdir -p "$SUPPORT_DEST"
  local src name
  for name in "${SUPPORT_MANIFEST[@]}"; do
    src="$FORGE_SCRIPTS_DIR/$name"
    [[ -f "$src" ]] || { echo "Install error: support script missing: $src" >&2; exit 1; }
    cp "$src" "$SUPPORT_DEST/$name"
  done
}

# Verify installed support scripts match the canonical source.
check_support_scripts() {
  local bad=0 src name
  if [[ ! -d "$SUPPORT_DEST" ]]; then
    echo "check: missing $SUPPORT_DEST" >&2; return 1
  fi
  for name in "${SUPPORT_MANIFEST[@]}"; do
    src="$FORGE_SCRIPTS_DIR/$name"
    if [[ ! -f "$SUPPORT_DEST/$name" ]]; then
      echo "check: missing support script $name" >&2; bad=1
    elif ! diff -q "$src" "$SUPPORT_DEST/$name" >/dev/null 2>&1; then
      echo "check: support script $name drifted from canonical" >&2; bad=1
    fi
  done
  return "$bad"
}

# Verify that the staged .devin/{agents,skills} tree matches the destination.
check_artifacts() {
  local src_agents="$SOURCE_TREE/agents" src_skills="$SOURCE_TREE/skills"
  local bad=0
  if [[ ! -d "$AGENTS_DEST" ]]; then
    echo "check: missing $AGENTS_DEST" >&2; bad=1
  elif ! diff -qr "$src_agents" "$AGENTS_DEST" >/dev/null 2>&1; then
    echo "check: agents do not match rendered source" >&2; bad=1
  fi
  if [[ ! -d "$SKILLS_DEST" ]]; then
    echo "check: missing $SKILLS_DEST" >&2; bad=1
  elif ! diff -qr "$src_skills" "$SKILLS_DEST" >/dev/null 2>&1; then
    echo "check: skills do not match rendered source" >&2; bad=1
  fi
  return "$bad"
}

# When `devin doctor --json` is available, assert all 14 Kaola role names appear.
check_doctor() {
  if ! command -v devin >/dev/null 2>&1; then
    echo "check: devin binary not found, skipping devin doctor"
    return 0
  fi
  local out="$STAGE/doctor.json"
  devin doctor --json > "$out" 2>/dev/null || true
  node - "$out" <<'NODE'
const fs = require('fs');
const file = process.argv[2];
let doc = {};
try { doc = JSON.parse(fs.readFileSync(file, 'utf8')); } catch (e) { /* ignore */ }
const roles = [
  'adversarial-verifier','build-error-resolver','code-architect','code-explorer','code-reviewer',
  'doc-updater','implementer','investigator','knowledge-lookup','metric-optimizer','planner',
  'security-reviewer','synthesizer','tdd-guide'
];
const text = JSON.stringify(doc);
const missing = roles.filter(r => !text.includes(r));
if (missing.length) {
  console.error('check: devin doctor missing Kaola roles: ' + missing.join(', '));
  process.exit(1);
}
NODE
}

if [[ "$CHECK" == 1 ]]; then
  check_global_carrier
  check_doctor
  manage_config_hook "$HOME_ROOT/config.json" check
  check_support_scripts || exit 1
  check_artifacts || exit 1
  echo "Devin edition check passed."
  exit 0
fi

install_global_carrier
manage_config_hook "$HOME_ROOT/config.json" install
install_support_scripts

mkdir -p "$AGENTS_DEST" "$SKILLS_DEST"
if [[ -d "$SOURCE_TREE/agents" ]]; then
  cp "$SOURCE_TREE/agents/"*.md "$AGENTS_DEST/"
fi
if [[ -d "$SOURCE_TREE/skills" ]]; then
  for src in "$SOURCE_TREE/skills/"*; do
    [[ -d "$src" ]] || continue
    name="$(basename "$src")"
    mkdir -p "$SKILLS_DEST/$name"
    cp "$src/SKILL.md" "$SKILLS_DEST/$name/SKILL.md"
  done
fi

echo "Installed Devin edition ($FORGE) — agents: $AGENTS_DEST, skills: $SKILLS_DEST, support scripts: $SUPPORT_DEST, global carrier: $HOME_ROOT/AGENTS.md"
