#!/usr/bin/env bash
# install-cursor.sh — deploy the Kaola-Workflow cursor edition into a project (or globally).
#
# Additive standalone installer (does NOT modify install.sh, install-opencode.sh,
# install-kimi.sh, or the claude/codex/gitlab/gitea editions). Cursor is a runtime
# (like opencode, Kimi, and Grok), not a git forge, so it is delivered the Cursor-native way:
# named agents under .cursor/agents/, flat slash commands under .cursor/commands/, hook
# scripts under .cursor/hooks/, and a merged .cursor/hooks.json.
#
# FORGE: --forge=github|gitlab|gitea selects which forge's workflow prose and support
# scripts to deploy (default github). The forge variants are GENERATED by
# sync-cursor-edition.js from the same routing surfaces the other editions ship;
# github renders .cursor/, a forge renders .cursor-<forge>/.
#
# Usage:
#   ./install-cursor.sh                         # deploy into the current directory
#   ./install-cursor.sh --target /path/to/repo  # deploy into a specific project
#   ./install-cursor.sh --forge=gitlab          # deploy the GitLab-shaped edition
#   ./install-cursor.sh --global                # deploy agents+commands to ${CURSOR_HOME:-~/.cursor}
#   ./install-cursor.sh --regenerate            # refresh the generated tree from canonical here
#
# DEPLOY LAYOUT (scope-dependent):
#   - PROJECT (--target/$PWD): agents and commands land under <project>/.cursor/{agents,commands}.
#   - GLOBAL (--global): they land DIRECTLY under ${CURSOR_HOME:-$HOME/.cursor}/{agents,commands}
#     with no nested .cursor/ under CURSOR_HOME. When the installer process cwd is inside a git
#     work tree, the same 14 agents + 3 commands are also written to
#     $(git rev-parse --show-toplevel)/.cursor/{agents,commands} (Task types are workspace-scoped).
#     --global from a directory with no git toplevel does not invent a project .cursor/ tree.
#   - Support scripts ALWAYS land under the Cursor home (user-level):
#     ${CURSOR_HOME:-$HOME/.cursor}/kaola-workflow/{scripts,hooks}.
#   - Project installs merge mapping into <project>/.cursor/hooks.json and copy hook
#     scripts to <project>/.cursor/hooks/. Global installs merge into
#     ${CURSOR_HOME:-$HOME/.cursor}/hooks.json (command paths rewritten to ./hooks/)
#     and copy scripts to ${CURSOR_HOME:-$HOME/.cursor}/hooks/. Existing non-kaola
#     hook entries are preserved. Skip with --no-scripts.
#
# Models: generated agents carry raw per-tier frontmatter pins from the canonical standard/
# reasoning classes; this installer seeds no user-specific per-role model or effort config.

set -euo pipefail

KW_TMPDIR="${TMPDIR:-/tmp}"
case "$KW_TMPDIR" in
  /*) ;;
  *) KW_TMPDIR="/tmp" ;;
esac

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
TARGET=""
GLOBAL=0
REGENERATE=0
UNINSTALL=0
YES=0
NO_SCRIPTS=0
FORGE="github"

usage() {
  cat <<'EOF'
Usage: ./install-cursor.sh [--target DIR] [--forge=github|gitlab|gitea] [--global]
                         [--regenerate] [--uninstall] [--no-scripts] [--yes]
  --target DIR     deploy agents+commands into DIR/.cursor (default: current directory)
  --forge F        github (default), gitlab, or gitea — which forge's workflow prose
                   and support scripts to deploy
  --global         deploy agents+commands into ${CURSOR_HOME:-~/.cursor} (all projects)
  --regenerate     refresh the in-repo .cursor/ tree from canonical, then exit
  --uninstall      remove the kaola-deployed cursor edition from the resolved scope
                   (honors --target/--global), then exit
  --no-scripts     skip support scripts, hook scripts, and the hooks JSON copy
  --yes            non-interactive (skip the confirmation prompt)

SUPPORT SCRIPTS + HOOKS: workflow commands resolve support scripts via
${CURSOR_HOME:-$HOME/.cursor}/kaola-workflow/scripts (the list comes from
scripts/kaola-workflow-install-manifest.js); hook scripts land in the live
.cursor/hooks (or ~/.cursor/hooks when --global) and are wired by a merged
hooks.json. Support-script copies also land under
${CURSOR_HOME:-$HOME/.cursor}/kaola-workflow/{scripts,hooks}.

UNINSTALL: --uninstall removes ONLY kaola-deployed artifacts from the resolved
scope: the deployed agents and commands (by source-tree filename), the support
scripts + hook scripts, and kaola entries in hooks.json (other hook entries stay).
The SHARED ~/.config/kaola-workflow/config.json is kept for any co-installed
Claude/Codex/opencode/kimi/grok edition.
EOF
}

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    --target) TARGET="${2:?--target requires a directory}"; shift 2 ;;
    --forge=*) FORGE="${1#--forge=}"; shift ;;
    --forge) FORGE="${2:?--forge requires github, gitlab, or gitea}"; shift 2 ;;
    --global) GLOBAL=1; shift ;;
    --regenerate) REGENERATE=1; shift ;;
    --uninstall) UNINSTALL=1; shift ;;
    --no-scripts) NO_SCRIPTS=1; shift ;;
    -y|--yes) YES=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

cursor_home() { printf '%s\n' "${CURSOR_HOME:-$HOME/.cursor}"; }

FORGE_HELPER="$SCRIPT_DIR/scripts/runtime-edition-forge.js"
if [[ ! -f "$FORGE_HELPER" ]]; then
  echo "Install error: forge layout helper missing: $FORGE_HELPER" >&2
  exit 1
fi
if ! FORGE_SUFFIX="$(node "$FORGE_HELPER" --forge="$FORGE" --out-suffix)"; then
  echo "Install error: unknown forge \"$FORGE\" (expected github, gitlab, or gitea)" >&2
  exit 2
fi
if ! FORGE_SCRIPTS_DIR="$(node "$FORGE_HELPER" --forge="$FORGE" --scripts-dir)"; then
  echo "Install error: cannot resolve the support-script dir for forge $FORGE" >&2
  exit 1
fi
if ! TREE_ROOT="$(node "$SCRIPT_DIR/scripts/sync-cursor-edition.js" --print-tree-root)"; then
  echo "Install error: cannot resolve where the generated cursor tree lands" >&2
  exit 1
fi
SOURCE_TREE="$TREE_ROOT/.cursor$FORGE_SUFFIX"

if [[ "$UNINSTALL" -ne 1 ]]; then
  echo "Kaola-Workflow · cursor edition ($FORGE) — refreshing generated tree..."
  node "$SCRIPT_DIR/scripts/sync-cursor-edition.js" --forge="$FORGE" --check >/dev/null 2>&1 \
    || node "$SCRIPT_DIR/scripts/sync-cursor-edition.js" --forge="$FORGE" --write >/dev/null
fi

if [[ "$REGENERATE" -eq 1 ]]; then
  echo "Regenerated $SOURCE_TREE from canonical. Done."
  exit 0
fi

# This edition has never shipped a prior command/agent/hook set, so there is nothing
# to retire yet. Names added here are removed on install and uninstall by basename.
RETIRED_AGENTS=()
RETIRED_COMMANDS=()
RETIRED_HOOKS=()
RETIRED_SUPPORT_SCRIPTS=()

WORKFLOW_COMMANDS=(
  kaola-workflow-finalize workflow-init workflow-next
)
in_array() { local needle="$1"; shift; local x; for x in "$@"; do [[ "$x" == "$needle" ]] && return 0; done; return 1; }

is_plain_basename() {
  local n="${1-}"
  [[ -n "$n" ]] || return 1
  case "$n" in
    */*|*\\*|.|..) return 1 ;;
  esac
  return 0
}

remove_retired_support_scripts() {
  local dir="$1"
  [[ -d "$dir" ]] || return 0
  local base name
  for base in "${RETIRED_SUPPORT_SCRIPTS[@]+"${RETIRED_SUPPORT_SCRIPTS[@]}"}"; do
    for name in "$base" \
      "${base/#kaola-workflow-/kaola-gitlab-workflow-}" \
      "${base/#kaola-workflow-/kaola-gitea-workflow-}"; do
      is_plain_basename "$name" || continue
      [[ -f "$dir/$name" ]] || continue
      rm -f "$dir/$name"
      echo "Removed retired support script: $dir/$name"
    done
  done
}

copy_agents() {
  local dest="$1"
  mkdir -p "$dest"
  if [[ "$SOURCE_TREE/agents" -ef "$dest" ]]; then
    echo "Self-dev deploy (source $SOURCE_TREE/agents is already the live tree) → copy skipped."
    return
  fi
  local retired
  for retired in "${RETIRED_AGENTS[@]+"${RETIRED_AGENTS[@]}"}"; do
    [[ -f "$dest/$retired.md" ]] || continue
    rm -f "$dest/$retired.md"
  done
  local src base count=0
  for src in "$SOURCE_TREE/agents/"*.md; do
    [[ -f "$src" ]] || continue
    base="$(basename "$src")"
    cp "$src" "$dest/$base"
    count=$((count + 1))
  done
  if [[ "$count" -eq 0 ]]; then
    echo "Install error: no agent sources found in $SOURCE_TREE/agents" >&2
    exit 1
  fi
  echo "Installed workflow agents → $dest/ ($count)"
}

copy_commands() {
  local dest="$1"
  mkdir -p "$dest"
  if [[ "$SOURCE_TREE/commands" -ef "$dest" ]]; then
    echo "Self-dev deploy (source $SOURCE_TREE/commands is already the live tree) → copy skipped."
    return
  fi
  local retired
  for retired in "${RETIRED_COMMANDS[@]+"${RETIRED_COMMANDS[@]}"}"; do
    [[ -f "$dest/$retired.md" ]] || continue
    rm -f "$dest/$retired.md"
  done
  local src base count=0 skipped=0
  for src in "$SOURCE_TREE/commands/"*.md; do
    [[ -f "$src" ]] || continue
    base="$(basename "$src" .md)"
    if ! in_array "$base" "${WORKFLOW_COMMANDS[@]}"; then
      echo "warning: skipping unrecognized command not in the workflow set: $base" >&2
      skipped=$((skipped + 1))
      continue
    fi
    cp "$src" "$dest/$base.md"
    count=$((count + 1))
  done
  if [[ "$count" -eq 0 ]]; then
    if [[ "$skipped" -gt 0 ]]; then
      echo "Install error: all $skipped command source(s) in $SOURCE_TREE/commands fall outside the workflow set" >&2
    else
      echo "Install error: no command sources found in $SOURCE_TREE/commands" >&2
    fi
    exit 1
  fi
  echo "Installed workflow commands → $dest/"
}

install_support_scripts() {
  if [[ "$NO_SCRIPTS" -eq 1 ]]; then
    echo "Support scripts skipped (--no-scripts)."
    return
  fi
  local home; home="$(cursor_home)"
  local manifest="$SCRIPT_DIR/scripts/kaola-workflow-install-manifest.js"
  [[ -f "$manifest" ]] || { echo "warning: install manifest not found; skipping support scripts." >&2; return; }
  local dest="$home/kaola-workflow/scripts"
  mkdir -p "$dest"
  local name src extra_ensure extra_ensure_src
  local deployed=()
  while IFS= read -r name || [[ -n "$name" ]]; do
    [[ -n "$name" ]] || continue
    src="$FORGE_SCRIPTS_DIR/$name"
    [[ -f "$src" ]] || src="$SCRIPT_DIR/scripts/$name"
    if [[ ! -f "$src" ]]; then
      echo "Install error: allowlisted support script missing from source for forge $FORGE: $name" >&2
      exit 1
    fi
    cp "$src" "$dest/$name"
    chmod +x "$dest/$name"
    deployed+=("$name")
  done < <(node "$manifest" --forge="$FORGE" --scripts 2>/dev/null)
  # Cursor-only extra: catalog ensure. Not in the github supportScripts manifest.
  extra_ensure="kaola-workflow-ensure-cursor-catalog.js"
  extra_ensure_src="$SCRIPT_DIR/scripts/$extra_ensure"
  if [[ -f "$extra_ensure_src" ]]; then
    cp "$extra_ensure_src" "$dest/$extra_ensure"
    chmod +x "$dest/$extra_ensure"
    deployed+=("$extra_ensure")
  fi
  if [[ ${#deployed[@]} -gt 0 ]]; then
    local stale_file stale_name is_current
    for stale_file in "$dest"/*.js; do
      [[ -f "$stale_file" ]] || continue
      stale_name="$(basename "$stale_file")"
      is_current=0
      for name in "${deployed[@]}"; do
        [[ "$name" == "$stale_name" ]] && is_current=1 && break
      done
      if [[ "$is_current" -eq 0 ]]; then
        rm -f "$stale_file"
        echo "Removed stale script: $stale_file"
      fi
    done
  fi
  echo "Installed support scripts → $dest (forge $FORGE)"
  local hooks_dest="$home/kaola-workflow/hooks"
  mkdir -p "$hooks_dest"
  local retired
  for retired in "${RETIRED_HOOKS[@]+"${RETIRED_HOOKS[@]}"}"; do
    [[ -f "$hooks_dest/$retired" ]] || continue
    rm -f "$hooks_dest/$retired"
    echo "Removed retired hook script: $hooks_dest/$retired"
  done
  local hook hook_base
  for hook in "$SOURCE_TREE/hooks/"*.sh; do
    [[ -f "$hook" ]] || continue
    hook_base="$(basename "$hook")"
    cp "$hook" "$hooks_dest/$hook_base"
    chmod 755 "$hooks_dest/$hook_base"
  done
  echo "Installed hook scripts → $hooks_dest"
}

install_hooks_json() {
  if [[ "$NO_SCRIPTS" -eq 1 ]]; then
    echo "Hooks JSON skipped (--no-scripts)."
    return
  fi
  local src="$SOURCE_TREE/hooks.json"
  [[ -f "$src" ]] || { echo "Install error: generated hooks.json missing: $src" >&2; exit 1; }
  local dest_hooks="$LAYOUT_DEST/hooks"
  if [[ ! "$SOURCE_TREE/hooks" -ef "$dest_hooks" ]]; then
    mkdir -p "$dest_hooks"
    local retired
    for retired in "${RETIRED_HOOKS[@]+"${RETIRED_HOOKS[@]}"}"; do
      [[ -f "$dest_hooks/$retired" ]] || continue
      rm -f "$dest_hooks/$retired"
      echo "Removed retired hook script: $dest_hooks/$retired"
    done
    local hook
    for hook in "$SOURCE_TREE/hooks/"*.sh; do
      [[ -f "$hook" ]] || continue
      cp "$hook" "$dest_hooks/$(basename "$hook")"
      chmod 755 "$dest_hooks/$(basename "$hook")"
    done
    echo "Installed hook scripts → $dest_hooks"
  fi
  local dest_json="$LAYOUT_DEST/hooks.json"
  local merge_args=(--merge-hooks "--dest=$dest_json")
  if [[ "$GLOBAL" -eq 1 ]]; then
    merge_args+=(--global)
  fi
  if ! node "$SCRIPT_DIR/scripts/sync-cursor-edition.js" "${merge_args[@]}"; then
    echo "Install error: failed to merge $dest_json" >&2
    exit 1
  fi
  echo "Merged hooks JSON → $dest_json"
}

uninstall_edition() {
  local home layout
  home="$(cursor_home)"
  if [[ "$GLOBAL" -eq 1 ]]; then
    layout="$home"
  else
    layout="${TARGET:-$PWD}/.cursor"
  fi
  echo "Uninstalling Kaola-Workflow · cursor edition ($FORGE) from → $layout"
  if [[ -d "$layout" && "$SOURCE_TREE" -ef "$layout" ]]; then
    echo "Refusing to uninstall the edition's OWN source tree ($layout). No-op." >&2
    return
  fi
  local f
  if [[ -d "$SOURCE_TREE/agents" && -d "$layout/agents" ]]; then
    for f in "$SOURCE_TREE/agents/"*.md; do
      [[ -f "$f" ]] || continue
      rm -f "$layout/agents/$(basename "$f")"
    done
  fi
  local retired
  for retired in "${RETIRED_AGENTS[@]+"${RETIRED_AGENTS[@]}"}"; do
    [[ -f "$layout/agents/$retired.md" ]] || continue
    rm -f "$layout/agents/$retired.md"
  done
  if [[ -d "$SOURCE_TREE/commands" && -d "$layout/commands" ]]; then
    for f in "$SOURCE_TREE/commands/"*.md; do
      [[ -f "$f" ]] || continue
      rm -f "$layout/commands/$(basename "$f")"
    done
  fi
  for retired in "${RETIRED_COMMANDS[@]+"${RETIRED_COMMANDS[@]}"}"; do
    [[ -f "$layout/commands/$retired.md" ]] || continue
    rm -f "$layout/commands/$retired.md"
  done
  if [[ -d "$layout/hooks" ]]; then
    local hook
    for hook in "$SOURCE_TREE/hooks/"*.sh; do
      [[ -f "$hook" ]] || continue
      rm -f "$layout/hooks/$(basename "$hook")"
    done
    for retired in "${RETIRED_HOOKS[@]+"${RETIRED_HOOKS[@]}"}"; do
      [[ -f "$layout/hooks/$retired" ]] || continue
      rm -f "$layout/hooks/$retired"
    done
  fi
  if [[ -f "$layout/hooks.json" ]]; then
    node "$SCRIPT_DIR/scripts/sync-cursor-edition.js" --strip-hooks "--dest=$layout/hooks.json" || true
  fi
  rmdir "$layout/agents" 2>/dev/null || true
  rmdir "$layout/commands" 2>/dev/null || true
  rmdir "$layout/hooks" 2>/dev/null || true
  if [[ "$GLOBAL" -ne 1 ]]; then rmdir "$layout" 2>/dev/null || true; fi
  echo "Removed deployed agents + commands."
  local scripts_dir="$home/kaola-workflow/scripts"
  local hooks_dir="$home/kaola-workflow/hooks"
  local manifest="$SCRIPT_DIR/scripts/kaola-workflow-install-manifest.js"
  if [[ -f "$manifest" && -d "$scripts_dir" ]]; then
    local name
    while IFS= read -r name || [[ -n "$name" ]]; do
      [[ -n "$name" ]] || continue
      if ! is_plain_basename "$name"; then
        echo "warning: ignoring support-script manifest entry that is not a plain file name: $name" >&2
        continue
      fi
      rm -f "$scripts_dir/$name"
    done < <(node "$manifest" --forge="$FORGE" --scripts 2>/dev/null)
  fi
  rm -f "$scripts_dir/kaola-workflow-ensure-cursor-catalog.js"
  remove_retired_support_scripts "$scripts_dir"
  if [[ -d "$hooks_dir" ]]; then
    local hook
    for hook in "$SOURCE_TREE/hooks/"*.sh; do
      [[ -f "$hook" ]] || continue
      rm -f "$hooks_dir/$(basename "$hook")"
    done
    for retired in "${RETIRED_HOOKS[@]+"${RETIRED_HOOKS[@]}"}"; do
      [[ -f "$hooks_dir/$retired" ]] || continue
      rm -f "$hooks_dir/$retired"
    done
  fi
  rmdir "$scripts_dir" 2>/dev/null || true
  rmdir "$hooks_dir" 2>/dev/null || true
  rmdir "$home/kaola-workflow" 2>/dev/null || true
  echo "Removed deployed support scripts + hook scripts; stripped kaola entries from hooks.json."
  echo "Uninstall complete. A fresh ./install-cursor.sh now deploys the workflow edition."
}

confirm_install() {
  if [[ "$YES" -eq 1 ]]; then return 0; fi
  if [[ ! -t 0 ]]; then return 0; fi
  cat <<EOF
About to install the Kaola-Workflow cursor edition:
  agents + commands   → $LAYOUT_DEST
  support scripts     → $(cursor_home)/kaola-workflow/scripts
  hook scripts        → $LAYOUT_DEST/hooks
  hooks JSON          → $LAYOUT_DEST/hooks.json (merged; other entries kept)
EOF
  local reply=""
  read -r -p "Proceed? [Y/n] " reply || reply="n"
  case "$reply" in
    n|N|no|No|NO) echo "Aborted."; exit 0 ;;
  esac
}

if [[ "$UNINSTALL" -eq 1 ]]; then
  uninstall_edition
  exit 0
fi

if [[ "$GLOBAL" -eq 1 ]]; then
  DEST_ROOT="$(cursor_home)"
  LAYOUT_DEST="$DEST_ROOT"
  echo "Deploying globally ($FORGE) → $DEST_ROOT"
else
  DEST_ROOT="${TARGET:-$PWD}"
  LAYOUT_DEST="$DEST_ROOT/.cursor"
  echo "Deploying into project ($FORGE) → $DEST_ROOT"
fi

confirm_install
copy_agents "$LAYOUT_DEST/agents"
copy_commands "$LAYOUT_DEST/commands"
if [[ "$GLOBAL" -eq 1 ]]; then
  git_toplevel="$(git rev-parse --show-toplevel 2>/dev/null || true)"
  if [[ -n "$git_toplevel" ]]; then
    project_layout="$git_toplevel/.cursor"
    if [[ "$project_layout" != "$LAYOUT_DEST" && "$git_toplevel" != "$DEST_ROOT" ]]; then
      echo "Task types are workspace-scoped; also deploying agents+commands → $project_layout"
      copy_agents "$project_layout/agents"
      copy_commands "$project_layout/commands"
    fi
  fi
fi
install_support_scripts
install_hooks_json

echo ""
echo "Next: open the project in Cursor and run a workflow command, e.g.:"
echo "  /workflow-init"
