#!/usr/bin/env bash
# install-cursor.sh — deploy the Kaola-Workflow cursor edition into a project (or globally).
#
# Additive standalone installer (does NOT modify install.sh, install-opencode.sh,
# install-kimi.sh, or the claude/codex/gitlab/gitea editions). Cursor is a runtime
# (like opencode, Kimi, and Grok), not a git forge, so it is delivered the Cursor-native way:
# named agents under .cursor/agents/, flat slash commands under .cursor/commands/, hook
# scripts under .cursor/hooks/, and a merged .cursor/hooks.json.
#
# FORGE: --forge=github|gitlab|gitea selects which forge's workflow prose and support
# scripts to deploy (default github). The forge variants are GENERATED by
# sync-cursor-edition.js from the same routing surfaces the other editions ship;
# github renders .cursor/, a forge renders .cursor-<forge>/.
#
# Usage:
#   ./install-cursor.sh --target /path/to/repo  # deploy into a specific project
#   ./install-cursor.sh --target /repo --forge=gitlab
#   ./install-cursor.sh --global                # deploy agents+commands to ${CURSOR_HOME:-~/.cursor}
#   ./install-cursor.sh --regenerate            # refresh the generated tree from canonical here
#   ./install-cursor.sh --doctor --json         # report surface facts; does not install
#
# DEPLOY LAYOUT (scope-dependent):
#   - PROJECT (--target): agents and commands land under <project>/.cursor/{agents,commands}.
#     The target is mandatory, derives from the receipt-verified global authority, and is never
#     selected from ambient cwd.
#   - GLOBAL (--global): they land DIRECTLY under ${CURSOR_HOME:-$HOME/.cursor}/{agents,commands}
#     with no nested .cursor/ under CURSOR_HOME. Running --global inside a Git work tree does
#     not create or refresh that repository's .cursor/ tree. Project catalogs that already
#     exist are left untouched. --global from a directory with no git toplevel does not invent
#     a project .cursor/ tree.
#   - Support scripts ALWAYS land under the Cursor home (user-level):
#     ${CURSOR_HOME:-$HOME/.cursor}/kaola-workflow/{scripts,hooks}.
#   - Project installs merge mapping into <project>/.cursor/hooks.json and copy hook
#     scripts to <project>/.cursor/hooks/. Global installs merge into
#     ${CURSOR_HOME:-$HOME/.cursor}/hooks.json (command paths rewritten to ./hooks/)
#     and copy scripts to ${CURSOR_HOME:-$HOME/.cursor}/hooks/. Existing non-kaola
#     hook entries are preserved. Skip with --no-scripts.
#
# Models: generated agents carry raw per-tier frontmatter pins from the canonical standard/
# reasoning classes; this installer seeds no user-specific per-role model or effort config.

set -euo pipefail

KW_TMPDIR="${TMPDIR:-/tmp}"
case "$KW_TMPDIR" in
  /*) ;;
  *) KW_TMPDIR="/tmp" ;;
esac

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
TARGET=""
GLOBAL=0
REGENERATE=0
UNINSTALL=0
YES=0
NO_SCRIPTS=0
DOCTOR=0
DOCTOR_JSON=0
DOCTOR_PRODUCT="unknown"
DOCTOR_HOST="unknown"
FORGE="github"

usage() {
  cat <<'EOF'
Usage: ./install-cursor.sh [--target DIR] [--forge=github|gitlab|gitea] [--global]
                         [--regenerate] [--uninstall] [--no-scripts] [--yes]
                         [--doctor] [--json] [--product cli|app] [--host local|cloud]
  --target DIR     explicitly materialize agents+commands into DIR/.cursor
  --forge F        github (default), gitlab, or gitea — which forge's workflow prose
                   and support scripts to deploy
  --global         deploy agents+commands into ${CURSOR_HOME:-~/.cursor} (all projects);
                   does not write the invoking Git repository
  --doctor         report Cursor product/host surface facts and exit (no install)
  --json           with --doctor, emit JSON
  --product S      with --doctor, cli|app|unknown (default unknown; never inferred)
  --host S         with --doctor, local|cloud|unknown (default unknown; never inferred)
  --regenerate     refresh the in-repo .cursor/ tree from canonical, then exit
  --uninstall      remove the kaola-deployed cursor edition from the resolved scope
                   (honors --target/--global), then exit
  --no-scripts     skip support scripts, hook scripts, and the hooks JSON copy
  --yes            non-interactive (skip the confirmation prompt)

SUPPORT SCRIPTS + HOOKS: workflow commands resolve support scripts via
${CURSOR_HOME:-$HOME/.cursor}/kaola-workflow/scripts (the list comes from
scripts/kaola-workflow-install-manifest.js); hook scripts land in the live
.cursor/hooks (or ~/.cursor/hooks when --global) and are wired by a merged
hooks.json. Support-script copies also land under
${CURSOR_HOME:-$HOME/.cursor}/kaola-workflow/{scripts,hooks}.

UNINSTALL: --uninstall removes ONLY receipt-proven, byte-unchanged Kaola artifacts
from the resolved scope. Modified, unmanaged, symlink, and nonregular paths remain;
only receipt-recorded Kaola entries are removed from hooks.json.
The SHARED ~/.config/kaola-workflow/config.json is kept for any co-installed
Claude/Codex/opencode/kimi/grok edition.
EOF
}

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    --target) TARGET="${2:?--target requires a directory}"; shift 2 ;;
    --forge=*) FORGE="${1#--forge=}"; shift ;;
    --forge) FORGE="${2:?--forge requires github, gitlab, or gitea}"; shift 2 ;;
    --global) GLOBAL=1; shift ;;
    --doctor) DOCTOR=1; shift ;;
    --json) DOCTOR_JSON=1; shift ;;
    --product) DOCTOR_PRODUCT="${2:?--product requires cli, app, or unknown}"; shift 2 ;;
    --host) DOCTOR_HOST="${2:?--host requires local, cloud, or unknown}"; shift 2 ;;
    --regenerate) REGENERATE=1; shift ;;
    --uninstall) UNINSTALL=1; shift ;;
    --no-scripts) NO_SCRIPTS=1; shift ;;
    -y|--yes) YES=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

cursor_home() { printf '%s\n' "${CURSOR_HOME:-$HOME/.cursor}"; }

FORGE_HELPER="$SCRIPT_DIR/scripts/runtime-edition-forge.js"
if [[ ! -f "$FORGE_HELPER" ]]; then
  echo "Install error: forge layout helper missing: $FORGE_HELPER" >&2
  exit 1
fi
if ! FORGE_SUFFIX="$(node "$FORGE_HELPER" --forge="$FORGE" --out-suffix)"; then
  echo "Install error: unknown forge \"$FORGE\" (expected github, gitlab, or gitea)" >&2
  exit 2
fi
if ! FORGE_SCRIPTS_DIR="$(node "$FORGE_HELPER" --forge="$FORGE" --scripts-dir)"; then
  echo "Install error: cannot resolve the support-script dir for forge $FORGE" >&2
  exit 1
fi

if [[ "$GLOBAL" -eq 1 && -n "$TARGET" ]]; then
  echo "Install error: --global and --target are mutually exclusive." >&2
  exit 2
fi

if [[ "$DOCTOR" -eq 1 ]]; then
  doctor_args=(--doctor --product "$DOCTOR_PRODUCT" --host "$DOCTOR_HOST" --forge "$FORGE")
  [[ -n "$TARGET" ]] && doctor_args+=(--target "$TARGET")
  [[ "$DOCTOR_JSON" -eq 1 ]] && doctor_args+=(--json)
  exec node "$SCRIPT_DIR/scripts/kaola-workflow-cursor-surface.js" "${doctor_args[@]}"
fi
if ! TREE_ROOT="$(node "$SCRIPT_DIR/scripts/sync-cursor-edition.js" --print-tree-root)"; then
  echo "Install error: cannot resolve where the generated cursor tree lands" >&2
  exit 1
fi
SOURCE_TREE="$TREE_ROOT/.cursor$FORGE_SUFFIX"

if [[ "$UNINSTALL" -ne 1 ]]; then
  echo "Kaola-Workflow · cursor edition ($FORGE) — refreshing generated tree..."
  node "$SCRIPT_DIR/scripts/sync-cursor-edition.js" --forge="$FORGE" --check >/dev/null 2>&1 \
    || node "$SCRIPT_DIR/scripts/sync-cursor-edition.js" --forge="$FORGE" --write >/dev/null
fi

if [[ "$REGENERATE" -eq 1 ]]; then
  echo "Regenerated $SOURCE_TREE from canonical. Done."
  exit 0
fi

confirm_install() {
  if [[ "$YES" -eq 1 ]]; then return 0; fi
  if [[ ! -t 0 ]]; then return 0; fi
  cat <<EOF
About to install the Kaola-Workflow cursor edition:
  agents + commands   → $LAYOUT_DEST
  support scripts     → $(cursor_home)/kaola-workflow/scripts
  hook scripts        → $LAYOUT_DEST/hooks
  hooks JSON          → $LAYOUT_DEST/hooks.json (merged; other entries kept)
EOF
  local reply=""
  read -r -p "Proceed? [Y/n] " reply || reply="n"
  case "$reply" in
    n|N|no|No|NO) echo "Aborted."; exit 0 ;;
  esac
}

if [[ "$GLOBAL" -eq 1 ]]; then
  DEST_ROOT="$(cursor_home)"
  LAYOUT_DEST="$DEST_ROOT"
  echo "Deploying globally ($FORGE) → $DEST_ROOT"
else
  if [[ -z "$TARGET" ]]; then
    echo "Install error: project materialization requires explicit --target DIR." >&2
    exit 2
  fi
  DEST_ROOT="$TARGET"
  LAYOUT_DEST="$DEST_ROOT/.cursor"
  echo "Deploying into project ($FORGE) → $DEST_ROOT"
fi

transaction_args=(--forge "$FORGE")
if [[ "$GLOBAL" -eq 1 ]]; then
  transaction_args+=(--scope global)
else
  transaction_args+=(--scope project --target "$DEST_ROOT")
fi
[[ "$NO_SCRIPTS" -eq 1 ]] && transaction_args+=(--no-scripts)

if [[ "$UNINSTALL" -eq 1 ]]; then
  node "$SCRIPT_DIR/scripts/kaola-workflow-cursor-surface.js" --uninstall "${transaction_args[@]}"
  echo "Uninstall complete; only receipt-proven unchanged bytes were removed."
  exit 0
fi

confirm_install
node "$SCRIPT_DIR/scripts/kaola-workflow-cursor-surface.js" --install \
  "${transaction_args[@]}" \
  --source-tree "$SOURCE_TREE" \
  --support-source "$FORGE_SCRIPTS_DIR"

if [[ "$GLOBAL" -eq 1 ]]; then
  echo "Global authority installed under $DEST_ROOT; no ambient project was materialized."
else
  echo "Project materialized from the receipt-verified global authority → $LAYOUT_DEST"
fi

echo ""
echo "Next: open the project in Cursor and run a workflow command, e.g.:"
echo "  /workflow-init"
