#!/usr/bin/env bash
# install-zcode.sh — deploy the Kaola-Workflow ZCode edition into a project (or globally).
#
# Additive standalone installer (does NOT modify install.sh, install-opencode.sh,
# install-kimi.sh, install-grok.sh, install-cursor.sh, or the claude/codex/gitlab/gitea
# editions). ZCode is a runtime (like opencode, Kimi, Grok, and Cursor), not a git forge,
# so it is delivered the ZCode-native way: named agents under .zcode/agents/, flat
# commands under .zcode/commands/. No Kaola prompt-lifecycle hook is installed:
# the measured one-million-token ZCode session does not need compact recovery,
# and per-tool hooks would add a subprocess/context surface without a use case.
#
# ZCode discovers subagents ONLY at user scope: a project install stages the agent
# roster under <project>/.zcode/agents/ AND syncs the same files to
# ${ZCODE_HOME:-$HOME/.zcode}/agents/ — the user scope is the one ZCode reads agents
# from; workspace-scope agents are unsupported in this beta.
#
# FORGE: --forge=github|gitlab|gitea selects which forge's workflow prose and support
# scripts to deploy (default github). The forge variants are GENERATED by
# sync-zcode-edition.js from the same routing surfaces the other editions ship;
# github renders .zcode/, a forge renders .zcode-<forge>/.
#
# Usage:
#   ./install-zcode.sh                         # deploy into the current directory
#   ./install-zcode.sh --target /path/to/repo  # deploy into a specific project
#   ./install-zcode.sh --forge=gitlab          # deploy the GitLab-shaped edition
#   ./install-zcode.sh --global                # deploy agents+commands to ${ZCODE_HOME:-~/.zcode}
#   ./install-zcode.sh --regenerate            # refresh the generated tree from canonical here
#
# DEPLOY LAYOUT (scope-dependent):
#   - PROJECT (--target/$PWD): agents and commands land under <project>/.zcode/{agents,commands}.
#     The agent roster is ALSO synced to ${ZCODE_HOME:-~/.zcode}/agents/.
#   - GLOBAL (--global): agents and commands land DIRECTLY under
#     ${ZCODE_HOME:-$HOME/.zcode}/{agents,commands} with no nested .zcode/ under the
#     ZCode home. Global install never creates ambient executable hooks.
#   - Support scripts (the real ones, from the install manifest) ALWAYS land under
#     ${ZCODE_HOME:-$HOME/.zcode}/kaola-workflow/scripts. Skip with --no-scripts.
#
# Models: generated agents pin model GLM-5.3 plus a canonical-tier thoughtLevel
# (standard high, reasoning max, heavy max) in frontmatter; this installer seeds no
# user-specific per-role model or effort config.

set -euo pipefail

KW_TMPDIR="${TMPDIR:-/tmp}"
case "$KW_TMPDIR" in
  /*) ;;
  *) KW_TMPDIR="/tmp" ;;
esac

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
TARGET=""
GLOBAL=0
REGENERATE=0
UNINSTALL=0
YES=0
NO_SCRIPTS=0
FORGE="github"

usage() {
  cat <<'EOF'
Usage: ./install-zcode.sh [--target DIR] [--forge=github|gitlab|gitea] [--global]
                         [--regenerate] [--uninstall] [--no-scripts] [--yes]
  --target DIR     deploy agents+commands into DIR/.zcode (default: current directory)
  --forge F        github (default), gitlab, or gitea — which forge's workflow prose
                   and support scripts to deploy
  --global         deploy global agents+commands only
  --regenerate     refresh the in-repo generated zcode tree from canonical, then exit
  --uninstall      remove the kaola-deployed zcode edition from the resolved scope
                   (honors --target/--global), then exit
  --no-scripts     skip support scripts and the kaola-workflow tree copy
  --yes            non-interactive (skip the confirmation prompt)

SUPPORT SCRIPTS: workflow commands resolve support scripts via
${ZCODE_HOME:-$HOME/.zcode}/kaola-workflow/scripts (the list comes from
scripts/kaola-workflow-install-manifest.js). Install and upgrade strip only
receipt-owned legacy Kaola declarations; foreign ZCode config stays untouched.

USER-SCOPE AGENTS: ZCode discovers subagents only at user scope (~/.zcode/agents),
so every project install also syncs the staged .zcode/agents/ roster there.

UNINSTALL: --uninstall removes ONLY kaola-deployed artifacts from the resolved
scope: the deployed agents and commands (by source-tree filename, both the staged
<project>/.zcode/agents copies and the ~/.zcode/agents sync), the support scripts
and project hook shells, the .zcode/kaola-workflow tree, legacy same-byte ambient
hook shells, and kaola entries in config.json
(other hook entries and foreign config keys stay).
EOF
}

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    --target) TARGET="${2:?--target requires a directory}"; shift 2 ;;
    --forge=*) FORGE="${1#--forge=}"; shift ;;
    --forge) FORGE="${2:?--forge requires github, gitlab, or gitea}"; shift 2 ;;
    --global) GLOBAL=1; shift ;;
    --regenerate) REGENERATE=1; shift ;;
    --uninstall) UNINSTALL=1; shift ;;
    --no-scripts) NO_SCRIPTS=1; shift ;;
    -y|--yes) YES=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

zcode_home() { printf '%s\n' "${ZCODE_HOME:-$HOME/.zcode}"; }

# Validate the forge BEFORE anything is written: an unknown forge refuses with
# exit 2 and leaves the target untouched.
FORGE_HELPER="$SCRIPT_DIR/scripts/runtime-edition-forge.js"
if [[ ! -f "$FORGE_HELPER" ]]; then
  echo "Install error: forge layout helper missing: $FORGE_HELPER" >&2
  exit 1
fi
if ! FORGE_SUFFIX="$(node "$FORGE_HELPER" --forge="$FORGE" --out-suffix)"; then
  echo "Install error: unknown forge \"$FORGE\" (expected github, gitlab, or gitea)" >&2
  exit 2
fi
if ! FORGE_SCRIPTS_DIR="$(node "$FORGE_HELPER" --forge="$FORGE" --scripts-dir)"; then
  echo "Install error: cannot resolve the support-script dir for forge $FORGE" >&2
  exit 1
fi
SYNC_JS="$SCRIPT_DIR/scripts/sync-zcode-edition.js"
if ! TREE_ROOT="$(node "$SYNC_JS" --print-tree-root)"; then
  echo "Install error: cannot resolve where the generated zcode tree lands" >&2
  exit 1
fi
SOURCE_TREE="$TREE_ROOT/.zcode$FORGE_SUFFIX"

if [[ "$UNINSTALL" -ne 1 ]]; then
  echo "Kaola-Workflow · zcode edition ($FORGE) — refreshing generated tree..."
  node "$SYNC_JS" --forge="$FORGE" --check >/dev/null 2>&1 \
    || node "$SYNC_JS" --forge="$FORGE" --write >/dev/null
fi

if [[ "$REGENERATE" -eq 1 ]]; then
  echo "Regenerated $SOURCE_TREE from canonical. Done."
  exit 0
fi

# Names here are removed on install and uninstall by basename.
RETIRED_AGENTS=()
RETIRED_COMMANDS=()
# This pre-wrapper hook had no generated byte authority; its exact ownership receipt is the
# authority for retiring the basename. The later compact/runtime wrappers are handled separately
# by retire_generated_hook_shells(), which deletes only byte-identical generated content.
RETIRED_HOOKS=(kaola-workflow-subagent-dispatch-log.sh)
RETIRED_SUPPORT_SCRIPTS=()

WORKFLOW_COMMANDS=(
  kaola-workflow-finalize workflow-init workflow-next
)
in_array() { local needle="$1"; shift; local x; for x in "$@"; do [[ "$x" == "$needle" ]] && return 0; done; return 1; }

is_plain_basename() {
  local n="${1-}"
  [[ -n "$n" ]] || return 1
  case "$n" in
    */*|*\\*|.|..) return 1 ;;
  esac
  return 0
}

copy_agents() {
  local dest="$1"
  mkdir -p "$dest"
  if [[ "$SOURCE_TREE/agents" -ef "$dest" ]]; then
    echo "Self-dev deploy (source $SOURCE_TREE/agents is already the live tree) → copy skipped."
    return
  fi
  local retired
  for retired in "${RETIRED_AGENTS[@]+"${RETIRED_AGENTS[@]}"}"; do
    [[ -f "$dest/$retired.md" ]] || continue
    rm -f "$dest/$retired.md"
  done
  local src base count=0
  for src in "$SOURCE_TREE/agents/"*.md; do
    [[ -f "$src" ]] || continue
    base="$(basename "$src")"
    cp "$src" "$dest/$base"
    count=$((count + 1))
  done
  if [[ "$count" -eq 0 ]]; then
    echo "Install error: no agent sources found in $SOURCE_TREE/agents" >&2
    exit 1
  fi
  echo "Installed workflow agents → $dest/ ($count)"
}

copy_commands() {
  local dest="$1"
  mkdir -p "$dest"
  if [[ "$SOURCE_TREE/commands" -ef "$dest" ]]; then
    echo "Self-dev deploy (source $SOURCE_TREE/commands is already the live tree) → copy skipped."
    return
  fi
  local retired
  for retired in "${RETIRED_COMMANDS[@]+"${RETIRED_COMMANDS[@]}"}"; do
    [[ -f "$dest/$retired.md" ]] || continue
    rm -f "$dest/$retired.md"
  done
  local src base count=0 skipped=0
  for src in "$SOURCE_TREE/commands/"*.md; do
    [[ -f "$src" ]] || continue
    base="$(basename "$src" .md)"
    if ! in_array "$base" "${WORKFLOW_COMMANDS[@]}"; then
      echo "warning: skipping unrecognized command not in the workflow set: $base" >&2
      skipped=$((skipped + 1))
      continue
    fi
    cp "$src" "$dest/$base.md"
    count=$((count + 1))
  done
  if [[ "$count" -eq 0 ]]; then
    if [[ "$skipped" -gt 0 ]]; then
      echo "Install error: all $skipped command source(s) in $SOURCE_TREE/commands fall outside the workflow set" >&2
    else
      echo "Install error: no command sources found in $SOURCE_TREE/commands" >&2
    fi
    exit 1
  fi
  echo "Installed workflow commands → $dest/"
}

# ZCode discovers subagents only at user scope, so a project install syncs the
# staged roster to ${ZCODE_HOME:-~/.zcode}/agents as well.
sync_agents_to_user_scope() {
  local home; home="$(zcode_home)"
  copy_agents "$home/agents"
  echo "Synced agent roster to user scope → $home/agents (ZCode reads agents from user scope only)"
}

install_support_scripts() {
  if [[ "$NO_SCRIPTS" -eq 1 ]]; then
    echo "Support scripts skipped (--no-scripts)."
    return
  fi
  local home; home="$(zcode_home)"
  local manifest="$SCRIPT_DIR/scripts/kaola-workflow-install-manifest.js"
  [[ -f "$manifest" ]] || { echo "warning: install manifest not found; skipping support scripts." >&2; return; }
  local dest="$home/kaola-workflow/scripts"
  mkdir -p "$dest"
  local name src
  local deployed=()
  while IFS= read -r name || [[ -n "$name" ]]; do
    [[ -n "$name" ]] || continue
    src="$FORGE_SCRIPTS_DIR/$name"
    [[ -f "$src" ]] || src="$SCRIPT_DIR/scripts/$name"
    if [[ ! -f "$src" ]]; then
      echo "Install error: allowlisted support script missing from source for forge $FORGE: $name" >&2
      exit 1
    fi
    cp "$src" "$dest/$name"
    chmod +x "$dest/$name"
    deployed+=("$name")
  done < <(node "$manifest" --forge="$FORGE" --scripts 2>/dev/null)
  if [[ ${#deployed[@]} -gt 0 ]]; then
    local stale_file stale_name is_current
    for stale_file in "$dest"/*.js; do
      [[ -f "$stale_file" ]] || continue
      stale_name="$(basename "$stale_file")"
      is_current=0
      for name in "${deployed[@]}"; do
        [[ "$name" == "$stale_name" ]] && is_current=1 && break
      done
      if [[ "$is_current" -eq 0 ]]; then
        rm -f "$stale_file"
        echo "Removed stale script: $stale_file"
      fi
    done
  fi
  echo "Installed support scripts → $dest (forge $FORGE)"
}

# Pre-trust-gate installers copied executable hook shells into the user home even
# though current workspace declarations execute the project carrier. Retire only
# byte-identical copies; a locally modified file is not ours to delete and is not
# active after its receipt-owned user declaration is stripped.
retire_legacy_user_hook_shells() {
  local hooks_dest="$(zcode_home)/kaola-workflow/hooks"
  [[ -d "$hooks_dest" ]] || return 0
  local hook hook_base installed retired legacy_receipt
  legacy_receipt="$(zcode_home)/kaola-workflow/zcode-hooks-state.json"
  for hook in "$SOURCE_TREE/kaola-workflow/hooks/"*.sh; do
    [[ -f "$hook" ]] || continue
    hook_base="$(basename "$hook")"
    installed="$hooks_dest/$hook_base"
    [[ -f "$installed" ]] || continue
    if cmp -s "$hook" "$installed"; then
      rm -f "$installed"
      echo "Removed legacy ambient hook shell: $installed"
    else
      echo "warning: retained modified legacy hook shell (not active): $installed" >&2
    fi
  done
  # A generated wrapper basename is not sufficient ownership proof: a user may have edited the
  # file after an older install. Retire only the exact historical bytes still represented by the
  # migration renderer. The older compact wrapper intentionally has no live renderer anymore;
  # its locally modified residue is therefore preserved instead of reconstructed or guessed.
  retire_generated_hook_shells "$hooks_dest"
  if [[ -e "$legacy_receipt" || -L "$legacy_receipt" ]]; then
    for retired in "${RETIRED_HOOKS[@]+"${RETIRED_HOOKS[@]}"}"; do
      [[ -f "$hooks_dest/$retired" ]] || continue
      rm -f "$hooks_dest/$retired"
      echo "Removed receipt-owned retired hook shell: $hooks_dest/$retired"
    done
  fi
  rmdir "$hooks_dest" 2>/dev/null || true
}

# The just-retired project declaration receipt proves these basenames were
# Kaola carriers. Delete only byte-identical generated shells; modified files
# remain inert and user-owned.
retire_generated_hook_shells() {
  local hooks_dest="$1"
  [[ -d "$hooks_dest" ]] || return 0
  ZCODE_SYNC_JS="$SYNC_JS" ZCODE_FORGE="$FORGE" ZCODE_HOOKS_DEST="$hooks_dest" node <<'NODE'
const fs = require('fs');
const path = require('path');
const sync = require(process.env.ZCODE_SYNC_JS);
const forge = process.env.ZCODE_FORGE;
const root = process.env.ZCODE_HOOKS_DEST;
const expected = new Map([
  [sync.RUNTIME_WRAPPER, sync.renderRuntimeHookWrapper(forge)],
]);
for (const [name, bytes] of expected) {
  const file = path.join(root, name);
  let stat;
  try { stat = fs.lstatSync(file); } catch (error) {
    if (error && error.code === 'ENOENT') continue;
    throw error;
  }
  if (!stat.isFile() || stat.isSymbolicLink()) continue;
  if (fs.readFileSync(file, 'utf8') === bytes) {
    fs.unlinkSync(file);
    process.stdout.write('Removed inert generated hook shell: ' + file + '\n');
  } else {
    process.stderr.write('warning: retained modified inert hook shell: ' + file + '\n');
  }
}
NODE
  rmdir "$hooks_dest" 2>/dev/null || true
}

# Copy generated support-script launchers into the project edition carrier.
install_edition_dir() {
  if [[ "$NO_SCRIPTS" -eq 1 ]]; then
    return
  fi
  local dest="$LAYOUT_DEST/kaola-workflow"
  if [[ -d "$SOURCE_TREE/kaola-workflow" && -d "$dest" && "$SOURCE_TREE/kaola-workflow" -ef "$dest" ]]; then
    echo "Self-dev deploy (generated edition directory is already the project carrier) → copy skipped."
    return
  fi
  mkdir -p "$dest/scripts"
  local f
  for f in "$SOURCE_TREE/kaola-workflow/scripts/"*.js; do
    [[ -f "$f" ]] || continue
    cp "$f" "$dest/scripts/$(basename "$f")"
    chmod 755 "$dest/scripts/$(basename "$f")"
  done
  echo "Installed edition script launchers → $dest"
}

install_hook_declarations() {
  if [[ "$NO_SCRIPTS" -eq 1 ]]; then
    echo "Hook mapping skipped (--no-scripts)."
    return
  fi
  # Remove only the exact user-level rows owned by pre-trust-gate installers.
  # The receipt is the authority; an unreceipted user hook remains untouched.
  local legacy_config="$(zcode_home)/cli/config.json"
  local legacy_receipt="$(zcode_home)/kaola-workflow/zcode-hooks-state.json"
  if [[ -e "$legacy_receipt" || -L "$legacy_receipt" ]]; then
    if ! node "$SYNC_JS" --strip-hooks "--dest=$legacy_config" "--receipt=$legacy_receipt" "--forge=$FORGE"; then
      echo "Install error: failed to retire receipt-owned user hooks from $legacy_config" >&2
      exit 1
    fi
    echo "Retired receipt-owned ambient user hooks → $legacy_config"
  fi
  if [[ "$GLOBAL" -eq 0 ]]; then
    local dest_json="$LAYOUT_DEST/config.json"
    local receipt="$LAYOUT_DEST/kaola-workflow/zcode-hooks-state.json"
    if [[ -e "$receipt" || -L "$receipt" ]]; then
      if ! node "$SYNC_JS" --strip-hooks "--dest=$dest_json" "--receipt=$receipt" "--forge=$FORGE"; then
        echo "Install error: failed to retire receipt-owned project hooks from $dest_json" >&2
        exit 1
      fi
      echo "Retired receipt-owned project hooks → $dest_json"
    fi
  fi
  echo "Kaola prompt-lifecycle hooks: not installed."
}

assert_hook_path_safe() {
  local file="$1" label="$2"
  if [[ -L "$file" ]]; then
    echo "Install error: $label is a symbolic link; refusing to follow or replace it: $file" >&2
    return 1
  fi
  if [[ -e "$file" && ! -f "$file" ]]; then
    echo "Install error: $label is not a regular file: $file" >&2
    return 1
  fi
}

# Validate every config/receipt ownership boundary before migration mutates any
# of them. Otherwise a later project-carrier refusal can leave the legacy user
# carrier partially stripped.
preflight_hook_carriers() {
  local home; home="$(zcode_home)"
  assert_hook_path_safe "$home/cli/config.json" "legacy ZCode hook config"
  assert_hook_path_safe "$home/kaola-workflow/zcode-hooks-state.json" "legacy ZCode hook receipt"
  if [[ "$GLOBAL" -eq 0 ]]; then
    local layout="${TARGET:-$PWD}/.zcode"
    assert_hook_path_safe "$layout/config.json" "project ZCode hook config"
    assert_hook_path_safe "$layout/kaola-workflow/zcode-hooks-state.json" "project ZCode hook receipt"
  fi
}

uninstall_edition() {
  local home layout
  home="$(zcode_home)"
  if [[ "$GLOBAL" -eq 1 ]]; then
    layout="$home"
  else
    layout="${TARGET:-$PWD}/.zcode"
  fi
  preflight_hook_carriers || return 1
  echo "Uninstalling Kaola-Workflow · zcode edition ($FORGE) from → $layout"
  if [[ -d "$layout" && "$SOURCE_TREE" -ef "$layout" ]]; then
    echo "Refusing to uninstall the edition's OWN source tree ($layout). No-op." >&2
    return
  fi
  local f retired
  # Kaola-deployed agent names, from the generated source tree.
  if [[ -d "$SOURCE_TREE/agents" ]]; then
    for f in "$SOURCE_TREE/agents/"*.md; do
      [[ -f "$f" ]] || continue
      # staged copies (project scope) ...
      [[ -d "$layout/agents" ]] && rm -f "$layout/agents/$(basename "$f")"
      # ... and the user-scope sync (ZCode discovery).
      [[ -d "$home/agents" ]] && rm -f "$home/agents/$(basename "$f")"
    done
  fi
  for retired in "${RETIRED_AGENTS[@]+"${RETIRED_AGENTS[@]}"}"; do
    [[ -f "$layout/agents/$retired.md" ]] || continue
    rm -f "$layout/agents/$retired.md"
  done
  if [[ -d "$SOURCE_TREE/commands" && -d "$layout/commands" ]]; then
    for f in "$SOURCE_TREE/commands/"*.md; do
      [[ -f "$f" ]] || continue
      rm -f "$layout/commands/$(basename "$f")"
    done
  fi
  for retired in "${RETIRED_COMMANDS[@]+"${RETIRED_COMMANDS[@]}"}"; do
    [[ -f "$layout/commands/$retired.md" ]] || continue
    rm -f "$layout/commands/$retired.md"
  done
  # The kaola-workflow edition dir under the project layout.
  if [[ -d "$layout/kaola-workflow" ]]; then
    if [[ -d "$SOURCE_TREE/kaola-workflow/hooks" ]]; then
      for f in "$SOURCE_TREE/kaola-workflow/hooks/"*.sh; do
        [[ -f "$f" ]] || continue
        rm -f "$layout/kaola-workflow/hooks/$(basename "$f")"
      done
    fi
    for retired in "${RETIRED_HOOKS[@]+"${RETIRED_HOOKS[@]}"}"; do
      [[ -f "$layout/kaola-workflow/hooks/$retired" ]] || continue
      rm -f "$layout/kaola-workflow/hooks/$retired"
    done
    retire_generated_hook_shells "$layout/kaola-workflow/hooks"
    if [[ -d "$SOURCE_TREE/kaola-workflow/scripts" ]]; then
      for f in "$SOURCE_TREE/kaola-workflow/scripts/"*.js; do
        [[ -f "$f" ]] || continue
        rm -f "$layout/kaola-workflow/scripts/$(basename "$f")"
      done
    fi
    if [[ -d "$SOURCE_TREE/kaola-workflow/prompts" ]]; then
      for f in "$SOURCE_TREE/kaola-workflow/prompts/"*.md; do
        [[ -f "$f" ]] || continue
        rm -f "$layout/kaola-workflow/prompts/$(basename "$f")"
      done
    fi
  fi
  # Strip current project declarations and legacy user declarations only when
  # their exact ownership receipts exist. Trust records are intentionally left
  # to ZCode; without declarations they execute nothing, and reinstalling the
  # same digest preserves the user's prior decision.
  local project_config="$layout/config.json"
  local project_receipt="$layout/kaola-workflow/zcode-hooks-state.json"
  if [[ "$GLOBAL" -ne 1 && ( -e "$project_receipt" || -L "$project_receipt" ) ]]; then
    if ! node "$SYNC_JS" --strip-hooks "--dest=$project_config" "--receipt=$project_receipt" "--forge=$FORGE"; then
      echo "Uninstall error: failed to strip receipt-owned hooks from $project_config" >&2
      return 1
    fi
  fi
  local legacy_config="$home/cli/config.json"
  local legacy_receipt="$home/kaola-workflow/zcode-hooks-state.json"
  if [[ -e "$legacy_receipt" || -L "$legacy_receipt" ]]; then
    if ! node "$SYNC_JS" --strip-hooks "--dest=$legacy_config" "--receipt=$legacy_receipt" "--forge=$FORGE"; then
      echo "Uninstall error: failed to strip receipt-owned legacy hooks from $legacy_config" >&2
      return 1
    fi
  fi
  rmdir "$layout/kaola-workflow/hooks" 2>/dev/null || true
  rmdir "$layout/kaola-workflow/scripts" 2>/dev/null || true
  rmdir "$layout/kaola-workflow/prompts" 2>/dev/null || true
  rmdir "$layout/kaola-workflow" 2>/dev/null || true
  rmdir "$layout/agents" 2>/dev/null || true
  rmdir "$layout/commands" 2>/dev/null || true
  if [[ "$GLOBAL" -ne 1 ]]; then rmdir "$layout" 2>/dev/null || true; fi
  echo "Removed deployed agents + commands (staged and user-scope) and the edition dir."
  local scripts_dir="$home/kaola-workflow/scripts"
  local hooks_dir="$home/kaola-workflow/hooks"
  local manifest="$SCRIPT_DIR/scripts/kaola-workflow-install-manifest.js"
  if [[ -f "$manifest" && -d "$scripts_dir" ]]; then
    local name
    while IFS= read -r name || [[ -n "$name" ]]; do
      [[ -n "$name" ]] || continue
      if ! is_plain_basename "$name"; then
        echo "warning: ignoring support-script manifest entry that is not a plain file name: $name" >&2
        continue
      fi
      rm -f "$scripts_dir/$name"
    done < <(node "$manifest" --forge="$FORGE" --scripts 2>/dev/null)
  fi
  if [[ -d "$hooks_dir" && -d "$SOURCE_TREE/kaola-workflow/hooks" ]]; then
    local hook
    for hook in "$SOURCE_TREE/kaola-workflow/hooks/"*.sh; do
      [[ -f "$hook" ]] || continue
      rm -f "$hooks_dir/$(basename "$hook")"
    done
  fi
  if [[ -d "$hooks_dir" ]]; then
    local retired_hook
    for retired_hook in "${RETIRED_HOOKS[@]+"${RETIRED_HOOKS[@]}"}"; do
      [[ -f "$hooks_dir/$retired_hook" ]] || continue
      rm -f "$hooks_dir/$retired_hook"
    done
  fi
  retire_generated_hook_shells "$hooks_dir"
  rmdir "$scripts_dir" 2>/dev/null || true
  rmdir "$hooks_dir" 2>/dev/null || true
  rmdir "$home/kaola-workflow" 2>/dev/null || true
  echo "Removed deployed support scripts + hook shells; stripped receipt-owned project/legacy hooks."
  echo "Uninstall complete. A fresh ./install-zcode.sh now deploys the workflow edition."
}

confirm_install() {
  if [[ "$YES" -eq 1 ]]; then return 0; fi
  if [[ ! -t 0 ]]; then return 0; fi
  cat <<EOF
About to install the Kaola-Workflow zcode edition:
  agents + commands   → $LAYOUT_DEST (+ agent roster synced to $(zcode_home)/agents)
  support scripts     → $(zcode_home)/kaola-workflow/scripts
  hook declarations   → none
EOF
  local reply=""
  read -r -p "Proceed? [Y/n] " reply || reply="n"
  case "$reply" in
    n|N|no|No|NO) echo "Aborted."; exit 0 ;;
  esac
}

if [[ "$UNINSTALL" -eq 1 ]]; then
  uninstall_edition
  exit 0
fi

if [[ "$GLOBAL" -eq 1 ]]; then
  DEST_ROOT="$(zcode_home)"
  LAYOUT_DEST="$DEST_ROOT"
  echo "Deploying globally ($FORGE) → $DEST_ROOT"
else
  DEST_ROOT="${TARGET:-$PWD}"
  LAYOUT_DEST="$DEST_ROOT/.zcode"
  echo "Deploying into project ($FORGE) → $DEST_ROOT"
fi

confirm_install
preflight_hook_carriers
copy_agents "$LAYOUT_DEST/agents"
copy_commands "$LAYOUT_DEST/commands"
sync_agents_to_user_scope
# The edition dir and the support-script home can alias (globally or when a
# project sets ZCODE_HOME to its .zcode directory), so real manifest scripts
# must always be the final copy. Hooks are safe to refresh in either location.
install_edition_dir
install_support_scripts
retire_legacy_user_hook_shells
install_hook_declarations
if [[ "$GLOBAL" -eq 0 ]]; then
  retire_generated_hook_shells "$LAYOUT_DEST/kaola-workflow/hooks"
fi

# Report the project declaration carrier after every project install. This is
# diagnostic only: ZCode owns trust, the generator owns declarations, and the
# receipt owns cleanup.
report_hook_diagnostics() {
  [[ "$GLOBAL" -eq 0 ]] || return 0
  local config_file="$LAYOUT_DEST/config.json"
  [[ -f "$config_file" ]] || return 0
  ZCODE_HOOK_CONFIG="$config_file" node <<'NODE'
const fs = require('fs');
const file = process.env.ZCODE_HOOK_CONFIG;
try {
  const config = JSON.parse(fs.readFileSync(file, 'utf8'));
  const events = config && config.hooks && config.hooks.events;
  const names = events && typeof events === 'object' && !Array.isArray(events)
    ? Object.keys(events) : [];
  let matcherRows = 0;
  let hookCount = 0;
  let invalidRows = 0;
  for (const name of names) {
    const rows = Array.isArray(events[name]) ? events[name] : [];
    matcherRows += rows.length;
    for (const row of rows) {
      if (!row || typeof row !== 'object' || !Array.isArray(row.hooks)) {
        invalidRows++;
        continue;
      }
      hookCount += row.hooks.length;
    }
  }
  console.log('ZCode 3.10.1 config=' + file + ' events=' + names.join(',')
    + ' matcherRows=' + matcherRows + ' hookCount=' + hookCount
    + ' invalidRows=' + invalidRows);
  if (invalidRows > 0) process.exitCode = 1;
} catch (error) {
  console.error('ZCode 3.10.1 config diagnostics unavailable: ' + error.message);
  process.exitCode = 1;
}
NODE
}

report_hook_diagnostics

echo ""
echo "Next: open the project in ZCode and run /workflow-init or /workflow-next."
